Job.create(name: "Actor")
Job.create(name: "Director")
Job.create(name: "Screenwriter")

Category.create(name: "Picture")
Category.create(name: "Director")
Category.create(name: "Actress")
Category.create(name: "Actor")
Category.create(name: "Supporting Actor")
Category.create(name: "Supporting Actress")
Category.create(name: "Screenplay")
Category.create(name: "Scene")
