class Movie < ActiveRecord::Base
  include Skandies::Maths

  belongs_to :year
  has_many :credits
  has_many :votes
  has_many :ratings
  has_many :scenes

  validates :title, presence: true
  validates :year, presence: true
  validates :title_index, presence: true

  before_validation :compute_title_index

  scope :by_title, -> { order("title_index ASC") }

  def self.results_list(year, category)
    if category.name == "director"
      where("year_id = ? and director_points > 0",year.id).order(director_points: :desc, director_votes: :desc, title_index: :asc)
    elsif category.name == "screenplay"
      where("year_id = ? and screenplay_points > 0",year.id).order(screenplay_points: :desc, screenplay_votes: :desc, title_index: :asc)
    else # category is best picture
      where("year_id = ? and picture_points > 0",year.id).order(picture_points: :desc, picture_votes: :desc, title_index: :asc)
    end
  end

  def self.ratings_results_list(year)
    where("year_id = ? and nbr_ratings > 4", year.id).order(average_rating: :desc, title_index: :asc)
  end

  def self.less_than_five_ratings(year)
    where("year_id = ? and nbr_ratings < 5 and nbr_ratings > 0",year.id).order(title_index: :asc)
  end

  def self.zero_ratings(year)
    where(year: year, nbr_ratings: 0).order(title_index: :asc)
  end

  def ratings_results_display_format
    if nbr_ratings < 10
      "(" + title + ")"
    else
      title
    end
  end

  def points_in_category(category)
    if category.name == "director"
      director_points
    elsif category.name == "screenplay"
      screenplay_points
    else
      picture_points
    end
  end

  def nbr_votes_in_category(category)
    if category.name == "director"
      director_votes
    elsif category.name == "screenplay"
      screenplay_votes
    else
      picture_votes
    end
  end

  def director_name
    if director_display
      director_display
    else
      director_job = Job.where(name: "director").first
      credit = credits.where(job: director_job).first
      if credit
        credit.person.name
      end
    end
  end

  def screenwriter_name
    if screenwriter_display
      screenwriter_display
    else
      screenwriter_job = Job.where(name: "screenwriter").first
      credit = credits.where(job: screenwriter_job).first
      if credit
        credit.person.name
      end
    end
  end

  def compute_title_index
    if title
      title_without_leading_article = title.gsub(/(The|A|An)\s/,"")
      if $1
        self.title_index = title_without_leading_article + ", " + $1
      else
        self.title_index = title
      end
    end
  end

  def compute_points(category)
    points = 0
    self.votes.where( category: category ).each do |v|
      points = points + v.points
    end
    points
  end

  def compute_votes(category)
    self.votes.where( category: category ).count
  end

  def compute_total_nbr_ratings
    ratings.count
  end

  def compute_average_rating
    points = 0
    if ratings.count > 0
      ratings.each do |r|
        points = points + r.value
      end
      average = (points / ratings.count).round(2)
    end
  end

  def compute_nbr_ratings(value)
    nbr_ratings = ratings.where(value: value).count
    if nbr_ratings
      nbr_ratings
    else
      0
    end
  end

  def compute_standard_dev
    values = ratings.map { |r| r.value }
    Skandies::Maths.standard_deviation(values).round(2)
  end

  def self.load_new_movies
    Movie.new_movie_array.each do |movie_title|
      m = Movie.new
      m.title = movie_title
      m.year_id = 20
      m.save
    end
  end

  def self.new_movie_array
    new_movie_array = [
    "#Stuck",
    "1 - Nenokkadine",
    "1,000 Times Good Night",
    "10 Rules for Sleeping Around",
    "12 O'Clock Boys",
    "13 Sins",
    "2 Autumns, 3 Winters",
    "2 States",
    "20,000 Days on Earth",
    "2014 Oscar-Nominated Animation Shorts",
    "2014 Oscar-Nominated Documentary Shorts",
    "2014 Oscar-Nominated Live-Action Shorts",
    "2014 Sundance Film Festival Short Films",
    "21 Years: Richard Linklater",
    "22 Jump Street",
    "23 Blast",
    "24 Exposures",
    "3 Days to Kill",
    "300: Rise of an Empire",
    "37: A Final Promise",
    "4 Minute Mile",
    "4 Moons",
    "7 Boxes",
    "Aatsinki: The Story of Arctic Cowboys",
    "Aberdeen",
    "About Alex",
    "About Last Night",
    "Abuse of Weakness",
    "Action Jackson",
    "Actress",
    "Addicted",
    "The Admiral: Roaring Currents",
    "Adult World",
    "Advanced Style",
    "Afflicted",
    "Affluenza",
    "After",
    "After the Dark",
    "After the Fall",
    "Aftermath (Peter Engert)",
    "Aftermath (Thomas Farone)",
    "Afternoon of a Faun: Tanaquil Le Clercq",
    "Age of Uprising: The Legend of Michael Kohlhaas",
    "Ai Weiwei: The Fake Case",
    "Alan Partridge",
    "Alexander and the Terrible, Horrible, No Good, Very Bad Day",
    "Algorithms",
    "Alien Abduction",
    "Alive Inside",
    "All Cheerleaders Die",
    "All Relative",
    "All You Need Is Love",
    "Almost Human",
    "The Almost Man",
    "Altered States of Plaine",
    "Altina",
    "Alumbrones",
    "Always Woodstock",
    "Amapola",
    "The Amazing Catfish",
    "The Amazing Spider-Man 2",
    "America",
    "America the Beautiful 3: The Sexualization of Our Youth",
    "An American in Hollywood",
    "American Jesus",
    "The American Nurse",
    "American Revolutionary: The Evolution of Grace Lee Boggs",
    "American Sniper",
    "Among Ravens",
    "And So It Goes",
    "The Angriest Man in Brooklyn",
    "Animal",
    "Anita",
    "Annabelle",
    "Annie",
    "The Anonymous People",
    "Another Me",
    "Antarctica: A Year on Ice",
    "Ape",
    "Apocalypse: A Bill Callahan Tour Film",
    "Archaeology of a Woman",
    "Are You Here",
    "Art and Craft",
    "The Art of the Steal",
    "As Above, So Below",
    "As It Is in Heaven",
    "Asmodexia",
    "At Middleton",
    "At the Devil's Door",
    "Atlas Shrugged: Who Is John Galt?",
    "The Attorney",
    "Authors Anonymous",
    "Automata",
    "Autonagar Surya",
    "Awake: The Life of Yogananda",
    "Awakened",
    "Awful Nice",
    "The Babadook",
    "Back in the Day",
    "Back in Time",
    "Bad Hair",
    "Bad Johnson",
    "Bad Turn Worse",
    "Bad Words",
    "The Bag Man",
    "Band of Sisters",
    "Bang Bang!",
    "Barbecue",
    "Barefoot",
    "The Barefoot Artist",
    "The Battered Bastards of Baseball",
    "Bears",
    "Before I Disappear",
    "Before I Go to Sleep",
    "Before You Know It",
    "Begin Again",
    "Beijing Love Story",
    "Being Ginger",
    "Believe Me",
    "Belle",
    "Beneath",
    "Beneath the Harvest Sky",
    "Beside Still Waters",
    "The Best of Me",
    "The Best Offer",
    "Bethlehem",
    "The Better Angels",
    "Better Living Through Chemistry",
    "Bewakoofiyaan",
    "Beyond Beyond",
    "Beyond Outrage",
    "Beyond the Edge",
    "Beyond the Lights",
    "Bhoothnath Returns",
    "Bhopal: A Prayer for Rain",
    "Bicycling With Molière",
    "Big Bad Wolves",
    "Big Eyes",
    "Big Hero 6",
    "Big Men",
    "Billy Bates",
    "Bird People",
    "A Birder's Guide to Everything",
    "Birdman, or (The Unexpected Virtue of Ignorance)",
    "Bitter Honey",
    "Björk: Biophilia Live",
    "Black Out",
    "Blended",
    "Blood Glacier",
    "Blood Ransom",
    "Blood Ties",
    "The Blue Room",
    "Blue Ruin",
    "Blumenthal",
    "Bobby Jasoos",
    "The Book of Life",
    "Borgman",
    "Born to Fly: Elizabeth Streb vs. Gravity",
    "Botso",
    "Bottled Up",
    "Bound by Flesh",
    "The Boxtrolls",
    "Boyhood",
    "Braddock America",
    "Brahmin Bulls",
    "Breaking the Frame",
    "Breakthrough Weekend",
    "Breakup Buddies",
    "The Breakup Guru",
    "Breastmilk",
    "Breathe In",
    "Brick Mansions",
    "Bright Days Ahead",
    "Brightest Star",
    "Brothers Hypnotic",
    "Brush With Danger",
    "Buno Haansh",
    "Burning Blue",
    "Burning Bush",
    "Burt's Buzz",
    "But Always",
    "Butter on the Latch",
    "The Butterfly Room",
    "Cabin Fever: Patient Zero",
    "Calvary",
    "Cam2Cam",
    "Camp X-Ray",
    "The Canal",
    "Canopy",
    "Cantinflas",
    "Captain America: The Winter Soldier",
    "Captivated: The Trials of Pamela Smart",
    "The Captive",
    "The Case Against 8",
    "Catch Hell",
    "Cavemen",
    "Cesar Chavez",
    "Cesar's Last Fast",
    "Chaplin of the Mountains",
    "Chapman",
    "Charlie Victor Romeo",
    "Cheap Thrills",
    "Chef",
    "Child of God",
    "Child's Pose",
    "Chinese Puzzle",
    "Chlorine",
    "The Circle",
    "Citizen Koch",
    "Citizenfour",
    "Closed Curtain",
    "Code Black",
    "A Coffee in Berlin",
    "Coherence",
    "Cold Bloom",
    "Cold Comes the Night",
    "Cold in July",
    "The Cold Lands",
    "Coldwater",
    "The Color of Time",
    "Come Back to Me",
    "Comet",
    "Concerning Violence",
    "The Congress",
    "Copenhagen",
    "Cuban Fury",
    "The Culture High",
    "Cyber-Seniors",
    "Daawat-e-Ishq",
    "DamNation",
    "The Damned",
    "The Dance of Reality",
    "Dancing in Jaffa",
    "Dark House",
    "Date and Switch",
    "Dawn of the Planet of the Apes",
    "Days and Nights",
    "Dead Snow: Red vs Dead",
    "Dear White People",
    "Death Metal Angola",
    "The Decent One",
    "Decoding Annie Parker",
    "Dedh Ishqiya",
    "Deepsea Challenge 3D",
    "Default",
    "Deliver Us From Evil",
    "Delusions of Guinevere",
    "Demi-soeur",
    "The Den",
    "Desert Riders",
    "Devil's Due",
    "The Devil's Hand",
    "Devil's Knot",
    "Dinosaur 13",
    "Diplomacy",
    "The Disappearance of Eleanor Rigby: Her",
    "The Disappearance of Eleanor Rigby: Him",
    "The Disappearance of Eleanor Rigby: Them",
    "The Discoverers",
    "Dishkiyaaoon",
    "Divergent",
    "Divorce Corp.",
    "Do You Know What My Name Is?",
    "Documented",
    "The Dog",
    "Dolphin Tale 2",
    "Dom Hemingway",
    "Don Peyote",
    "Don't Go Breaking My Heart 2",
    "Dormant Beauty",
    "The Double",
    "Double Play: James Benning | Richard Linklater",
    "Dr. Cabbie",
    "Dracula Untold",
    "Draft Day",
    "Drive Hard",
    "The Drop",
    "Drug Lord: The Legend of Shorty",
    "Drunktown's Finest",
    "Dumb and Dumber To",
    "Dumbbells",
    "Dying of the Light",
    "E-Team",
    "Earth to Echo",
    "Easy Money: Hard to Kill",
    "Edge of Tomorrow",
    "El Crimen del Cácaro Gumaro",
    "Elaine Stritch: Shoot Me",
    "Elena",
    "Elsa & Fred",
    "Emoticon ;)",
    "The Empty Hours",
    "Endless Love",
    "Enemies Closer",
    "Enemy",
    "Entertainment",
    "The Equalizer",
    "Ernest & Celestine",
    "Eternity: The Movie",
    "Evergreen: The Road to Legalization",
    "Everybody Street",
    "Evolution of a Criminal",
    "Exhibition",
    "Exists",
    "Exodus: Gods and Kings",
    "Expedition to the End of the World",
    "Expelled",
    "The Expendables 3",
    "Exposed",
    "Extraterrestrial",
    "The Face of Love",
    "Fading Gigolo",
    "Faith Connections",
    "Falcon Rising",
    "Fanny",
    "A Fantastic Fear of Everything",
    "Farmland",
    "Fatal Assistance",
    "The Fatal Encounter",
    "The Fault in Our Stars",
    "Fed Up",
    "Felony",
    "A Field in England",
    "Fifi Howls From Happiness",
    "Filmistaan",
    "Filth",
    "The Final Member",
    "Finding Fanny",
    "Finding Fela",
    "Finding Vivian Maier",
    "Fishing Without Nets",
    "A Five Star Life",
    "Flex Is Kings",
    "The Fluffy Movie",
    "Fonzy",
    "Food Chains",
    "For a Woman",
    "For No Good Reason",
    "Force Majeure",
    "Fort Bliss",
    "Foxcatcher",
    "The Foxy Merkins",
    "A Fragile Trust",
    "Frank",
    "Frank Miller's Sin City: A Dame to Kill For",
    "Free Ride",
    "Free the Nipple",
    "The French Minister",
    "Frequencies",
    "Friended to Death",
    "From Both Sides of the Aegean: Expulsion and Exchange of Populations, Turkey-Greece: 1922-1924",
    "From the Rough",
    "Frontera",
    "The Frontier",
    "Fugly!",
    "A Fuller Life",
    "Fury",
    "G.B.F.",
    "Gabrielle",
    "The Galápagos Affair: Satan Came to Eden",
    "Gambit",
    "The Gambler",
    "Gang of Ghosts",
    "Gebo and the Shadow",
    "Generation War",
    "The German Doctor",
    "Get On Up",
    "Getting to The Nutcracker",
    "Gimme Shelter",
    "The Girl and Death",
    "Girl on a Bicycle",
    "A Girl Walks Home Alone at Night",
    "The Giver",
    "Glen Campbell: I'll Be Me",
    "Gloria",
    "Go Down Death",
    "God Help the Girl",
    "God the Father",
    "God's Not Dead",
    "God's Pocket",
    "Godzilla",
    "The Golden Era",
    "Gone Girl",
    "The Good Lie",
    "A Good Marriage",
    "Goodbye to All That",
    "Goodbye to Language",
    "Goodbye World",
    "Gore Vidal: The United States of Amnesia",
    "Govindudu Andari Vaadela",
    "The Grand Budapest Hotel",
    "Grand départ",
    "Grand Piano",
    "The Grand Seduction ",
    "The Great Flood",
    "The Great Invisible",
    "The Green Prince",
    "Greencard Warriors",
    "Gringo Trails",
    "The Grounded",
    "Guardians of the Galaxy",
    "The Guest",
    "Gunday",
    "The Hacker Wars",
    "The Hadza: Last of the First",
    "Haider",
    "HairBrained",
    "Half of a Yellow Sun",
    "Half the Road: The Passion, Pitfalls & Power of Women's Professional Cycling",
    "Han Gong-Ju",
    "Hangar 10",
    "Hank and Asha",
    "Hank: 5 Years From the Brink",
    "Hanna Ranch",
    "Happy Christmas",
    "Happy Ending",
    "Happy New Year",
    "Happy Valley",
    "Harlem Street Singer",
    "Harmontown",
    "Hasee Toh Phasee",
    "Hateship Loveship",
    "Haunt",
    "A Haunted House 2",
    "The Heart Machine",
    "Heaven Is for Real",
    "Hector and the Search for Happiness",
    "Heli",
    "Hellaware",
    "Hellion",
    "Henry & Me",
    "Hercules",
    "The Hero of Color City",
    "Hide Your Smiling Faces",
    "Highway",
    "The Historian",
    "Hit by Lightning",
    "Holiday",
    "Hollidaysburg",
    "The Hobbit: The Battle of the Five Armies",
    "Home, James",
    "The Homesman",
    "Honey",
    "Honeymoon",
    "Honour",
    "The Hornet's Nest",
    "Horns",
    "Horrible Bosses 2",
    "Horses of God",
    "The Houses October Built",
    "How to Train Your Dragon 2",
    "Humpty Sharma Ki Dulhania",
    "Humshakals",
    "The Hundred-Foot Journey",
    "The Hunger Games: Mockingjay - Part I",
    "I Am Ali",
    "I Am Happiness on Earth",
    "I Am I",
    "I, Frankenstein",
    "I Origins",
    "Iceman",
    "Ida",
    "The Identical",
    "If I Stay",
    "If You Build It",
    "If You Don't, I Will",
    "Ilo Ilo",
    "I'm the Same I'm an Other",
    "The Imitation Game",
    "The Immigrant",
    "The Immortalists",
    "In Bloom",
    "In Fear",
    "In No Great Hurry: 13 Lessons in Life With Saul Leiter",
    "In Secret",
    "In the Blood",
    "Indigo Children",
    "Inherent Vice",
    "Inner Demons",
    "Innocence",
    "Interior. Leather Bar.",
    "The Internet's Own Boy",
    "Interstellar",
    "The Interview",
    "Into the Storm",
    "Into the Woods",
    "The Invisible Front",
    "The Island of St. Matthews",
    "Isn't It Delicious",
    "It Felt Like Love",
    "It Was You Charlie",
    "Ivory Tower",
    "Jack Ryan: Shadow Recruit",
    "Jai Ho",
    "Jake Squared",
    "Jamie Marks Is Dead",
    "Jealousy",
    "Jersey Boys",
    "Jersey Shore Massacre",
    "Jessabelle",
    "The Jewish Cardinal",
    "Jews of Egypt",
    "Jimi: All Is by My Side",
    "Jimmy P.: Psychotherapy of a Plains Indian",
    "Jinn",
    "Jobriath A.D.",
    "Jodorowsky's Dune",
    "Joe",
    "John Wick",
    "The Journey of a Female Comic",
    "Journey to the West: Conquering the Demons",
    "The Judge",
    "Just a Sigh",
    "K2: Siren of the Himalayas",
    "Kaanchi",
    "Kabbalah Me",
    "Karle Pyaar Karle",
    "Keep On Keepin' On",
    "Kelly & Cal",
    "Khoobsurat",
    "Kick",
    "Kid Cannabis",
    "Kids for Cash",
    "Kill Dil",
    "The Kill Team",
    "Kill the Messenger",
    "The Kingdom of Dreams and Madness",
    "Kink",
    "Kite",
    "Korengal",
    "Koyelaanchal",
    "Kundo: Age of the Rampant",
    "La Bare",
    "Labor Day",
    "Laggies",
    "Land Ho!",
    "Last Days in Vietnam",
    "Last Hijack",
    "The Last of Robin Hood",
    "The Last of the Unjust",
    "Last Passenger",
    "The Last Patrol",
    "The Last Sentence",
    "Last Weekend",
    "Late Phases",
    "Le Chef",
    "Le Week-end",
    "Leave the World Behind",
    "Left Behind",
    "The Legend of Hercules",
    "Legends of Oz: Dorothy's Return",
    "The Lego Movie",
    "Lekar Hum Deewana Dil",
    "Leprechaun: Origins",
    "Let's Be Cops",
    "Leviathan",
    "Levitated Mass",
    "The Liberator",
    "Life After Beth",
    "The Life and Crimes of Doris Payne",
    "A Life in Dirty Movies",
    "Life Is Strange",
    "Life Itself",
    "Life of an Actress: The Musical",
    "Life of Crime",
    "Life of Riley",
    "Life Partners",
    "Life's a Breeze",
    "Like Father, Like Son",
    "Lilting",
    "Listen Up Philip",
    "Little Feet",
    "A Little Game",
    "Little Hope Was Arson",
    "The Little Tin Man",
    "Little White Lie",
    "Llyn Foulkes One Man Band",
    "Locke",
    "A Long Way Down",
    "The Longest Week",
    "The Lookalike",
    "Lotoman 003",
    "Louder Than Words",
    "Love & Air Sex",
    "Love Hunter",
    "Love Is in the Air",
    "Love Is Strange",
    "Love on the Cloud",
    "The Love Punch",
    "Loves Her Gun",
    "Low Down",
    "Lucky Bastard",
    "Lucky Them",
    "Lucy",
    "Lullaby",
    "The Lunchbox",
    "The M Word",
    "Magic in the Moonlight",
    "Magic Words (Breaking a Spell)",
    "Magical Universe",
    "Magician: The Astonishing Life & Work of Orson Welles",
    "Maidan",
    "Maidentrip",
    "The Maid's Room",
    "Main Tera Hero",
    "Make Your Move",
    "Maleficent",
    "The Man on Her Mind",
    "Manakamana",
    "Manam",
    "Manuscripts Don't Burn",
    "Mardaani",
    "Marius",
    "Mars at Sunrise",
    "Marvin Seth and Stanley",
    "Mary Kom",
    "Más negro que la noche",
    "A Master Builder",
    "Master of the Universe",
    "May in the Summer",
    "The Maze Runner",
    "McCanick",
    "Me and You",
    "Mea Culpa",
    "Meet the Mormons",
    "Memphis",
    "Men, Women & Children",
    "Mercedes Sosa: The Voice of Latin America",
    "Merchants of Doubt",
    "Million Dollar Arm",
    "A Million Ways to Die in the West",
    "Miss Granny",
    "Miss Julie",
    "Miss Lovely",
    "Miss Meadows",
    "The Missing Picture",
    "Mission Blue",
    "Mistaken for Strangers",
    "Moebius",
    "The Moment",
    "Moms' Night Out",
    "Monk With a Camera",
    "The Monuments Men",
    "Mood Indigo",
    "More Than the Rainbow",
    "A Most Violent Year",
    "A Most Wanted Man",
    "Mountains of the Moon",
    "Mr. Peabody & Sherman",
    "Mr. Turner",
    "Mr. X: A Vision of Leos Carax",
    "Muppets Most Wanted",
    "Murder of a Cat",
    "My Man Is a Loser",
    "My Old Lady",
    "Naked Opera",
    "The Naked Room",
    "Nan Goldin: I Remember Your Face",
    "Nas: Time Is Illmatic",
    "National Gallery",
    "Need for Speed",
    "Neighbors",
    "Next Goal Wins",
    "Next Year Jerusalem",
    "Night at the Museum: Secret of the Tomb",
    "A Night in Old Mexico",
    "Night Moves",
    "Nightcrawler",
    "No Cameras Allowed",
    "No God, No Master",
    "No Good Deed",
    "No No: A Dockumentary",
    "No Tears for the Dead",
    "Noah",
    "Non-Stop",
    "Norte, the End of History",
    "Northern Light",
    "Not Cool",
    "The Notebook (Le Grand Cahier)",
    "Nothing Without You",
    "The November Man",
    "NOW: In the Wings on a World Stage",
    "Nurse 3-D",
    "The Nut Job",
    "Nymph()maniac Vol. I",
    "Nymph()maniac Vol. II",
    "Obvious Child",
    "Occupy the Farm",
    "Oculus",
    "Odd Thomas",
    "Omar",
    "On Any Sunday: The Next Chapter",
    "On My Way",
    "On the Other Side of the Tracks",
    "Once Upon a Time Veronica",
    "One Candle, Two Candles...",
    "One Chance",
    "The One I Love",
    "Only Lovers Left Alive ",
    "The Only Real Game",
    "Open Windows",
    "The Other Woman",
    "Ouija",
    "The Outsider",
    "The Overnighters",
    "The Pact 2",
    "Palo Alto",
    "Paranormal Activity: The Marked Ones",
    "Particle Fever",
    "Patema Inverted",
    "Pay 2 Play: Democracy's High Stakes",
    "Pelican Dreams",
    "Penance",
    "Penguins of Madagascar",
    "Perfect Sisters",
    "Persecuted",
    "Peter Brook: The Tightrope",
    "A Picture of You",
    "Ping Pong Summer",
    "Pioneer",
    "The Pirates",
    "Planes: Fire & Rescue",
    "Plastic",
    "The Players",
    "The Pleasures of Being out of Step: Notes on the Life of Nat Hentoff",
    "Plot for Peace",
    "Point and Shoot",
    "Policeman",
    "Pompeii",
    "The Possession of Michael King",
    "Postman Pat: The Movie",
    "Poverty, Inc.",
    "Precious Caterpillar",
    "Premature",
    "The Pretty One",
    "Pride",
    "The Prince",
    "Print the Legend",
    "Private Peaceful",
    "Private Violence",
    "A Promise",
    "The Protector 2",
    "Proxy",
    "Pulp: A Film About Life, Death & Supermarkets",
    "Pump",
    "Purgatorio: A Journey Into the Heart of the Border",
    "The Purge: Anarchy",
    "The Pyramid",
    "Queen",
    "The Quiet Ones",
    "The Quitter",
    "Rabindranath Tagore: The Poet of Eternity",
    "Rage",
    "Ragini MMS 2",
    "The Raid 2",
    "The Railway Man",
    "Raja Natwarlal",
    "Raze",
    "Reach Me",
    "Reasonable Doubt",
    "Recep Ivedik 4",
    "Reclaim",
    "Red Army",
    "Red Dot on the Ocean",
    "Red Knot",
    "Refuge",
    "Relationship Status: It's Complicated",
    "Remote Area Medical",
    "Repentance",
    "A Requiem for Syrian Refugees",
    "The Retrieval",
    "Return to Nuke 'Em High: Volume 1",
    "The Returned",
    "Revenge of the Green Dragons",
    "Revenge of the Mekons",
    "Rich Hill",
    "Ride Along",
    "Rigor Mortis",
    "Rio 2",
    "The Rise and Rise of Bitcoin",
    "Road to Paloma",
    "Roar: Tigers of the Sundarbans",
    "Rob the Mob",
    "RoboCop",
    "The Rocket",
    "Rocks in My Pockets",
    "Rosewater",
    "The Rover",
    "Rowdy",
    "Rudderless",
    "The Rule",
    "Rumstick Road",
    "Run & Jump",
    "Sabotage",
    "The Sacrament",
    "Sagrada: The Mystery of Creation",
    "The Salt of the Earth",
    "Salvo",
    "Saving Christmas",
    "School Dance",
    "Seasons of Love",
    "Second Opinion: Laetrile at Sloan-Kettering",
    "See You Next Tuesday",
    "Selma",
    "Sex Ed",
    "Sex Tape",
    "Shaadi Ke Side Effects",
    "Shadows From My Past",
    "The Shaukeens",
    "She's Beautiful When She's Angry",
    "Shirin in Love",
    "A Short History of Decay",
    "Siddharth",
    "The Signal",
    "Sinbad: The Fifth Voyage",
    "Singham Returns",
    "Six Dance Lessons in Six Weeks",
    "Skating to New York",
    "The Skeleton Twins ",
    "The Sleepwalker",
    "A Small Section of the World",
    "Small Small Thing",
    "Small Time",
    "Smiling Through the Apocalypse: Esquire in the 60s",
    "Snowpiercer",
    "Soft in the Head",
    "Sol LeWitt",
    "Someone Marry Barry",
    "Somewhere Slow ",
    "Son of God",
    "The Song",
    "Song of the Sea",
    "Space Station 76",
    "Speak the Music: Robert Mann and the Mysteries of Chamber Music",
    "Special ID",
    "A Spell to Ward Off the Darkness",
    "St. Vincent",
    "Stage Fright",
    "Stalingrad",
    "Stand Clear of the Closing Doors",
    "The Standbys",
    "Starred Up",
    "Starry Eyes",
    "Stay",
    "Step Up All In",
    "Still Alice",
    "Still I Strive",
    "Stonehearst Asylum",
    "Stones in the Sun",
    "Stop the Pounding Heart",
    "Story of My Death",
    "The Strange Color of Your Body's Tears",
    "The Strange Little Cat",
    "Stranger by the Lake",
    "Stray Dogs",
    "Summer in February",
    "Summer of Blood",
    "SuperMensch: The Legend of Shep Gordon",
    "The Supreme Price",
    "The Suspect",
    "Swearnet",
    "Swim Little Fish Swim",
    "Tabloid Truth",
    "Take Care",
    "Take Me to the River",
    "The Tale of the Princess Kaguya",
    "Tales of the Grim Sleeper",
    "Tammy",
    "Tasting Menu",
    "Teenage",
    "Teenage Mutant Ninja Turtles",
    "Temporary Family",
    "Test",
    "That Awkward Moment",
    "That Demon Within",
    "The Theory of Everything",
    "Theo's House",
    "They Came Together",
    "Think Like a Man Too",
    "Third Person",
    "This Ain't No Mouse Music",
    "This Is Not a Ball",
    "This Is Where I Leave You",
    "Thomas Keating: A Rising Tide of Silence",
    "Thou Wast Mild and Lovely",
    "Through a Lens Darkly: Black Photographers and the Emergence of a People",
    "Thunder and the House of Magic",
    "Tiger Lily Road",
    "Tip Top",
    "To Be Takei",
    "Top Five",
    "Total Chaos",
    "Touch the Wall",
    "Towheads",
    "The Town That Dreaded Sundown",
    "Tracks",
    "Trailer Park Boys: Don't Legalize It",
    "Transcendence",
    "Transformers: Age of Extinction",
    "The Trip to Italy",
    "True Son",
    "Trust Me",
    "Truth",
    "The Truth About Emanuel",
    "Tusk",
    "Two Days, One Night",
    "The Two Faces of January",
    "Two Lives",
    "Two Night Stand",
    "Tyler Perry's The Single Moms Club",
    "Unbroken",
    "Unclaimed",
    "Under the Electric Sky",
    "Under the Skin",
    "Underwater Dreams",
    "The Unknown Known",
    "Unthinkable: An Airline Captain's Story",
    "Uzumasa Limelight",
    "Vampire Academy",
    "Vanishing Pearls: The Oystermen of Pointe à la Hache",
    "The Vanquishing of the Witch Baba Yaga",
    "Venus in Fur",
    "Veronica Mars",
    "Very Good Girls",
    "Vic + Flo Saw a Bear",
    "Video Games: The Movie",
    "Viktor",
    "The Villain",
    "Violette",
    "Virunga",
    "Visions of Mary Frank",
    "Visitors",
    "Viva la libertà",
    "The Wait",
    "Waiting for August",
    "A Walk Among the Tombstones",
    "Walk of Shame",
    "Walking the Camino: Six Ways to Santiago",
    "Walking With the Enemy",
    "War of the Worlds: Goliath",
    "War Story",
    "Warsaw Uprising",
    "Watchers of the Sky",
    "Watermark",
    "The Way He Looks",
    "We Are Mari Pepa",
    "We Are the Best!",
    "We Are the Giant",
    "We Could Be King",
    "Web Junkie",
    "Welcome to the Jungle",
    "Wetlands",
    "What If",
    "What Now? Remind Me",
    "When I Saw You",
    "When the Game Stands Tall",
    "Where We Started",
    "Whiplash",
    "White Bird in a Blizzard",
    "WHITEY: United States of America vs. James J. Bulger",
    "Who Is Dayani Cristal?",
    "Wild",
    "The Will",
    "A Will for the Woods",
    "Will You Still Love Me Tomorrow?",
    "Willow Creek",
    "Winter in the Blood",
    "Winter Sleep",
    "Winter's Tale",
    "Wish I Was Here",
    "Witching & Bitching",
    "Wolf Creek 2",
    "Wolves",
    "The Word",
    "Words and Pictures",
    "A World Not Ours",
    "Xingu",
    "X-Men: Days of Future Past",
    "Young & Beautiful",
    "Young Ones",
    "You're Not You",
    "Yves Saint Laurent",
    "Zero Motivation",
    "The Zero Theorem"
  ]
end
end
