class Year < ActiveRecord::Base
  has_many :movies
  has_many :ballots
  has_many :credits
  has_many :scenes

  validates :name, presence: true
  validates :open_voting, presence: true
  validates :close_voting, presence: true
  validates :display_results, presence: true


  def self.results_display
    where("display_results < ?", Time.zone.now).last
  end

  def self.active_voting
    where("open_voting < ? AND close_voting > ?", Time.zone.now, Time.zone.now).last
  end

  def self.all_but_results_display
    year_array = []
    where("display_results < ?", Time.zone.now).all.each do |y|
      if y != Year.results_display
        year_array << y
      end
    end
    year_array
  end

  def self.get_display_year(year)
    if year
      where("name = ? and display_results < ?", year, Time.zone.now ).last
    else
      Year.results_display
    end
  end

  def eligible_movies_by_average_rating
    movies.where("nbr_ratings > 4").order(average_rating: :desc, title_index: :asc)
  end

  def ranked_movies_hash
    ranked_movies_hash = {}
    hold_for_ties_array = []
    tie_start_index = 0
    tie_average_rating = 0.00
    movies_array = eligible_movies_by_average_rating
    movies_array.each_with_index do |m,index|
      if m.average_rating == tie_average_rating || index == 0 # this movie is tied with the previous movie on the list
        hold_for_ties_array << m
        if index + 1 == movies_array.length # end of the list--move last movie (plus any previous ties) to hash
          rank_array = (tie_start_index..index + 1).to_a
          rank_sum = rank_array.inject(:+)
          average_rank_of_tied_movies = rank_sum.to_f / hold_for_ties_array.length.to_f
          hold_for_ties_array.each do |m|
            ranked_movies_hash[m.id] = average_rank_of_tied_movies
          end
        end
      else
        if hold_for_ties_array.length > 1 # there are two or more tied movies in the hold array
          rank_array = (tie_start_index..index).to_a
          rank_sum = rank_array.inject(:+)
          average_rank_of_tied_movies = rank_sum.to_f / hold_for_ties_array.length.to_f
          hold_for_ties_array.each do |m|
            ranked_movies_hash[m.id] = average_rank_of_tied_movies
          end
        elsif hold_for_ties_array.length == 1 # there is a single movie in the hold array.  There were no ties.
          ranked_movies_hash[hold_for_ties_array[0].id] = index
        end
        if index + 1 == movies_array.length # end of the list--move last movie to the hash
          ranked_movies_hash[m.id] = index + 1
        else
          hold_for_ties_array = [m]
          tie_start_index = index + 1
          tie_average_rating = m.average_rating
        end
      end
    end
    ranked_movies_hash
  end

  def save_movie_vote_results
    picture_category = Category.where(name: "picture").first
    director_category = Category.where(name: "director").first
    screenplay_category = Category.where(name: "screenplay").first
    movies.each do |m|
      m.picture_points = m.compute_points(picture_category)
      m.picture_votes = m.compute_votes(picture_category)
      m.director_points = m.compute_points(director_category)
      m.director_votes = m.compute_votes(director_category)
      m.screenplay_points = m.compute_points(screenplay_category)
      m.screenplay_votes = m.compute_votes(screenplay_category)
      m.save
    end
  end

  def save_credit_vote_results
    actor_job = Job.where(name: "actor")
    credits.where(job: actor_job).each do |c|
      results_category = c.compute_results_category
      c.category = results_category
      c.points = c.compute_points_results(results_category)
      c.nbr_votes = c.compute_votes_results(results_category)
      c.save
    end
  end

  def save_scene_vote_results
    scenes.each do |s|
      s.nbr_votes = s.compute_votes
      s.points = s.compute_points
      s.save
    end
  end

  def save_ratings_results
    movies.each do |m|
      m.nbr_ratings = m.compute_total_nbr_ratings
      m.average_rating = m.compute_average_rating
      m.four_ratings = m.compute_nbr_ratings(4.0)
      m.three_pt_five_ratings = m.compute_nbr_ratings(3.5)
      m.three_ratings = m.compute_nbr_ratings(3.0)
      m.two_pt_five_ratings = m.compute_nbr_ratings(2.5)
      m.two_ratings = m.compute_nbr_ratings(2.0)
      m.one_pt_five_ratings = m.compute_nbr_ratings(1.5)
      m.one_ratings = m.compute_nbr_ratings(1.0)
      m.zero_ratings = m.compute_nbr_ratings(0.0)
      if m.compute_total_nbr_ratings > 1
        m.standard_dev = m.compute_standard_dev
      end
      m.save
    end
  end

  def save_user_profile_results
    ballots.each do |b|
      b.nbr_ratings = b.compute_total_nbr_ratings
      b.average_rating = b.compute_average_rating
      b.four_ratings = b.compute_nbr_ratings(4.0)
      b.three_pt_five_ratings = b.compute_nbr_ratings(3.5)
      b.three_ratings = b.compute_nbr_ratings(3.0)
      b.two_pt_five_ratings = b.compute_nbr_ratings(2.5)
      b.two_ratings = b.compute_nbr_ratings(2.0)
      b.one_pt_five_ratings = b.compute_nbr_ratings(1.5)
      b.one_ratings = b.compute_nbr_ratings(1.0)
      b.zero_ratings = b.compute_nbr_ratings(0.0)
      b.selectivity_index = b.compute_selectivity_index
      b.save
    end
  end

  def save_complete_results
    save_movie_vote_results
    save_credit_vote_results
    save_scene_vote_results
    save_ratings_results
    save_user_profile_results
  end

  def self.upload_2016_movies
    Movie.create(title: "À la vie", year_id: 22)
    Movie.create(title: "The Abandoned", year_id: 22)
    Movie.create(title: "The Abolitionists", year_id: 22)
    Movie.create(title: "Abortion: Stories Women Tell", year_id: 22)
    Movie.create(title: "About Scout", year_id: 22)
    Movie.create(title: "Above and Below", year_id: 22)
    Movie.create(title: "Absolutely Fabulous: The Movie", year_id: 22)
    Movie.create(title: "The Academy of Muses", year_id: 22)
    Movie.create(title: "The Accountant", year_id: 22)
    Movie.create(title: "Ace the Case: Manhattan Mystery", year_id: 22)
    Movie.create(title: "The Achy Breaky Hearts", year_id: 22)
    Movie.create(title: "Actor in Law", year_id: 22)
    Movie.create(title: "The Adderall Diaries", year_id: 22)
    Movie.create(title: "Ae Dil Hai Mushkil", year_id: 22)
    Movie.create(title: "Aferim!", year_id: 22)
    Movie.create(title: "Afternoon", year_id: 22)
    Movie.create(title: "The Age of Shadows", year_id: 22)
    Movie.create(title: "Airlift", year_id: 22)
    Movie.create(title: "Akira", year_id: 22)
    Movie.create(title: "Ali & Nino", year_id: 22)
    Movie.create(title: "Alice Through the Looking Glass", year_id: 22)
    Movie.create(title: "All Governments Lie: Truth, Deception, and the Spirit of I.F. Stone", year_id: 22)
    Movie.create(title: "All in Time", year_id: 22)
    Movie.create(title: "All Mistakes Buried", year_id: 22)
    Movie.create(title: "All Roads Lead to Rome", year_id: 22)
    Movie.create(title: "All We Had", year_id: 22)
    Movie.create(title: "All You Need Is Pag-ibig", year_id: 22)
    Movie.create(title: "Allied", year_id: 22)
    Movie.create(title: "Almost Christmas", year_id: 22)
    Movie.create(title: "Almost Holy", year_id: 22)
    Movie.create(title: "Already Tomorrow in Hong Kong", year_id: 22)
    Movie.create(title: "Always Be My Maybe", year_id: 22)
    Movie.create(title: "Always Shine", year_id: 22)
    Movie.create(title: "Amanda Knox", year_id: 22)
    Movie.create(title: "Amateur Night", year_id: 22)
    Movie.create(title: "American Honey", year_id: 22)
    Movie.create(title: "American Pastoral", year_id: 22)
    Movie.create(title: "The American Side", year_id: 22)
    Movie.create(title: "Among the Believers", year_id: 22)
    Movie.create(title: "Andron", year_id: 22)
    Movie.create(title: "Anesthesia", year_id: 22)
    Movie.create(title: "Anger of the Dead", year_id: 22)
    Movie.create(title: "The Angry Birds Movie", year_id: 22)
    Movie.create(title: "Anne Frank: Then and Now", year_id: 22)
    Movie.create(title: "Anthropoid", year_id: 22)
    Movie.create(title: "The Anthropologist", year_id: 22)
    Movie.create(title: "Antibirth", year_id: 22)
    Movie.create(title: "Ants on a Shrimp", year_id: 22)
    Movie.create(title: "The Apostate", year_id: 22)
    Movie.create(title: "Apparition Hill", year_id: 22)
    Movie.create(title: "Approaching the Unknown", year_id: 22)
    Movie.create(title: "April and the Extraordinary World", year_id: 22)
    Movie.create(title: "Aquarius", year_id: 22)
    Movie.create(title: "Argentina", year_id: 22)
    Movie.create(title: "Army of One", year_id: 22)
    Movie.create(title: "Arrival", year_id: 22)
    Movie.create(title: "Art Bastard", year_id: 22)
    Movie.create(title: "An Art That Nature Makes", year_id: 22)
    Movie.create(title: "As I AM: The Life and Times of DJ AM", year_id: 22)
    Movie.create(title: "As I Open My Eyes", year_id: 22)
    Movie.create(title: "Asian Connection", year_id: 22)
    Movie.create(title: "Asperger's Are Us", year_id: 22)
    Movie.create(title: "Assassin's Creed", year_id: 22)
    Movie.create(title: "Asura: The City of Madness", year_id: 22)
    Movie.create(title: "At the Fork", year_id: 22)
    Movie.create(title: "The Ataxian", year_id: 22)
    Movie.create(title: "Audrie & Daisy", year_id: 22)
    Movie.create(title: "Author: The JT LeRoy Story", year_id: 22)
    Movie.create(title: "The Autopsy of Jane Doe", year_id: 22)
    Movie.create(title: "Autumn Lights", year_id: 22)
    Movie.create(title: "Ava's Possessions", year_id: 22)
    Movie.create(title: "Azhar", year_id: 22)
    Movie.create(title: "Baaghi", year_id: 22)
    Movie.create(title: "Baar Baar Dekho", year_id: 22)
    Movie.create(title: "Back in the Day", year_id: 22)
    Movie.create(title: "Backgammon", year_id: 22)
    Movie.create(title: "Backtrack", year_id: 22)
    Movie.create(title: "Bad Hurt", year_id: 22)
    Movie.create(title: "The Bad Kids", year_id: 22)
    Movie.create(title: "Bad Moms", year_id: 22)
    Movie.create(title: "Bad Santa 2", year_id: 22)
    Movie.create(title: "Baden Baden", year_id: 22)
    Movie.create(title: "Band of Robbers", year_id: 22)
    Movie.create(title: "Bang Gang (A Modern Love Story)", year_id: 22)
    Movie.create(title: "Banjo", year_id: 22)
    Movie.create(title: "Barbershop: The Next Cut", year_id: 22)
    Movie.create(title: "Barcelona: A Love Untold", year_id: 22)
    Movie.create(title: "Barry", year_id: 22)
    Movie.create(title: "Baskin", year_id: 22)
    Movie.create(title: "Batman v Superman: Dawn of Justice", year_id: 22)
    Movie.create(title: "Bazodee", year_id: 22)
    Movie.create(title: "Be Here Now", year_id: 22)
    Movie.create(title: "Be Somebody", year_id: 22)
    Movie.create(title: "The Beatles: Eight Days a Week - The Touring Years", year_id: 22)
    Movie.create(title: "A Beautiful Planet", year_id: 22)
    Movie.create(title: "Beautiful Something", year_id: 22)
    Movie.create(title: "Beauty Bites Beast", year_id: 22)
    Movie.create(title: "Becoming Mike Nichols", year_id: 22)
    Movie.create(title: "Befikre", year_id: 22)
    Movie.create(title: "Before the Flood", year_id: 22)
    Movie.create(title: 'Behind "The Cove"', year_id: 22)
    Movie.create(title: "Behind Bayonets and Barbed Wire", year_id: 22)
    Movie.create(title: "Being Charlie", year_id: 22)
    Movie.create(title: "Being 17", year_id: 22)
    Movie.create(title: "Believe", year_id: 22)
    Movie.create(title: "The Benefactor", year_id: 22)
    Movie.create(title: "Ben-Hur", year_id: 22)
    Movie.create(title: "Best and Most Beautiful Things", year_id: 22)
    Movie.create(title: "The Best Democracy Money Can Buy: A Tale of Billionaires & Ballot Bandits", year_id: 22)
    Movie.create(title: "Best Worst Thing That Ever Could Have Happened", year_id: 22)
    Movie.create(title: "Beyond the Gates", year_id: 22)
    Movie.create(title: "The BFG", year_id: 22)
    Movie.create(title: "A Bigger Splash", year_id: 22)
    Movie.create(title: "A Billion Lives", year_id: 22)
    Movie.create(title: "Billy Lynn's Long Halftime Walk", year_id: 22)
    Movie.create(title: "The Birth of a Nation", year_id: 22)
    Movie.create(title: "The Birth of Saké", year_id: 22)
    Movie.create(title: "Black Rose", year_id: 22)
    Movie.create(title: "Black Women in Medicine", year_id: 22)
    Movie.create(title: "Blair Witch", year_id: 22)
    Movie.create(title: "Bleak Street", year_id: 22)
    Movie.create(title: "Bleed for This", year_id: 22)
    Movie.create(title: "Blood Father", year_id: 22)
    Movie.create(title: "Blood on the Mountain", year_id: 22)
    Movie.create(title: "Blue Jay", year_id: 22)
    Movie.create(title: "Bobby Sands: 66 Days", year_id: 22)
    Movie.create(title: "Boom Bust Boom", year_id: 22)
    Movie.create(title: "Born to Be Blue", year_id: 22)
    Movie.create(title: "The Boss", year_id: 22)
    Movie.create(title: "The Bounce Back", year_id: 22)
    Movie.create(title: "Bourek", year_id: 22)
    Movie.create(title: "The Boy", year_id: 22)
    Movie.create(title: "The Boy and the Beast", year_id: 22)
    Movie.create(title: "Boy 23: The Forgotten Boys of Brazil", year_id: 22)
    Movie.create(title: "Brahmotsavam", year_id: 22)
    Movie.create(title: "The Brainwashing of My Dad", year_id: 22)
    Movie.create(title: "The Brand New Testament", year_id: 22)
    Movie.create(title: "Breaking a Monster: A Film About Unlocking The Truth", year_id: 22)
    Movie.create(title: "Bridgend", year_id: 22)
    Movie.create(title: "Bridget Jones's Baby", year_id: 22)
    Movie.create(title: "The Bronze", year_id: 22)
    Movie.create(title: "The Brooklyn Banker", year_id: 22)
    Movie.create(title: "Brother Nature", year_id: 22)
    Movie.create(title: "The Brothers Grimsby", year_id: 22)
    Movie.create(title: "Burn Country", year_id: 22)
    Movie.create(title: "Busco novio para mi mujer", year_id: 22)
    Movie.create(title: "By Sidney Lumet", year_id: 22)
    Movie.create(title: "C Street", year_id: 22)
    Movie.create(title: "The C Word", year_id: 22)
    Movie.create(title: "Cabin Fever", year_id: 22)
    Movie.create(title: "Café Society", year_id: 22)
    Movie.create(title: "Caged No More", year_id: 22)
    Movie.create(title: "Call Her Applebroog", year_id: 22)
    Movie.create(title: "Camera Store", year_id: 22)
    Movie.create(title: "Cameraperson", year_id: 22)
    Movie.create(title: "Can We Take a Joke?", year_id: 22)
    Movie.create(title: "Captain America: Civil War", year_id: 22)
    Movie.create(title: "Captain Fantastic", year_id: 22)
    Movie.create(title: "Cardboard Boxer", year_id: 22)
    Movie.create(title: "Careful What You Wish For", year_id: 22)
    Movie.create(title: "The Caretaker", year_id: 22)
    Movie.create(title: "Carnage Park", year_id: 22)
    Movie.create(title: "Cash Only", year_id: 22)
    Movie.create(title: "Catching the Sun", year_id: 22)
    Movie.create(title: "Cell", year_id: 22)
    Movie.create(title: "Cemetery of Splendour", year_id: 22)
    Movie.create(title: "Central Intelligence", year_id: 22)
    Movie.create(title: "Certain Women", year_id: 22)
    Movie.create(title: "Chasing Yesterday", year_id: 22)
    Movie.create(title: "Chevalier", year_id: 22)
    Movie.create(title: "Chicken People", year_id: 22)
    Movie.create(title: "The Childhood of a Leader", year_id: 22)
    Movie.create(title: "The Choice", year_id: 22)
    Movie.create(title: "Chongqing Hot Pot", year_id: 22)
    Movie.create(title: "Christine", year_id: 22)
    Movie.create(title: "Chronic", year_id: 22)
    Movie.create(title: "Citizen Soldier", year_id: 22)
    Movie.create(title: "City of Gold", year_id: 22)
    Movie.create(title: "The Clan", year_id: 22)
    Movie.create(title: "Class Divide", year_id: 22)
    Movie.create(title: "Closet Monster", year_id: 22)
    Movie.create(title: "Clown", year_id: 22)
    Movie.create(title: "The Club", year_id: 22)
    Movie.create(title: "Cock and Bull", year_id: 22)
    Movie.create(title: "Code of Honor", year_id: 22)
    Movie.create(title: "Cold War II", year_id: 22)
    Movie.create(title: "Collateral Beauty", year_id: 22)
    Movie.create(title: "Colliding Dreams", year_id: 22)
    Movie.create(title: "Colonia", year_id: 22)
    Movie.create(title: "Come and Find Me", year_id: 22)
    Movie.create(title: "Come What May", year_id: 22)
    Movie.create(title: "The Comedian", year_id: 22)
    Movie.create(title: "Coming Through the Rye", year_id: 22)
    Movie.create(title: "Command and Control", year_id: 22)
    Movie.create(title: "Compadres", year_id: 22)
    Movie.create(title: "Complete Unknown", year_id: 22)
    Movie.create(title: "The Confirmation", year_id: 22)
    Movie.create(title: "The Congressman", year_id: 22)
    Movie.create(title: "The Conjuring 2", year_id: 22)
    Movie.create(title: "Contract to Kill", year_id: 22)
    Movie.create(title: "Cosmos", year_id: 22)
    Movie.create(title: "Crazy About Tiffany's", year_id: 22)
    Movie.create(title: "Creative Control", year_id: 22)
    Movie.create(title: "Creepy", year_id: 22)
    Movie.create(title: "Criminal", year_id: 22)
    Movie.create(title: "Crosscurrent", year_id: 22)
    Movie.create(title: "Dancer", year_id: 22)
    Movie.create(title: "Dangal", year_id: 22)
    Movie.create(title: "Danny Says", year_id: 22)
    Movie.create(title: "Dark Horse [the race-horse documentary]", year_id: 22)
    Movie.create(title: "The Dark Horse [the chess drama]", year_id: 22)
    Movie.create(title: "The Darkness", year_id: 22)
    Movie.create(title: "Darling", year_id: 22)
    Movie.create(title: "The David Dance", year_id: 22)
    Movie.create(title: "Daylight's End", year_id: 22)
    Movie.create(title: "De Palma", year_id: 22)
    Movie.create(title: "The Dead Room", year_id: 22)
    Movie.create(title: "Deadpool", year_id: 22)
    Movie.create(title: "Dear Zindagi", year_id: 22)
    Movie.create(title: "The Debt", year_id: 22)
    Movie.create(title: "Deepwater Horizon", year_id: 22)
    Movie.create(title: "Defying the Nazis: The Sharps' War", year_id: 22)
    Movie.create(title: "Demolition", year_id: 22)
    Movie.create(title: "Demon", year_id: 22)
    Movie.create(title: "Denial", year_id: 22)
    Movie.create(title: "Department Q: A Conspiracy of Faith", year_id: 22)
    Movie.create(title: "Department Q: The Absent One", year_id: 22)
    Movie.create(title: "Desierto", year_id: 22)
    Movie.create(title: "Detective Chinatown", year_id: 22)
    Movie.create(title: "The Devil's Dolls", year_id: 22)
    Movie.create(title: "Dhanak (Rainbow)", year_id: 22)
    Movie.create(title: "Dheepan", year_id: 22)
    Movie.create(title: "Dhruva", year_id: 22)
    Movie.create(title: "Diamond Tongues", year_id: 22)
    Movie.create(title: "Diary of a Chambermaid", year_id: 22)
    Movie.create(title: "Dick & Jack", year_id: 22)
    Movie.create(title: "Dirty Grandpa", year_id: 22)
    Movie.create(title: "Dirty 30", year_id: 22)
    Movie.create(title: "The Disappointments Room", year_id: 22)
    Movie.create(title: "Dishoom", year_id: 22)
    Movie.create(title: "Disorder", year_id: 22)
    Movie.create(title: "Disturbing the Peace", year_id: 22)
    Movie.create(title: "The Divergent Series: Allegiant", year_id: 22)
    Movie.create(title: "Do Not Resist", year_id: 22)
    Movie.create(title: "Dr. Feelgood: Dealer or Healer?", year_id: 22)
    Movie.create(title: "Doctor Strange", year_id: 22)
    Movie.create(title: "Dog Eat Dog", year_id: 22)
    Movie.create(title: "The Dog Wedding", year_id: 22)
    Movie.create(title: "Don't Blink: Robert Frank", year_id: 22)
    Movie.create(title: "Don't Breathe", year_id: 22)
    Movie.create(title: "Don't Call Me Son", year_id: 22)
    Movie.create(title: "Don't Look Down", year_id: 22)
    Movie.create(title: "Don't Think Twice", year_id: 22)
    Movie.create(title: "Don't Worry Baby", year_id: 22)
    Movie.create(title: "Dough", year_id: 22)
    Movie.create(title: "Dreamland", year_id: 22)
    Movie.create(title: "The Dressmaker", year_id: 22)
    Movie.create(title: "Dude Bro Party Massacre III", year_id: 22)
    Movie.create(title: "The Duel", year_id: 22)
    Movie.create(title: "The Duelist", year_id: 22)
    Movie.create(title: "Dukot", year_id: 22)
    Movie.create(title: "Dying to Know: Ram Dass & Timothy Leary", year_id: 22)
    Movie.create(title: "The Eagle Huntress", year_id: 22)
    Movie.create(title: "Eat That Question - Frank Zappa in His Own Words", year_id: 22)
    Movie.create(title: "Eating You Alive", year_id: 22)
    Movie.create(title: "Echo Park", year_id: 22)
    Movie.create(title: "Eddie the Eagle", year_id: 22)
    Movie.create(title: "The Edge of Seventeen", year_id: 22)
    Movie.create(title: "Edge of Winter", year_id: 22)
    Movie.create(title: "Eisenstein in Guanajuato", year_id: 22)
    Movie.create(title: "11 Minutes", year_id: 22)
    Movie.create(title: "Elle", year_id: 22)
    Movie.create(title: "Elstree 1976", year_id: 22)
    Movie.create(title: "Elvis & Nixon", year_id: 22)
    Movie.create(title: "Embrace of the Serpent", year_id: 22)
    Movie.create(title: "Emelie", year_id: 22)
    Movie.create(title: "Equal Means Equal", year_id: 22)
    Movie.create(title: "Equals", year_id: 22)
    Movie.create(title: "Equity", year_id: 22)
    Movie.create(title: "Eva Hesse", year_id: 22)
    Movie.create(title: "Evan's Crime", year_id: 22)
    Movie.create(title: "Everybody Wants Some!!", year_id: 22)
    Movie.create(title: "Everybody's Fine", year_id: 22)
    Movie.create(title: "Everything About Her", year_id: 22)
    Movie.create(title: "Everything Is Copy -- Nora Ephron: Scripted & Unscripted", year_id: 22)
    Movie.create(title: "Evolution", year_id: 22)
    Movie.create(title: "Exposed", year_id: 22)
    Movie.create(title: "An Eye for an Eye", year_id: 22)
    Movie.create(title: "An Eye for Beauty", year_id: 22)
    Movie.create(title: "Eye in the Sky", year_id: 22)
    Movie.create(title: "The Eyes of My Mother", year_id: 22)
    Movie.create(title: "A Family Affair", year_id: 22)
    Movie.create(title: "The Family Fang", year_id: 22)
    Movie.create(title: "Fan", year_id: 22)
    Movie.create(title: "Fantastic Beasts and Where to Find Them", year_id: 22)
    Movie.create(title: "Fassbinder: To Love Without Demands", year_id: 22)
    Movie.create(title: "Fastball", year_id: 22)
    Movie.create(title: "Fathers and Daughters", year_id: 22)
    Movie.create(title: "Fatima", year_id: 22)
    Movie.create(title: "Fences", year_id: 22)
    Movie.create(title: "The 5th Wave", year_id: 22)
    Movie.create(title: "Fifty Shades of Black", year_id: 22)
    Movie.create(title: "Fight Valley", year_id: 22)
    Movie.create(title: "The Final Project", year_id: 22)
    Movie.create(title: "Finding Altamira", year_id: 22)
    Movie.create(title: "Finding Babel", year_id: 22)
    Movie.create(title: "Finding Dory", year_id: 22)
    Movie.create(title: "Finding Mr. Right 2", year_id: 22)
    Movie.create(title: "The Finest Hours", year_id: 22)
    Movie.create(title: "Fire at Sea", year_id: 22)
    Movie.create(title: "First Lady of the Revolution", year_id: 22)
    Movie.create(title: "The First Monday in May", year_id: 22)
    Movie.create(title: "Fitoor", year_id: 22)
    Movie.create(title: "The Fits", year_id: 22)
    Movie.create(title: "Five Nights in Maine", year_id: 22)
    Movie.create(title: "The Flight Fantastic", year_id: 22)
    Movie.create(title: "Flock of Dudes", year_id: 22)
    Movie.create(title: "Florence Foster Jenkins", year_id: 22)
    Movie.create(title: "Floyd Norman: An Animated Life", year_id: 22)
    Movie.create(title: "A Flying Jatt", year_id: 22)
    Movie.create(title: "Foolish Plans", year_id: 22)
    Movie.create(title: "For a Few Bullets", year_id: 22)
    Movie.create(title: "For the Love of Spock", year_id: 22)
    Movie.create(title: "For the Plasma", year_id: 22)
    Movie.create(title: "Force 2", year_id: 22)
    Movie.create(title: "The Forest", year_id: 22)
    Movie.create(title: "Forsaken", year_id: 22)
    Movie.create(title: "Fort Buchanan", year_id: 22)
    Movie.create(title: "400 Days", year_id: 22)
    Movie.create(title: "4th Man Out", year_id: 22)
    Movie.create(title: "Francofonia", year_id: 22)
    Movie.create(title: "Frank & Lola", year_id: 22)
    Movie.create(title: "Freaky Ali", year_id: 22)
    Movie.create(title: "Free State of Jones", year_id: 22)
    Movie.create(title: "Free to Run", year_id: 22)
    Movie.create(title: "The Free World", year_id: 22)
    Movie.create(title: "From Afar", year_id: 22)
    Movie.create(title: "From This Day Forward", year_id: 22)
    Movie.create(title: "From Vegas to Macau III", year_id: 22)
    Movie.create(title: "Front Cover", year_id: 22)
    Movie.create(title: "Garnet's Gold", year_id: 22)
    Movie.create(title: "The Gemini", year_id: 22)
    Movie.create(title: "Generation Startup", year_id: 22)
    Movie.create(title: "Genius", year_id: 22)
    Movie.create(title: "Germans & Jews", year_id: 22)
    Movie.create(title: "Get a Job", year_id: 22)
    Movie.create(title: "Get Happy!", year_id: 22)
    Movie.create(title: "Ghayal Once Again", year_id: 22)
    Movie.create(title: "Ghost Team", year_id: 22)
    Movie.create(title: "Ghostbusters", year_id: 22)
    Movie.create(title: "Ghostland: The View of the Ju/'Hoansi", year_id: 22)
    Movie.create(title: "Gimme Danger ", year_id: 22)
    Movie.create(title: "Girl Asleep", year_id: 22)
    Movie.create(title: "The Girl in the Photographs", year_id: 22)
    Movie.create(title: "The Girl on the Train", year_id: 22)
    Movie.create(title: "Glassland", year_id: 22)
    Movie.create(title: "Gleason", year_id: 22)
    Movie.create(title: "Goat", year_id: 22)
    Movie.create(title: "The God Cells", year_id: 22)
    Movie.create(title: "God's Not Dead 2", year_id: 22)
    Movie.create(title: "Gods of Egypt", year_id: 22)
    Movie.create(title: "Good Kids", year_id: 22)
    Movie.create(title: "The Good Neighbor", year_id: 22)
    Movie.create(title: "Goodnight Brooklyn: The Story of Death By Audio", year_id: 22)
    Movie.create(title: "Gordon Getty: There Will Be Music", year_id: 22)
    Movie.create(title: "The Greasy Strangler", year_id: 22)
    Movie.create(title: "The Great Gilly Hopkins", year_id: 22)
    Movie.create(title: "Greater", year_id: 22)
    Movie.create(title: "Green Room", year_id: 22)
    Movie.create(title: "Gurukulam", year_id: 22)
    Movie.create(title: "H.", year_id: 22)
    Movie.create(title: "Hacksaw Ridge", year_id: 22)
    Movie.create(title: "Hail, Caesar!", year_id: 22)
    Movie.create(title: "The Handmaiden", year_id: 22)
    Movie.create(title: "Hands of Stone", year_id: 22)
    Movie.create(title: "Happy Bhag Jayegi", year_id: 22)
    Movie.create(title: "Happy Hour", year_id: 22)
    Movie.create(title: "Hardcore Henry", year_id: 22)
    Movie.create(title: "Harry and Snowman", year_id: 22)
    Movie.create(title: "Harry Benson: Shoot First", year_id: 22)
    Movie.create(title: "Hate Rising", year_id: 22)
    Movie.create(title: "A Haunting in Cawdor", year_id: 22)
    Movie.create(title: "Havana Motor Club", year_id: 22)
    Movie.create(title: "Hell or High Water", year_id: 22)
    Movie.create(title: "Hello, My Name Is Doris", year_id: 22)
    Movie.create(title: "Henry Gamble's Birthday Party", year_id: 22)
    Movie.create(title: "Here Come the Videofreex", year_id: 22)
    Movie.create(title: "Hidden Figures", year_id: 22)
    Movie.create(title: "Hieronymus Bosch: Touched by the Devil", year_id: 22)
    Movie.create(title: "High Strung", year_id: 22)
    Movie.create(title: "High-Rise", year_id: 22)
    Movie.create(title: "Hillary's America", year_id: 22)
    Movie.create(title: "Hillsong: Let Hope Rise", year_id: 22)
    Movie.create(title: "The Himalayas", year_id: 22)
    Movie.create(title: "Hockney", year_id: 22)
    Movie.create(title: "Holidays", year_id: 22)
    Movie.create(title: "The Hollars", year_id: 22)
    Movie.create(title: "The Hollow", year_id: 22)
    Movie.create(title: "The Hollow Point", year_id: 22)
    Movie.create(title: "Hollywood Beauty Salon", year_id: 22)
    Movie.create(title: "A Hologram for the King", year_id: 22)
    Movie.create(title: "Holy Hell", year_id: 22)
    Movie.create(title: "Homeland: Iraq Year Zero", year_id: 22)
    Movie.create(title: "The Homeless Billionaire", year_id: 22)
    Movie.create(title: "Homo sapiens", year_id: 22)
    Movie.create(title: "Honeyglue", year_id: 22)
    Movie.create(title: "Hooligan Sparrow", year_id: 22)
    Movie.create(title: "Housefull 3", year_id: 22)
    Movie.create(title: "How He Fell in Love", year_id: 22)
    Movie.create(title: "How to Be Single", year_id: 22)
    Movie.create(title: "How to Let Go of the World (And Love All the Things Climate Can't Change)", year_id: 22)
    Movie.create(title: "Hunt for the Wilderpeople", year_id: 22)
    Movie.create(title: "Hunter Gatherer", year_id: 22)
    Movie.create(title: "The Huntsman: Winter's War", year_id: 22)
    Movie.create(title: "Huntwatch", year_id: 22)
    Movie.create(title: "Hyena Road", year_id: 22)
    Movie.create(title: "I Am Not a Serial Killer", year_id: 22)
    Movie.create(title: "I Am Not Madame Bovary", year_id: 22)
    Movie.create(title: "I Am Not Your Negro", year_id: 22)
    Movie.create(title: "I Am Wrath", year_id: 22)
    Movie.create(title: "I Belonged to You", year_id: 22)
    Movie.create(title: "I, Daniel Blake", year_id: 22)
    Movie.create(title: "I Don't Belong Anywhere: Le cinéma de Chantal Akerman", year_id: 22)
    Movie.create(title: "I Saw the Light", year_id: 22)
    Movie.create(title: "Ice Age: Collision Course", year_id: 22)
    Movie.create(title: "Ice Guardians", year_id: 22)
    Movie.create(title: "The Idol", year_id: 22)
    Movie.create(title: "Ignacio de Loyola", year_id: 22)
    Movie.create(title: "The Illinois Parables", year_id: 22)
    Movie.create(title: "I'm Not Ashamed", year_id: 22)
    Movie.create(title: "Imperium", year_id: 22)
    Movie.create(title: "In a Valley of Violence", year_id: 22)
    Movie.create(title: "In Order of Disappearance", year_id: 22)
    Movie.create(title: "In Search of the American Dream", year_id: 22)
    Movie.create(title: "In the Shadow of Women", year_id: 22)
    Movie.create(title: "Incarnate", year_id: 22)
    Movie.create(title: "Independence Day: Resurgence", year_id: 22)
    Movie.create(title: "Indian Point", year_id: 22)
    Movie.create(title: "Indignation", year_id: 22)
    Movie.create(title: "Inferno", year_id: 22)
    Movie.create(title: "The Infiltrator", year_id: 22)
    Movie.create(title: "The Innocents", year_id: 22)
    Movie.create(title: "The Intervention", year_id: 22)
    Movie.create(title: "Into the Forest", year_id: 22)
    Movie.create(title: "Into the Inferno", year_id: 22)
    Movie.create(title: "Intruder", year_id: 22)
    Movie.create(title: "Intruders", year_id: 22)
    Movie.create(title: "The Invitation", year_id: 22)
    Movie.create(title: "Ip Man 3", year_id: 22)
    Movie.create(title: "Iron Moon", year_id: 22)
    Movie.create(title: "Is That a Gun in Your Pocket?...", year_id: 22)
    Movie.create(title: "Is That You?", year_id: 22)
    Movie.create(title: "I.T.", year_id: 22)
    Movie.create(title: "It Had to Be You", year_id: 22)
    Movie.create(title: "Ithaca", year_id: 22)
    Movie.create(title: "Ivory: A Crime Story", year_id: 22)
    Movie.create(title: "The Ivory Game", year_id: 22)
    Movie.create(title: "Ixcanul", year_id: 22)
    Movie.create(title: "Jack Goes Home", year_id: 22)
    Movie.create(title: "Jack of the Red Hearts", year_id: 22)
    Movie.create(title: "Jack Reacher: Never Go Back", year_id: 22)
    Movie.create(title: "Jackie", year_id: 22)
    Movie.create(title: "Jai GangaaJal", year_id: 22)
    Movie.create(title: "Janaan", year_id: 22)
    Movie.create(title: "Janatha Garage", year_id: 22)
    Movie.create(title: "Jane Got a Gun", year_id: 22)
    Movie.create(title: "Jane Wants a Boyfriend", year_id: 22)
    Movie.create(title: "Jason Bourne", year_id: 22)
    Movie.create(title: "The Jazz Loft According to W. Eugene Smith", year_id: 22)
    Movie.create(title: "Jeruzalem", year_id: 22)
    Movie.create(title: "Jia Zhangke, a Guy From Fenyang", year_id: 22)
    Movie.create(title: "Jim: The James Foley Story", year_id: 22)
    Movie.create(title: "Jimmy Vestvood: Amerikan Hero", year_id: 22)
    Movie.create(title: "Joshy", year_id: 22)
    Movie.create(title: "Julieta", year_id: 22)
    Movie.create(title: "The Jungle Book", year_id: 22)
    Movie.create(title: "Just the 3 of Us", year_id: 22)
    Movie.create(title: "Kaashmora", year_id: 22)
    Movie.create(title: "Kabali", year_id: 22)
    Movie.create(title: "Kahaani 2: Durga Rani Singh", year_id: 22)
    Movie.create(title: "Kaili Blues", year_id: 22)
    Movie.create(title: "Kampai! For the Love of Sake", year_id: 22)
    Movie.create(title: "Kapoor & Sons (Since 1921)", year_id: 22)
    Movie.create(title: "Kate Plays Christine", year_id: 22)
    Movie.create(title: "Keanu", year_id: 22)
    Movie.create(title: "Keepers of the Game", year_id: 22)
    Movie.create(title: "Keeping Up With the Joneses", year_id: 22)
    Movie.create(title: "Ki & Ka", year_id: 22)
    Movie.create(title: "Kickboxer: Vengeance", year_id: 22)
    Movie.create(title: "Kicks", year_id: 22)
    Movie.create(title: "Kill Your Friends", year_id: 22)
    Movie.create(title: "Kill Zone 2", year_id: 22)
    Movie.create(title: "Killing Ed", year_id: 22)
    Movie.create(title: "The Kind Words", year_id: 22)
    Movie.create(title: "King Cobra", year_id: 22)
    Movie.create(title: "King Georges", year_id: 22)
    Movie.create(title: "King Jack", year_id: 22)
    Movie.create(title: "Kingsglaive: Final Fantasy XV", year_id: 22)
    Movie.create(title: "Knight of Cups", year_id: 22)
    Movie.create(title: "Krisha", year_id: 22)
    Movie.create(title: "Ktown Cowboys", year_id: 22)
    Movie.create(title: "Kubo and the Two Strings", year_id: 22)
    Movie.create(title: "Kung Fu Panda 3", year_id: 22)
    Movie.create(title: "La La Land", year_id: 22)
    Movie.create(title: "Laal Rang", year_id: 22)
    Movie.create(title: "Lace Crater", year_id: 22)
    Movie.create(title: "Lamb", year_id: 22)
    Movie.create(title: "The Land", year_id: 22)
    Movie.create(title: "Land and Shade", year_id: 22)
    Movie.create(title: "Land of Mine", year_id: 22)
    Movie.create(title: "Landfill Harmonic", year_id: 22)
    Movie.create(title: "Last Cab to Darwin", year_id: 22)
    Movie.create(title: "Last Days in the Desert", year_id: 22)
    Movie.create(title: "The Last Man on the Moon", year_id: 22)
    Movie.create(title: "The Late Bloomer", year_id: 22)
    Movie.create(title: "L'attesa", year_id: 22)
    Movie.create(title: "Lazer Team", year_id: 22)
    Movie.create(title: "Lazy Eye", year_id: 22)
    Movie.create(title: "League of Gods", year_id: 22)
    Movie.create(title: "The Legend of Tarzan", year_id: 22)
    Movie.create(title: "Len and Company", year_id: 22)
    Movie.create(title: "The Lennon Report", year_id: 22)
    Movie.create(title: "Les cowboys", year_id: 22)
    Movie.create(title: "Let's Be Evil", year_id: 22)
    Movie.create(title: "Level Up", year_id: 22)
    Movie.create(title: "Life, Animated", year_id: 22)
    Movie.create(title: "Life on the Line", year_id: 22)
    Movie.create(title: "The Light Between Oceans", year_id: 22)
    Movie.create(title: "Lights Out", year_id: 22)
    Movie.create(title: "Like for Likes", year_id: 22)
    Movie.create(title: "Line Walker: The Movie", year_id: 22)
    Movie.create(title: "Lion", year_id: 22)
    Movie.create(title: "Little Men", year_id: 22)
    Movie.create(title: "The Little Prince", year_id: 22)
    Movie.create(title: "Little Sister", year_id: 22)
    Movie.create(title: "Live by Night", year_id: 22)
    Movie.create(title: "Lo and Behold: Reveries of the Connected World", year_id: 22)
    Movie.create(title: "The Lobster", year_id: 22)
    Movie.create(title: "Lolo", year_id: 22)
    Movie.create(title: "London Has Fallen", year_id: 22)
    Movie.create(title: "London Road", year_id: 22)
    Movie.create(title: "London Town", year_id: 22)
    Movie.create(title: "Long Way North", year_id: 22)
    Movie.create(title: "Look at Us Now, Mother!", year_id: 22)
    Movie.create(title: "L.O.R.D.: Legend of Ravaging Dynasties", year_id: 22)
    Movie.create(title: "Lost and Beautiful", year_id: 22)
    Movie.create(title: "The Lost Arcade", year_id: 22)
    Movie.create(title: "Louder Than Bombs", year_id: 22)
    Movie.create(title: "Love & Friendship", year_id: 22)
    Movie.create(title: "Love Is Blind", year_id: 22)
    Movie.create(title: "Love Thy Nature", year_id: 22)
    Movie.create(title: "The Love Witch", year_id: 22)
    Movie.create(title: "The Lovers & the Despot", year_id: 22)
    Movie.create(title: "Loving", year_id: 22)
    Movie.create(title: "Lucha Mexico", year_id: 22)
    Movie.create(title: "Luck-Key", year_id: 22)
    Movie.create(title: "ma ma", year_id: 22)
    Movie.create(title: "Mad Tiger", year_id: 22)
    Movie.create(title: "Madaari", year_id: 22)
    Movie.create(title: "Maggie's Plan", year_id: 22)
    Movie.create(title: "The Magnificent Seven", year_id: 22)
    Movie.create(title: "Magnus", year_id: 22)
    Movie.create(title: "Making a Killing: Guns, Greed, and the NRA", year_id: 22)
    Movie.create(title: "A Man Called Ove", year_id: 22)
    Movie.create(title: "Man Down", year_id: 22)
    Movie.create(title: "The Man Who Knew Infinity", year_id: 22)
    Movie.create(title: "Manchester By The Sea", year_id: 22)
    Movie.create(title: "Manhattan Night", year_id: 22)
    Movie.create(title: "Mapplethorpe: Look at the Pictures", year_id: 22)
    Movie.create(title: "Marathon: The Patriots Day Bombing", year_id: 22)
    Movie.create(title: "Marauders", year_id: 22)
    Movie.create(title: "Marguerite", year_id: 22)
    Movie.create(title: "Marguerite & Julien", year_id: 22)
    Movie.create(title: "Marinoni: The Fire in the Frame", year_id: 22)
    Movie.create(title: "Martyrs", year_id: 22)
    Movie.create(title: "Mascots", year_id: 22)
    Movie.create(title: "The Masked Saint", year_id: 22)
    Movie.create(title: "The Master", year_id: 22)
    Movie.create(title: "Masterminds", year_id: 22)
    Movie.create(title: "Masti-zaade", year_id: 22)
    Movie.create(title: "Mavis!", year_id: 22)
    Movie.create(title: "Max Steel", year_id: 22)
    Movie.create(title: "Maximum Ride", year_id: 22)
    Movie.create(title: "Maya Angelou: And Still I Rise", year_id: 22)
    Movie.create(title: "MBA Partners", year_id: 22)
    Movie.create(title: "Me Before You", year_id: 22)
    Movie.create(title: "Me Him Her", year_id: 22)
    Movie.create(title: "The Measure of a Man", year_id: 22)
    Movie.create(title: "Mechanic: Resurrection", year_id: 22)
    Movie.create(title: "The Meddler", year_id: 22)
    Movie.create(title: "Meet the Blacks", year_id: 22)
    Movie.create(title: "Men & Chicken", year_id: 22)
    Movie.create(title: "Men Go to Battle", year_id: 22)
    Movie.create(title: "Mermaid", year_id: 22)
    Movie.create(title: "Mia Madre", year_id: 22)
    Movie.create(title: "Michael Moore in TrumpLand", year_id: 22)
    Movie.create(title: "Microbe and Gasoline", year_id: 22)
    Movie.create(title: "Middle School: The Worst Years of My Life", year_id: 22)
    Movie.create(title: "Midnight Special", year_id: 22)
    Movie.create(title: "Mifune: The Last Samurai", year_id: 22)
    Movie.create(title: "Mike and Dave Need Wedding Dates", year_id: 22)
    Movie.create(title: "Miles Ahead", year_id: 22)
    Movie.create(title: "The Mind's Eye", year_id: 22)
    Movie.create(title: "Miracles From Heaven", year_id: 22)
    Movie.create(title: "Mirzya", year_id: 22)
    Movie.create(title: "Misconduct", year_id: 22)
    Movie.create(title: "The Misfortunes of François Jane", year_id: 22)
    Movie.create(title: "Miss Hokusai", year_id: 22)
    Movie.create(title: "Miss Peregrine's Home for Peculiar Children", year_id: 22)
    Movie.create(title: "Miss Sharon Jones!", year_id: 22)
    Movie.create(title: "Miss Sloane", year_id: 22)
    Movie.create(title: "Miss Stevens", year_id: 22)
    Movie.create(title: "Mission Milano", year_id: 22)
    Movie.create(title: "Mr. Church", year_id: 22)
    Movie.create(title: "Mr. Donkey", year_id: 22)
    Movie.create(title: "Mr. Right", year_id: 22)
    Movie.create(title: "Moana", year_id: 22)
    Movie.create(title: "The Model", year_id: 22)
    Movie.create(title: "Mohenjo Daro", year_id: 22)
    Movie.create(title: "Mojave", year_id: 22)
    Movie.create(title: "Monday at 11:01 A.M.", year_id: 22)
    Movie.create(title: "Money Monster", year_id: 22)
    Movie.create(title: "The Monkey King 2", year_id: 22)
    Movie.create(title: "The Monster", year_id: 22)
    Movie.create(title: "A Monster Calls", year_id: 22)
    Movie.create(title: "Monster Hunt", year_id: 22)
    Movie.create(title: "A Monster With a Thousand Heads", year_id: 22)
    Movie.create(title: "Moonlight", year_id: 22)
    Movie.create(title: "Moonwalkers", year_id: 22)
    Movie.create(title: "Morgan", year_id: 22)
    Movie.create(title: "Morris From America", year_id: 22)
    Movie.create(title: "Mothers and Daughters", year_id: 22)
    Movie.create(title: "Mother's Day", year_id: 22)
    Movie.create(title: "Mountain Men", year_id: 22)
    Movie.create(title: "Mountains May Depart", year_id: 22)
    Movie.create(title: "M.S. Dhoni: The Untold Story", year_id: 22)
    Movie.create(title: "The Music of Strangers", year_id: 22)
    Movie.create(title: "My Best Friend's Wedding", year_id: 22)
    Movie.create(title: "My Big Fat Greek Wedding 2", year_id: 22)
    Movie.create(title: "My Big Night", year_id: 22)
    Movie.create(title: "My Blind Brother", year_id: 22)
    Movie.create(title: "My Dead Boyfriend", year_id: 22)
    Movie.create(title: "My Golden Days", year_id: 22)
    Movie.create(title: "My King", year_id: 22)
    Movie.create(title: "My Love, Don't Cross That River", year_id: 22)
    Movie.create(title: "National Bird", year_id: 22)
    Movie.create(title: "Natural Born Pranksters", year_id: 22)
    Movie.create(title: "Natural Selection", year_id: 22)
    Movie.create(title: "Naz & Maalik", year_id: 22)
    Movie.create(title: "Neerja", year_id: 22)
    Movie.create(title: "Neighbors 2: Sorority Rising", year_id: 22)
    Movie.create(title: "Neither Heaven nor Earth", year_id: 22)
    Movie.create(title: "Neon Bull", year_id: 22)
    Movie.create(title: "The Neon Demon", year_id: 22)
    Movie.create(title: "Neruda", year_id: 22)
    Movie.create(title: "Nerve", year_id: 22)
    Movie.create(title: "Never Gone", year_id: 22)
    Movie.create(title: "Never Surrender: The Ed Ramsey Story", year_id: 22)
    Movie.create(title: "The New Year's Eve of Old Lee", year_id: 22)
    Movie.create(title: "New York New York", year_id: 22)
    Movie.create(title: "Newtown", year_id: 22)
    Movie.create(title: "The Nice Guys", year_id: 22)
    Movie.create(title: "Nina", year_id: 22)
    Movie.create(title: "Nine Lives", year_id: 22)
    Movie.create(title: "1920 London", year_id: 22)
    Movie.create(title: "The 9th Life of Louis Drax", year_id: 22)
    Movie.create(title: "No Home Movie", year_id: 22)
    Movie.create(title: "No Letting Go", year_id: 22)
    Movie.create(title: "No manches Frida", year_id: 22)
    Movie.create(title: "No One's Life Is Easy", year_id: 22)
    Movie.create(title: "Nocturnal Animals", year_id: 22)
    Movie.create(title: "Norm of the North", year_id: 22)
    Movie.create(title: "Norman Lear: Just Another Version of You", year_id: 22)
    Movie.create(title: "Notes on Blindness", year_id: 22)
    Movie.create(title: "Notfilm", year_id: 22)
    Movie.create(title: "Now You See Me 2", year_id: 22)
    Movie.create(title: "Nuts!", year_id: 22)
    Movie.create(title: "Off the Rails", year_id: 22)
    Movie.create(title: "The Offering", year_id: 22)
    Movie.create(title: "Office Christmas Party", year_id: 22)
    Movie.create(title: "O.J.: Made in America", year_id: 22)
    Movie.create(title: "Old Stone", year_id: 22)
    Movie.create(title: "Older Than Ireland", year_id: 22)
    Movie.create(title: "Olé Olé Olé!: A Trip Across Latin America", year_id: 22)
    Movie.create(title: "Olympic Pride, American Prejudice", year_id: 22)
    Movie.create(title: "On the Map", year_id: 22)
    Movie.create(title: "100 Years", year_id: 22)
    Movie.create(title: "One More Time", year_id: 22)
    Movie.create(title: "One Night Only", year_id: 22)
    Movie.create(title: "1000 Rupee Note", year_id: 22)
    Movie.create(title: "The Ones Below", year_id: 22)
    Movie.create(title: "Operation Avalanche", year_id: 22)
    Movie.create(title: "Operation Chromite", year_id: 22)
    Movie.create(title: "Operation Mekong", year_id: 22)
    Movie.create(title: "Ordinary World", year_id: 22)
    Movie.create(title: "Other People", year_id: 22)
    Movie.create(title: "Other People's Children", year_id: 22)
    Movie.create(title: "The Other Side", year_id: 22)
    Movie.create(title: "The Other Side of the Door", year_id: 22)
    Movie.create(title: "The Otherworld", year_id: 22)
    Movie.create(title: "Ouija: Origin of Evil", year_id: 22)
    Movie.create(title: "Our Kind of Traitor", year_id: 22)
    Movie.create(title: "Our Last Tango", year_id: 22)
    Movie.create(title: "Our Little Sister", year_id: 22)
    Movie.create(title: "Outlaws and Angels", year_id: 22)
    Movie.create(title: "Ovation!", year_id: 22)
    Movie.create(title: "The Pack", year_id: 22)
    Movie.create(title: "Pali Road", year_id: 22)
    Movie.create(title: "Papa", year_id: 22)
    Movie.create(title: "Papa: Hemingway in Cuba", year_id: 22)
    Movie.create(title: "Parched", year_id: 22)
    Movie.create(title: "Passage to Mars", year_id: 22)
    Movie.create(title: "Passengers", year_id: 22)
    Movie.create(title: "Paterson", year_id: 22)
    Movie.create(title: "Paths of the Soul", year_id: 22)
    Movie.create(title: "Patriots Day", year_id: 22)
    Movie.create(title: "Pelé: Birth of a Legend", year_id: 22)
    Movie.create(title: "The People vs. Fritz Bauer", year_id: 22)
    Movie.create(title: "A Perfect Day", year_id: 22)
    Movie.create(title: "The Perfect Match", year_id: 22)
    Movie.create(title: "Pervert Park", year_id: 22)
    Movie.create(title: "Pet", year_id: 22)
    Movie.create(title: "Peter and the Farm", year_id: 22)
    Movie.create(title: "Pete's Dragon", year_id: 22)
    Movie.create(title: "Phantom Boy", year_id: 22)
    Movie.create(title: "Phantom Detective", year_id: 22)
    Movie.create(title: "Phantom of the Theatre", year_id: 22)
    Movie.create(title: "The Phenom", year_id: 22)
    Movie.create(title: "The Pickle Recipe", year_id: 22)
    Movie.create(title: "Pink", year_id: 22)
    Movie.create(title: "Popstar: Never Stop Never Stopping", year_id: 22)
    Movie.create(title: "Portrait of a Garden", year_id: 22)
    Movie.create(title: "Precious Cargo", year_id: 22)
    Movie.create(title: "The Preppie Connection", year_id: 22)
    Movie.create(title: "Prescription Thugs", year_id: 22)
    Movie.create(title: "Presenting Princess Shaw", year_id: 22)
    Movie.create(title: "The President", year_id: 22)
    Movie.create(title: "Priceless", year_id: 22)
    Movie.create(title: "Pride and Prejudice and Zombies", year_id: 22)
    Movie.create(title: "Princess", year_id: 22)
    Movie.create(title: "The Prison in Twelve Landscapes", year_id: 22)
    Movie.create(title: "The Program", year_id: 22)
    Movie.create(title: "Providence", year_id: 22)
    Movie.create(title: "Puerto Ricans in Paris", year_id: 22)
    Movie.create(title: "The Purge: Election Year", year_id: 22)
    Movie.create(title: "Queen of Katwe", year_id: 22)
    Movie.create(title: "Quitters", year_id: 22)
    Movie.create(title: "Rabid Dogs", year_id: 22)
    Movie.create(title: "Rabin in His Own Words", year_id: 22)
    Movie.create(title: "Rabin: The Last Day", year_id: 22)
    Movie.create(title: "Race", year_id: 22)
    Movie.create(title: "Raiders!: The Story of the Greatest Fan Film Ever Made", year_id: 22)
    Movie.create(title: "Rainbow Time", year_id: 22)
    Movie.create(title: "Raman Raghav 2.0", year_id: 22)
    Movie.create(title: "Rams", year_id: 22)
    Movie.create(title: "Ratchet & Clank", year_id: 22)
    Movie.create(title: "Ratter", year_id: 22)
    Movie.create(title: "The Red Pill", year_id: 22)
    Movie.create(title: "The Red Turtle", year_id: 22)
    Movie.create(title: "Regression", year_id: 22)
    Movie.create(title: "The Remains", year_id: 22)
    Movie.create(title: "A Remarkable Life", year_id: 22)
    Movie.create(title: "Remember", year_id: 22)
    Movie.create(title: "Requiem for the American Dream", year_id: 22)
    Movie.create(title: "Richard Linklater: Dream Is Destiny", year_id: 22)
    Movie.create(title: "Ride Along 2", year_id: 22)
    Movie.create(title: "Right Now, Wrong Then", year_id: 22)
    Movie.create(title: "Rio, I Love You", year_id: 22)
    Movie.create(title: "Risen", year_id: 22)
    Movie.create(title: "River", year_id: 22)
    Movie.create(title: "The River Thief", year_id: 22)
    Movie.create(title: "Road Games", year_id: 22)
    Movie.create(title: "Rock On 2", year_id: 22)
    Movie.create(title: "Rocky Handsome", year_id: 22)
    Movie.create(title: "Rogue One", year_id: 22)
    Movie.create(title: "Rolling Papers", year_id: 22)
    Movie.create(title: "Ron and Laura Take Back America", year_id: 22)
    Movie.create(title: "Rooted in Peace", year_id: 22)
    Movie.create(title: "Roseanne for President!", year_id: 22)
    Movie.create(title: "The Ruins of Lifta: Where the Holocaust and Nakba Meet", year_id: 22)
    Movie.create(title: "Rules Don't Apply", year_id: 22)
    Movie.create(title: "Rustom", year_id: 22)
    Movie.create(title: "S Storm", year_id: 22)
    Movie.create(title: "Saala Khadoos", year_id: 22)
    Movie.create(title: "Sacrifice", year_id: 22)
    Movie.create(title: "Sand Storm", year_id: 22)
    Movie.create(title: "Sarbjit", year_id: 22)
    Movie.create(title: "Sausage Party", year_id: 22)
    Movie.create(title: "The Sea of Trees", year_id: 22)
    Movie.create(title: "Search Party", year_id: 22)
    Movie.create(title: "Seasons", year_id: 22)
    Movie.create(title: "The Seasons in Quincy: Four Portraits of John Berger", year_id: 22)
    Movie.create(title: "The Secret Life of Pets", year_id: 22)
    Movie.create(title: "Seed: The Untold Story", year_id: 22)
    Movie.create(title: "Seoul Searching", year_id: 22)
    Movie.create(title: "Septembers of Shiraz", year_id: 22)
    Movie.create(title: "The Seventh Fire", year_id: 22)
    Movie.create(title: "Sex and Broadcasting", year_id: 22)
    Movie.create(title: "Shadow World", year_id: 22)
    Movie.create(title: "The Shallows", year_id: 22)
    Movie.create(title: "Shangri-La Suite", year_id: 22)
    Movie.create(title: "Shelley", year_id: 22)
    Movie.create(title: "Shin Godzilla", year_id: 22)
    Movie.create(title: "Shivaay", year_id: 22)
    Movie.create(title: "Short Stay", year_id: 22)
    Movie.create(title: "Shut In", year_id: 22)
    Movie.create(title: "Sicilian Vampire", year_id: 22)
    Movie.create(title: "Silence", year_id: 22)
    Movie.create(title: "Silicon Cowboys", year_id: 22)
    Movie.create(title: "Sin Alas", year_id: 22)
    Movie.create(title: "Sing", year_id: 22)
    Movie.create(title: "Sing Street", year_id: 22)
    Movie.create(title: "Siren", year_id: 22)
    Movie.create(title: "Sister Cities", year_id: 22)
    Movie.create(title: "600 Miles", year_id: 22)
    Movie.create(title: "Skiptrace", year_id: 22)
    Movie.create(title: "Sky Ladder: The Art of Cai Guo-Qiang", year_id: 22)
    Movie.create(title: "Sky on Fire", year_id: 22)
    Movie.create(title: "Slash", year_id: 22)
    Movie.create(title: "Snowden", year_id: 22)
    Movie.create(title: "Snowtime!", year_id: 22)
    Movie.create(title: "Solace", year_id: 22)
    Movie.create(title: "Sold", year_id: 22)
    Movie.create(title: "Solitary", year_id: 22)
    Movie.create(title: "Someone to Talk To", year_id: 22)
    Movie.create(title: "Songs My Brothers Taught Me", year_id: 22)
    Movie.create(title: "SoulMate", year_id: 22)
    Movie.create(title: "Southbound", year_id: 22)
    Movie.create(title: "Southside With You", year_id: 22)
    Movie.create(title: "Southwest of Salem: The Story of the San Antonio Four", year_id: 22)
    Movie.create(title: "Spa Night", year_id: 22)
    Movie.create(title: "A Space Program", year_id: 22)
    Movie.create(title: "Spaceman", year_id: 22)
    Movie.create(title: "Spirits' Homecoming", year_id: 22)
    Movie.create(title: "Stagecoach: The Texas Jack Story", year_id: 22)
    Movie.create(title: "A Stand Up Guy", year_id: 22)
    Movie.create(title: "Standing Tall", year_id: 22)
    Movie.create(title: "Standoff", year_id: 22)
    Movie.create(title: "Star Trek Beyond", year_id: 22)
    Movie.create(title: "Starving the Beast", year_id: 22)
    Movie.create(title: "Stealing Cars", year_id: 22)
    Movie.create(title: "Storks", year_id: 22)
    Movie.create(title: "A Stray", year_id: 22)
    Movie.create(title: "A Street Cat Named Bob", year_id: 22)
    Movie.create(title: "Streit's: Matzo and the American Dream", year_id: 22)
    Movie.create(title: "Sugar Mountain", year_id: 22)
    Movie.create(title: "Suicide Squad", year_id: 22)
    Movie.create(title: "Sully", year_id: 22)
    Movie.create(title: "Sultan", year_id: 22)
    Movie.create(title: "Summer Camp", year_id: 22)
    Movie.create(title: "Summer of 8", year_id: 22)
    Movie.create(title: "Summertime", year_id: 22)
    Movie.create(title: "Sundown", year_id: 22)
    Movie.create(title: "Sunset Song", year_id: 22)
    Movie.create(title: "The Super Parental Guardians", year_id: 22)
    Movie.create(title: "Supersonic", year_id: 22)
    Movie.create(title: "Sweaty Betty", year_id: 22)
    Movie.create(title: "Sweet Bean", year_id: 22)
    Movie.create(title: "Sweet Sixteen", year_id: 22)
    Movie.create(title: "Swiss Army Man", year_id: 22)
    Movie.create(title: "Sword Master", year_id: 22)
    Movie.create(title: "Sworn Virgin", year_id: 22)
    Movie.create(title: "The Syndrome", year_id: 22)
    Movie.create(title: "The Take", year_id: 22)
    Movie.create(title: "Take Me to the River", year_id: 22)
    Movie.create(title: "A Tale of Love and Darkness", year_id: 22)
    Movie.create(title: "Tale of Tales", year_id: 22)
    Movie.create(title: "Tallulah", year_id: 22)
    Movie.create(title: "Tank 432", year_id: 22)
    Movie.create(title: "Tanna", year_id: 22)
    Movie.create(title: "Te3n", year_id: 22)
    Movie.create(title: "Teenage Mutant Ninja Turtles: Out of the Shadows", year_id: 22)
    Movie.create(title: "The Teller and the Truth", year_id: 22)
    Movie.create(title: "10 Cloverfield Lane", year_id: 22)
    Movie.create(title: "The Tenth Man", year_id: 22)
    Movie.create(title: "Tere Bin Laden: Dead or Alive", year_id: 22)
    Movie.create(title: "Term Life", year_id: 22)
    Movie.create(title: "Thank You for Playing", year_id: 22)
    Movie.create(title: "Thank You for Your Service", year_id: 22)
    Movie.create(title: "Tharlo", year_id: 22)
    Movie.create(title: "Theo Who Lived", year_id: 22)
    Movie.create(title: "Therapy for a Vampire", year_id: 22)
    Movie.create(title: "They Will Have to Kill Us First", year_id: 22)
    Movie.create(title: "They're Watching", year_id: 22)
    Movie.create(title: "Things to Come", year_id: 22)
    Movie.create(title: "The Third Party", year_id: 22)
    Movie.create(title: "3rd Street Blackout", year_id: 22)
    Movie.create(title: "13 Cameras", year_id: 22)
    Movie.create(title: "13 Hours: The Secret Soldiers of Benghazi", year_id: 22)
    Movie.create(title: "13th", year_id: 22)
    Movie.create(title: "30 Days With My Brother", year_id: 22)
    Movie.create(title: "31", year_id: 22)
    Movie.create(title: "37", year_id: 22)
    Movie.create(title: "This Is Life", year_id: 22)
    Movie.create(title: "This Time", year_id: 22)
    Movie.create(title: "Those People", year_id: 22)
    Movie.create(title: "The Thoughts That Once We Had", year_id: 22)
    Movie.create(title: "Three", year_id: 22)
    Movie.create(title: "Tickled", year_id: 22)
    Movie.create(title: "The Tiger: An Old Hunter's Tale", year_id: 22)
    Movie.create(title: "Tikkun", year_id: 22)
    Movie.create(title: "'Til Madness Do Us Part", year_id: 22)
    Movie.create(title: "Time Raiders", year_id: 22)
    Movie.create(title: "Time to Choose", year_id: 22)
    Movie.create(title: "To Steal From a Thief", year_id: 22)
    Movie.create(title: "Toni Erdmann", year_id: 22)
    Movie.create(title: "Tony Robbins: I Am Not Your Guru", year_id: 22)
    Movie.create(title: "Too Late", year_id: 22)
    Movie.create(title: "Touched With Fire", year_id: 22)
    Movie.create(title: "Tower", year_id: 22)
    Movie.create(title: "Traded", year_id: 22)
    Movie.create(title: "Train to Busan", year_id: 22)
    Movie.create(title: "The Trans List", year_id: 22)
    Movie.create(title: "Transfixed", year_id: 22)
    Movie.create(title: "Transpecos", year_id: 22)
    Movie.create(title: "Trapped", year_id: 22)
    Movie.create(title: "Trash Fire", year_id: 22)
    Movie.create(title: "The Treasure", year_id: 22)
    Movie.create(title: "T-Rex", year_id: 22)
    Movie.create(title: "Trezoros: The Lost Jews of Kastoria", year_id: 22)
    Movie.create(title: "Triple 9", year_id: 22)
    Movie.create(title: "Trolls", year_id: 22)
    Movie.create(title: "Troublemakers: The Story of Land Art", year_id: 22)
    Movie.create(title: "The Trust", year_id: 22)
    Movie.create(title: "Tumbledown", year_id: 22)
    Movie.create(title: "The Tunnel", year_id: 22)
    Movie.create(title: "20th Century Women", year_id: 22)
    Movie.create(title: "Two Lovers and a Bear", year_id: 22)
    Movie.create(title: "2 Policias en Apuros", year_id: 22)
    Movie.create(title: "2016 Academy Award Nominated Animated Short Films", year_id: 22)
    Movie.create(title: "2016 Academy Award Nominated Documentary Short Films - Program A", year_id: 22)
    Movie.create(title: "2016 Academy Award Nominated Documentary Short Films - Program B", year_id: 22)
    Movie.create(title: "2016 Academy Award Nominated Live-Action Short Films", year_id: 22)
    Movie.create(title: "2016 Sundance Film Festival Short Film Tour", year_id: 22)
    Movie.create(title: "Two Trains Runnin'", year_id: 22)
    Movie.create(title: "Tyler Perry's Boo! A Madea Halloween", year_id: 22)
    Movie.create(title: "Udta Punjab", year_id: 22)
    Movie.create(title: "Uncle Howard", year_id: 22)
    Movie.create(title: "Uncle Kent 2!", year_id: 22)
    Movie.create(title: "The Uncondemned", year_id: 22)
    Movie.create(title: "Under the Gun", year_id: 22)
    Movie.create(title: "Under the Shadow", year_id: 22)
    Movie.create(title: "Under the Sun", year_id: 22)
    Movie.create(title: "Underfire: The Untold Story of Pfc. Tony Vaccaro", year_id: 22)
    Movie.create(title: "Undrafted", year_id: 22)
    Movie.create(title: "Unlocking the Cage", year_id: 22)
    Movie.create(title: "Unlucky Plaza", year_id: 22)
    Movie.create(title: "The Unmarried Wife", year_id: 22)
    Movie.create(title: "The Unspoken", year_id: 22)
    Movie.create(title: "Urge", year_id: 22)
    Movie.create(title: "U.S.S. Indianapolis: The Legacy Project", year_id: 22)
    Movie.create(title: "USS Indianapolis: Men of Courage", year_id: 22)
    Movie.create(title: "Valley of Love", year_id: 22)
    Movie.create(title: "Vanishing Time: A Boy Who Returned", year_id: 22)
    Movie.create(title: "Vaxxed: From Cover-Up to Catastrophe", year_id: 22)
    Movie.create(title: "The Vessel", year_id: 22)
    Movie.create(title: "Videofilia (And Other Viral Syndromes)", year_id: 22)
    Movie.create(title: "Viktoria", year_id: 22)
    Movie.create(title: "A Violent Prosecutor", year_id: 22)
    Movie.create(title: "Viral", year_id: 22)
    Movie.create(title: "Virus of Fear", year_id: 22)
    Movie.create(title: "Vita Activa, the Spirit of Hannah Arendt", year_id: 22)
    Movie.create(title: "Viva", year_id: 22)
    Movie.create(title: "Voyage of Time", year_id: 22)
    Movie.create(title: "The Wailing", year_id: 22)
    Movie.create(title: "#Walang Forever", year_id: 22)
    Movie.create(title: "A War", year_id: 22)
    Movie.create(title: "War Dogs", year_id: 22)
    Movie.create(title: "Warcraft", year_id: 22)
    Movie.create(title: "The Wasted Times", year_id: 22)
    Movie.create(title: "Watani: My Homeland", year_id: 22)
    Movie.create(title: "The Wave", year_id: 22)
    Movie.create(title: "Wazir", year_id: 22)
    Movie.create(title: "We Are Twisted F***ing Sister", year_id: 22)
    Movie.create(title: "We Are X", year_id: 22)
    Movie.create(title: "We the People: The Market Basket Effect", year_id: 22)
    Movie.create(title: "Wedding Doll", year_id: 22)
    Movie.create(title: "A Weekend With the Family", year_id: 22)
    Movie.create(title: "Weiner", year_id: 22)
    Movie.create(title: "Welcome to Happiness", year_id: 22)
    Movie.create(title: "What Now?", year_id: 22)
    Movie.create(title: "What We Become", year_id: 22)
    Movie.create(title: "When Larry Met Mary", year_id: 22)
    Movie.create(title: "When the Bough Breaks", year_id: 22)
    Movie.create(title: "When Two Worlds Collide", year_id: 22)
    Movie.create(title: "Whiskey Tango Foxtrot", year_id: 22)
    Movie.create(title: "White Girl", year_id: 22)
    Movie.create(title: "The Whole Truth", year_id: 22)
    Movie.create(title: "Who's Driving Doug", year_id: 22)
    Movie.create(title: "Why Him?", year_id: 22)
    Movie.create(title: "Wiener-Dog", year_id: 22)
    Movie.create(title: "The Wild Life", year_id: 22)
    Movie.create(title: "Wild Oats", year_id: 22)
    Movie.create(title: "The Witch: A New-England Folktale", year_id: 22)
    Movie.create(title: "The Witness", year_id: 22)
    Movie.create(title: "X-Men: Apocalypse", year_id: 22)
    Movie.create(title: "Yarn", year_id: 22)
    Movie.create(title: "Yellow Day", year_id: 22)
    Movie.create(title: "Yosemite", year_id: 22)
    Movie.create(title: "The Young Messiah", year_id: 22)
    Movie.create(title: "You've Been Trumped Too", year_id: 22)
    Movie.create(title: "Zero Days", year_id: 22)
    Movie.create(title: "Zoolander 2", year_id: 22)
    Movie.create(title: "Zoom", year_id: 22)
    Movie.create(title: "Zootopia", year_id: 22)
  end
end
