class Year < ActiveRecord::Base
  has_many :movies
  has_many :ballots
  has_many :credits
  has_many :scenes

  validates :name, presence: true
  validates :open_voting, presence: true
  validates :close_voting, presence: true
  validates :display_results, presence: true


  def self.results_display
    where("display_results < ?", Time.zone.now).last
  end

  def self.active_voting
    where("open_voting < ? AND close_voting > ?", Time.zone.now, Time.zone.now).last
  end

  def self.all_but_results_display
    year_array = []
    where("display_results < ?", Time.zone.now).all.each do |y|
      if y != Year.results_display
        year_array << y
      end
    end
    year_array
  end

  def self.get_display_year(year)
    if year
      where("name = ? and display_results < ?", year, Time.zone.now ).last
    else
      Year.results_display
    end
  end

  def eligible_movies_by_average_rating
    movies.where("nbr_ratings > 4").order(average_rating: :desc, title_index: :asc)
  end

  def ranked_movies_hash
    ranked_movies_hash = {}
    hold_for_ties_array = []
    tie_start_index = 0
    tie_average_rating = 0.00
    movies_array = eligible_movies_by_average_rating
    movies_array.each_with_index do |m,index|
      if m.average_rating == tie_average_rating || index == 0 # this movie is tied with the previous movie on the list
        hold_for_ties_array << m
        if index + 1 == movies_array.length # end of the list--move last movie (plus any previous ties) to hash
          rank_array = (tie_start_index..index + 1).to_a
          rank_sum = rank_array.inject(:+)
          average_rank_of_tied_movies = rank_sum.to_f / hold_for_ties_array.length.to_f
          hold_for_ties_array.each do |m|
            ranked_movies_hash[m.id] = average_rank_of_tied_movies
          end
        end
      else
        if hold_for_ties_array.length > 1 # there are two or more tied movies in the hold array
          rank_array = (tie_start_index..index).to_a
          rank_sum = rank_array.inject(:+)
          average_rank_of_tied_movies = rank_sum.to_f / hold_for_ties_array.length.to_f
          hold_for_ties_array.each do |m|
            ranked_movies_hash[m.id] = average_rank_of_tied_movies
          end
        elsif hold_for_ties_array.length == 1 # there is a single movie in the hold array.  There were no ties.
          ranked_movies_hash[hold_for_ties_array[0].id] = index
        end
        if index + 1 == movies_array.length # end of the list--move last movie to the hash
          ranked_movies_hash[m.id] = index + 1
        else
          hold_for_ties_array = [m]
          tie_start_index = index + 1
          tie_average_rating = m.average_rating
        end
      end
    end
    ranked_movies_hash
  end

  def save_movie_vote_results
    picture_category = Category.where(name: "picture").first
    director_category = Category.where(name: "director").first
    screenplay_category = Category.where(name: "screenplay").first
    movies.each do |m|
      m.picture_points = m.compute_points(picture_category)
      m.picture_votes = m.compute_votes(picture_category)
      m.director_points = m.compute_points(director_category)
      m.director_votes = m.compute_votes(director_category)
      m.screenplay_points = m.compute_points(screenplay_category)
      m.screenplay_votes = m.compute_votes(screenplay_category)
      m.save
    end
  end

  def save_credit_vote_results
    actor_job = Job.where(name: "actor")
    credits.where(job: actor_job).each do |c|
      results_category = c.compute_results_category
      c.category = results_category
      c.points = c.compute_points_results(results_category)
      c.nbr_votes = c.compute_votes_results(results_category)
      c.save
    end
  end

  def save_scene_vote_results
    scenes.each do |s|
      s.nbr_votes = s.compute_votes
      s.points = s.compute_points
      s.save
    end
  end

  def save_ratings_results
    movies.each do |m|
      m.nbr_ratings = m.compute_total_nbr_ratings
      m.average_rating = m.compute_average_rating
      m.four_ratings = m.compute_nbr_ratings(4.0)
      m.three_pt_five_ratings = m.compute_nbr_ratings(3.5)
      m.three_ratings = m.compute_nbr_ratings(3.0)
      m.two_pt_five_ratings = m.compute_nbr_ratings(2.5)
      m.two_ratings = m.compute_nbr_ratings(2.0)
      m.one_pt_five_ratings = m.compute_nbr_ratings(1.5)
      m.one_ratings = m.compute_nbr_ratings(1.0)
      m.zero_ratings = m.compute_nbr_ratings(0.0)
      if m.compute_total_nbr_ratings > 1
        m.standard_dev = m.compute_standard_dev
      end
      m.save
    end
  end

  def save_user_profile_results
    ballots.each do |b|
      b.nbr_ratings = b.compute_total_nbr_ratings
      b.average_rating = b.compute_average_rating
      b.four_ratings = b.compute_nbr_ratings(4.0)
      b.three_pt_five_ratings = b.compute_nbr_ratings(3.5)
      b.three_ratings = b.compute_nbr_ratings(3.0)
      b.two_pt_five_ratings = b.compute_nbr_ratings(2.5)
      b.two_ratings = b.compute_nbr_ratings(2.0)
      b.one_pt_five_ratings = b.compute_nbr_ratings(1.5)
      b.one_ratings = b.compute_nbr_ratings(1.0)
      b.zero_ratings = b.compute_nbr_ratings(0.0)
      b.selectivity_index = b.compute_selectivity_index
      b.save
    end
  end

  def save_complete_results
    save_movie_vote_results
    save_credit_vote_results
    save_scene_vote_results
    save_ratings_results
    save_user_profile_results
  end

  def self.upload_2024_movies
    Movie.create(title: "Aattam", year_id: 30)
    Movie.create(title: "The Abandon", year_id: 30)
    Movie.create(title: "Abigail", year_id: 30)
    Movie.create(title: "The Absence of Eden", year_id: 30)
    Movie.create(title: "Absolution", year_id: 30)
    Movie.create(title: "Accidental Texan", year_id: 30)
    Movie.create(title: "Across the River and Into the Trees", year_id: 30)
    Movie.create(title: "Adios Buenos Aires", year_id: 30)
    Movie.create(title: "Adrianne & the Castle", year_id: 30)
    Movie.create(title: "Afraid", year_id: 30)
    Movie.create(title: "After: Poetry Destroys Silence", year_id: 30)
    Movie.create(title: "Aftermath", year_id: 30)
    Movie.create(title: "Afterwater", year_id: 30)
    Movie.create(title: "Agastya: Chapter 1", year_id: 30)
    Movie.create(title: "Agent of Happiness", year_id: 30)
    Movie.create(title: "Aggro Dr1ft", year_id: 30)
    Movie.create(title: "Aisha", year_id: 30)
    Movie.create(title: "Albany Road", year_id: 30)
    Movie.create(title: "Alien: Romulus", year_id: 30)
    Movie.create(title: "Alien Rubicon", year_id: 30)
    Movie.create(title: "Alienoid: The Return to the Future", year_id: 30)
    Movie.create(title: "All Happy Families", year_id: 30)
    Movie.create(title: "All Shall Be Well", year_id: 30)
    Movie.create(title: "All We Imagine as Light", year_id: 30)
    Movie.create(title: "Allswell in New York", year_id: 30)
    Movie.create(title: "Altered Reality", year_id: 30)
    Movie.create(title: "Am I OK?", year_id: 30)
    Movie.create(title: "Am I Racist?", year_id: 30)
    Movie.create(title: "Amaran", year_id: 30)
    Movie.create(title: "Ambajipeta Marriage Band", year_id: 30)
    Movie.create(title: "Amber Alert", year_id: 30)
    Movie.create(title: "Ameena", year_id: 30)
    Movie.create(title: "Amelia's Children", year_id: 30)
    Movie.create(title: "America—Everything You've Ever Dreamed Of: The Films of Tony Ganz & Rhody Streeter", year_id: 30)
    Movie.create(title: "The American", year_id: 30)
    Movie.create(title: "American Dreamer", year_id: 30)
    Movie.create(title: "The American Society of Magical Negroes", year_id: 30)
    Movie.create(title: "American Star", year_id: 30)
    Movie.create(title: "Americans With No Address", year_id: 30)
    Movie.create(title: "America's Burning", year_id: 30)
    Movie.create(title: "And Mrs", year_id: 30)
    Movie.create(title: "Andrea Bocelli 30: The Celebration", year_id: 30)
    Movie.create(title: "The Animal Kingdom", year_id: 30)
    Movie.create(title: "Animalia", year_id: 30)
    Movie.create(title: "Anora", year_id: 30)
    Movie.create(title: "Apartment 7A", year_id: 30)
    Movie.create(title: "Apolonia, Apolonia", year_id: 30)
    Movie.create(title: "The Apprentice", year_id: 30)
    Movie.create(title: "Aranmanai 4", year_id: 30)
    Movie.create(title: "The Arc of Oblivion", year_id: 30)
    Movie.create(title: "Arcadian", year_id: 30)
    Movie.create(title: "Ardaas Sarbat De Bhalle Di", year_id: 30)
    Movie.create(title: "Argylle", year_id: 30)
    Movie.create(title: "A · R · M", year_id: 30)
    Movie.create(title: "Armand", year_id: 30)
    Movie.create(title: "Armor", year_id: 30)
    Movie.create(title: "Art College 1994", year_id: 30)
    Movie.create(title: "Art Dealers", year_id: 30)
    Movie.create(title: "Art Talent Show", year_id: 30)
    Movie.create(title: "Arthur the King", year_id: 30)
    Movie.create(title: "Arthur's Whisky", year_id: 30)
    Movie.create(title: "Article 370", year_id: 30)
    Movie.create(title: "Article 20", year_id: 30)
    Movie.create(title: "As We Speak", year_id: 30)
    Movie.create(title: "Asleep in My Palm", year_id: 30)
    Movie.create(title: "Asphalt City", year_id: 30)
    Movie.create(title: "Atlas", year_id: 30)
    Movie.create(title: "Attack of the Meth Gator", year_id: 30)
    Movie.create(title: "Auron Mein Kahan Dum Tha", year_id: 30)
    Movie.create(title: "Average Joe", year_id: 30)
    Movie.create(title: "Ayalaan", year_id: 30)
    Movie.create(title: "Azrael", year_id: 30)
    Movie.create(title: "Babes", year_id: 30)
    Movie.create(title: "Baby John", year_id: 30)
    Movie.create(title: "Babygirl", year_id: 30)
    Movie.create(title: "Babylicious", year_id: 30)
    Movie.create(title: "Bachhala Malli", year_id: 30)
    Movie.create(title: "Back Home", year_id: 30)
    Movie.create(title: "Back to Black", year_id: 30)
    Movie.create(title: "Backspot", year_id: 30)
    Movie.create(title: "Bad Actor: A Hollywood Ponzi Scheme", year_id: 30)
    Movie.create(title: "Bad Boys: Ride or Die", year_id: 30)
    Movie.create(title: "Bad Faith", year_id: 30)
    Movie.create(title: "Bad Genius", year_id: 30)
    Movie.create(title: "Bad Newz", year_id: 30)
    Movie.create(title: "Bad River", year_id: 30)
    Movie.create(title: "Bade Miyan Chote Miyan", year_id: 30)
    Movie.create(title: "Bagman", year_id: 30)
    Movie.create(title: "Banel & Adama", year_id: 30)
    Movie.create(title: "Bastar: The Naxal Story", year_id: 30)
    Movie.create(title: "The Bastard Sons", year_id: 30)
    Movie.create(title: "The Beach Boys", year_id: 30)
    Movie.create(title: "The Beast", year_id: 30)
    Movie.create(title: "The Beast Within", year_id: 30)
    Movie.create(title: "Beatles '64", year_id: 30)
    Movie.create(title: "The Beautiful Game", year_id: 30)
    Movie.create(title: "The Becomers", year_id: 30)
    Movie.create(title: "Becoming King", year_id: 30)
    Movie.create(title: "The Beekeeper", year_id: 30)
    Movie.create(title: "Beetlejuice Beetlejuice", year_id: 30)
    Movie.create(title: "The Best Christmas Pageant Ever", year_id: 30)
    Movie.create(title: "Better Man", year_id: 30)
    Movie.create(title: "Between the Temples", year_id: 30)
    Movie.create(title: "Beverly Hills Cop: Axel F", year_id: 30)
    Movie.create(title: "Beyond the Wall", year_id: 30)
    Movie.create(title: "Bhaje Vaayu Vegam", year_id: 30)
    Movie.create(title: "Bhimaa", year_id: 30)
    Movie.create(title: "Bhool Bhulaiyaa 3", year_id: 30)
    Movie.create(title: "Bhoothaddam Bhaskar Narayana", year_id: 30)
    Movie.create(title: "The Bibi Files", year_id: 30)
    Movie.create(title: "Big Boys", year_id: 30)
    Movie.create(title: "The Bikeriders", year_id: 30)
    Movie.create(title: "Bird", year_id: 30)
    Movie.create(title: "Black Barbie", year_id: 30)
    Movie.create(title: "Black Box Diaries", year_id: 30)
    Movie.create(title: "The Black Guelph", year_id: 30)
    Movie.create(title: "The Black Sea", year_id: 30)
    Movie.create(title: "Blackia 2", year_id: 30)
    Movie.create(title: "Blackout", year_id: 30)
    Movie.create(title: "Blackwater Lane", year_id: 30)
    Movie.create(title: "Bleeding Love", year_id: 30)
    Movie.create(title: "Blink", year_id: 30)
    Movie.create(title: "Blink Twice", year_id: 30)
    Movie.create(title: "Blitz", year_id: 30)
    Movie.create(title: "Blood for Dust", year_id: 30)
    Movie.create(title: "Bloodline Killer", year_id: 30)
    Movie.create(title: "Bloody Axe Wound", year_id: 30)
    Movie.create(title: "The Blue Angels", year_id: 30)
    Movie.create(title: "Blue Lock: Episode Nagi", year_id: 30)
    Movie.create(title: "The Blue Rose", year_id: 30)
    Movie.create(title: "The Blues Society", year_id: 30)
    Movie.create(title: "Bob Marley: One Love", year_id: 30)
    Movie.create(title: "The Body Politic", year_id: 30)
    Movie.create(title: "Bogart: Life Comes in Flashes", year_id: 30)
    Movie.create(title: "Boneyard", year_id: 30)
    Movie.create(title: "Bonhoeffer", year_id: 30)
    Movie.create(title: "Booger", year_id: 30)
    Movie.create(title: "The Book of Clarence", year_id: 30)
    Movie.create(title: "Bookworm", year_id: 30)
    Movie.create(title: "Boot Camp", year_id: 30)
    Movie.create(title: "Borderland | The Line Within", year_id: 30)
    Movie.create(title: "Borderlands", year_id: 30)
    Movie.create(title: "Boy Kills World", year_id: 30)
    Movie.create(title: "Brats", year_id: 30)
    Movie.create(title: "Bread & Roses", year_id: 30)
    Movie.create(title: "Break the Game", year_id: 30)
    Movie.create(title: "The Breaking Ice", year_id: 30)
    Movie.create(title: "Breathe", year_id: 30)
    Movie.create(title: "The Bricklayer", year_id: 30)
    Movie.create(title: "Brief Tender Light", year_id: 30)
    Movie.create(title: "Brother and Sister", year_id: 30)
    Movie.create(title: "Brothers", year_id: 30)
    Movie.create(title: "The Brutalist", year_id: 30)
    Movie.create(title: "The Buckingham Murders", year_id: 30)
    Movie.create(title: "Bull Street", year_id: 30)
    Movie.create(title: "Butterfly in the Sky", year_id: 30)
    Movie.create(title: "Bye Bye Tiberias", year_id: 30)
    Movie.create(title: "Cabrini", year_id: 30)
    Movie.create(title: "Captain Avispa", year_id: 30)
    Movie.create(title: "Captain Miller", year_id: 30)
    Movie.create(title: "Carol Doda Topless at The Condor", year_id: 30)
    Movie.create(title: "Carry-On", year_id: 30)
    Movie.create(title: "Carville: Winning Is Everything, Stupid", year_id: 30)
    Movie.create(title: "¡ Casa Bonita Mi Amor!", year_id: 30)
    Movie.create(title: "Cashing Out", year_id: 30)
    Movie.create(title: "Catching Dust", year_id: 30)
    Movie.create(title: "Catching Fire: The Story of Anita Pallenberg", year_id: 30)
    Movie.create(title: "Cellar Door", year_id: 30)
    Movie.create(title: "Cesium Fallout", year_id: 30)
    Movie.create(title: "Chaari 111", year_id: 30)
    Movie.create(title: "Challengers", year_id: 30)
    Movie.create(title: "Chandu Champion", year_id: 30)
    Movie.create(title: "Chasing Chasing Amy", year_id: 30)
    Movie.create(title: "Chestnut", year_id: 30)
    Movie.create(title: "Chhakka Panja 5", year_id: 30)
    Movie.create(title: "Chhota Bheem and the Curse of Damyaan", year_id: 30)
    Movie.create(title: "Chicken for Linda!", year_id: 30)
    Movie.create(title: "Chief of Station", year_id: 30)
    Movie.create(title: "The Chosen: Season 4 Episodes 1-3", year_id: 30)
    Movie.create(title: "The Chosen: Season 4 Episodes 4-6", year_id: 30)
    Movie.create(title: "The Chosen: Season 4 Episodes 7-8", year_id: 30)
    Movie.create(title: "Christmas Eve in Miller's Point", year_id: 30)
    Movie.create(title: "Christophe...Definitely", year_id: 30)
    Movie.create(title: "Chronicles of a Wandering Saint", year_id: 30)
    Movie.create(title: "Chuck Chuck Baby", year_id: 30)
    Movie.create(title: "Cinderella's Revenge", year_id: 30)
    Movie.create(title: "Cirque du Soleil: Without a Net", year_id: 30)
    Movie.create(title: "City of Dreams", year_id: 30)
    Movie.create(title: "Civil War", year_id: 30)
    Movie.create(title: "Clawfoot", year_id: 30)
    Movie.create(title: "Close to You", year_id: 30)
    Movie.create(title: "Close Your Eyes", year_id: 30)
    Movie.create(title: "Club Zero", year_id: 30)
    Movie.create(title: "Cobweb", year_id: 30)
    Movie.create(title: "Coconut Head Generation", year_id: 30)
    Movie.create(title: "Code 8: Part II", year_id: 30)
    Movie.create(title: "Colao 2", year_id: 30)
    Movie.create(title: "Cold Copy", year_id: 30)
    Movie.create(title: "Coma", year_id: 30)
    Movie.create(title: "The Commandant's Shadow", year_id: 30)
    Movie.create(title: "Commuted", year_id: 30)
    Movie.create(title: "A Complete Unknown", year_id: 30)
    Movie.create(title: "Conclave", year_id: 30)
    Movie.create(title: "Confessions of a Good Samaritan", year_id: 30)
    Movie.create(title: "Continue", year_id: 30)
    Movie.create(title: "The Convert", year_id: 30)
    Movie.create(title: "Copa 71", year_id: 30)
    Movie.create(title: "Cora Bora", year_id: 30)
    Movie.create(title: "Cottontail", year_id: 30)
    Movie.create(title: "The Count of Monte Cristo", year_id: 30)
    Movie.create(title: "Coup!", year_id: 30)
    Movie.create(title: "Coup de chance", year_id: 30)
    Movie.create(title: "The Cowboy and the Queen", year_id: 30)
    Movie.create(title: "Craak: Jeetega...Toh Jiyegaa", year_id: 30)
    Movie.create(title: "Creatura", year_id: 30)
    Movie.create(title: "Crew", year_id: 30)
    Movie.create(title: "Crisis Negotiators", year_id: 30)
    Movie.create(title: "The Critic", year_id: 30)
    Movie.create(title: "Critical Acclaim", year_id: 30)
    Movie.create(title: "The Crow", year_id: 30)
    Movie.create(title: "Crumb Catcher", year_id: 30)
    Movie.create(title: "Cuckoo", year_id: 30)
    Movie.create(title: "Cult Killer", year_id: 30)
    Movie.create(title: "Customs Frontline", year_id: 30)
    Movie.create(title: "Daaaaaalí!", year_id: 30)
    Movie.create(title: "Daddio", year_id: 30)
    Movie.create(title: "Dahomey", year_id: 30)
    Movie.create(title: "Damaged", year_id: 30)
    Movie.create(title: "Damsel", year_id: 30)
    Movie.create(title: "Dan Da Dan: First Encounter", year_id: 30)
    Movie.create(title: "Dance First", year_id: 30)
    Movie.create(title: "Dancing Village: The Curse Begins", year_id: 30)
    Movie.create(title: "Dandelion", year_id: 30)
    Movie.create(title: "Dard", year_id: 30)
    Movie.create(title: "Dario Argento Panico", year_id: 30)
    Movie.create(title: "Darla in Space", year_id: 30)
    Movie.create(title: "Darling", year_id: 30)
    Movie.create(title: "Daughters", year_id: 30)
    Movie.create(title: "Day of the Fight", year_id: 30)
    Movie.create(title: "Dayarani", year_id: 30)
    Movie.create(title: "Daytime Revolution", year_id: 30)
    Movie.create(title: "The Dead Don't Hurt", year_id: 30)
    Movie.create(title: "Dead Money", year_id: 30)
    Movie.create(title: "Dead Sea", year_id: 30)
    Movie.create(title: "Dead Whisper", year_id: 30)
    Movie.create(title: "Deadpool & Wolverine", year_id: 30)
    Movie.create(title: "Death Whisperer 2", year_id: 30)
    Movie.create(title: "Death Without Mercy", year_id: 30)
    Movie.create(title: "Decoded", year_id: 30)
    Movie.create(title: "The Deliverance", year_id: 30)
    Movie.create(title: "Demon Slayer: Kimetsu No Yaiba—To the Hashira Training", year_id: 30)
    Movie.create(title: "Desire Lines", year_id: 30)
    Movie.create(title: "Despicable Me 4", year_id: 30)
    Movie.create(title: "Destroy All Neighbors", year_id: 30)
    Movie.create(title: "Devara Part I", year_id: 30)
    Movie.create(title: "The Devil's Bath", year_id: 30)
    Movie.create(title: "Deyaler Desh", year_id: 30)
    Movie.create(title: "Diary of a Fleeting Affair", year_id: 30)
    Movie.create(title: "Dìdi", year_id: 30)
    Movie.create(title: "A Different Man", year_id: 30)
    Movie.create(title: "Director's Cut", year_id: 30)
    Movie.create(title: "Dirty Angels", year_id: 30)
    Movie.create(title: "Disco Boy", year_id: 30)
    Movie.create(title: "Do Aur Do Pyaar", year_id: 30)
    Movie.create(title: "Do Not Expect Too Much From the End of the World", year_id: 30)
    Movie.create(title: "DogMan", year_id: 30)
    Movie.create(title: "Dominique", year_id: 30)
    Movie.create(title: "Don't Tell Mom the Babysitter's Dead", year_id: 30)
    Movie.create(title: "Double iSmart", year_id: 30)
    Movie.create(title: "Dragonkeeper", year_id: 30)
    Movie.create(title: "The Dream and the Radio", year_id: 30)
    Movie.create(title: "Dream Team", year_id: 30)
    Movie.create(title: "Drift", year_id: 30)
    Movie.create(title: "Drive-Away Dolls", year_id: 30)
    Movie.create(title: "Driving Madeleine", year_id: 30)
    Movie.create(title: "Drugstore June", year_id: 30)
    Movie.create(title: "Dune: Part Two", year_id: 30)
    Movie.create(title: "Eagle", year_id: 30)
    Movie.create(title: "East Bay", year_id: 30)
    Movie.create(title: "Egoist", year_id: 30)
    Movie.create(title: "El Harifa", year_id: 30)
    Movie.create(title: "El Hawa Sultan", year_id: 30)
    Movie.create(title: "Electric Lady Studios: A Jimi Hendrix Vision", year_id: 30)
    Movie.create(title: "Elevation", year_id: 30)
    Movie.create(title: "Elizabeth Taylor: The Lost Tapes", year_id: 30)
    Movie.create(title: "Elton John: Never Too Late", year_id: 30)
    Movie.create(title: "Emilia Pérez", year_id: 30)
    Movie.create(title: "The End", year_id: 30)
    Movie.create(title: "Endless Summer Syndrome", year_id: 30)
    Movie.create(title: "Eno", year_id: 30)
    Movie.create(title: "Epic Tails", year_id: 30)
    Movie.create(title: "Ernest Cole: Lost and Found", year_id: 30)
    Movie.create(title: "Escape", year_id: 30)
    Movie.create(title: "Escape From Extinction Rewilding", year_id: 30)
    Movie.create(title: "Eureka", year_id: 30)
    Movie.create(title: "Evil Does Not Exist", year_id: 30)
    Movie.create(title: "Exhibiting Forgiveness", year_id: 30)
    Movie.create(title: "Exhuma", year_id: 30)
    Movie.create(title: "The Exorcism", year_id: 30)
    Movie.create(title: "Ezra", year_id: 30)
    Movie.create(title: "The Fabulous Four", year_id: 30)
    Movie.create(title: "The Face of the Jellyfish", year_id: 30)
    Movie.create(title: "Face Off 7: One Wish", year_id: 30)
    Movie.create(title: "Fairytale", year_id: 30)
    Movie.create(title: "The Fall Guy.", year_id: 30)
    Movie.create(title: "The Falling Star", year_id: 30)
    Movie.create(title: "A Family Affair", year_id: 30)
    Movie.create(title: "Family Pack", year_id: 30)
    Movie.create(title: "Family Portrait", year_id: 30)
    Movie.create(title: "The Family Star", year_id: 30)
    Movie.create(title: "Fanatical: The Catfishing of Tegan and Sara", year_id: 30)
    Movie.create(title: "Fancy Dance", year_id: 30)
    Movie.create(title: "Fanmade: ENHYPEN", year_id: 30)
    Movie.create(title: "Fasel Men El Lahazat El Lazeeza", year_id: 30)
    Movie.create(title: "The Featherweight", year_id: 30)
    Movie.create(title: "Federer: Twelve Final Days", year_id: 30)
    Movie.create(title: "The Feeling That the Time for Doing Something Has Passed", year_id: 30)
    Movie.create(title: "Femme", year_id: 30)
    Movie.create(title: "Fighter", year_id: 30)
    Movie.create(title: "Fighting Spirit: A Combat Chaplain's Journey", year_id: 30)
    Movie.create(title: "Film Geek", year_id: 30)
    Movie.create(title: "Find Me Falling", year_id: 30)
    Movie.create(title: "Finding the Money", year_id: 30)
    Movie.create(title: "The Fire Inside", year_id: 30)
    Movie.create(title: "Firebrand", year_id: 30)
    Movie.create(title: "The Firing Squad", year_id: 30)
    Movie.create(title: "The First Omen", year_id: 30)
    Movie.create(title: "Fitting In", year_id: 30)
    Movie.create(title: "5LBs of Pressure", year_id: 30)
    Movie.create(title: "Flight 404", year_id: 30)
    Movie.create(title: "Flipside", year_id: 30)
    Movie.create(title: "Float", year_id: 30)
    Movie.create(title: "Flow", year_id: 30)
    Movie.create(title: "Fly Me to the Moon", year_id: 30)
    Movie.create(title: "Food and Country", year_id: 30)
    Movie.create(title: "Food Inc. 2", year_id: 30)
    Movie.create(title: "Force of Nature: The Dry 2", year_id: 30)
    Movie.create(title: "The Forge", year_id: 30)
    Movie.create(title: "Forgetting the Many: The Royal Pardon of Alan Turing", year_id: 30)
    Movie.create(title: "Founders Day", year_id: 30)
    Movie.create(title: "Four Souls of Coyote", year_id: 30)
    Movie.create(title: "The 4:30 Movie", year_id: 30)
    Movie.create(title: "A Fragile Flower", year_id: 30)
    Movie.create(title: "Frank Capra: Mr America", year_id: 30)
    Movie.create(title: "Frankie Freako", year_id: 30)
    Movie.create(title: "Freddy", year_id: 30)
    Movie.create(title: "Free Time", year_id: 30)
    Movie.create(title: "French Girl", year_id: 30)
    Movie.create(title: "Fresh Kills", year_id: 30)
    Movie.create(title: "From Embers", year_id: 30)
    Movie.create(title: "The Front Room", year_id: 30)
    Movie.create(title: "Furiosa: A Mad Max Saga", year_id: 30)
    Movie.create(title: "G for Gap", year_id: 30)
    Movie.create(title: "Gaami", year_id: 30)
    Movie.create(title: "Gabru Gang", year_id: 30)
    Movie.create(title: "Gangs of Godavari", year_id: 30)
    Movie.create(title: "The Garfield Movie", year_id: 30)
    Movie.create(title: "Garudan", year_id: 30)
    Movie.create(title: "Gasoline Rainbow", year_id: 30)
    Movie.create(title: "The Geechee Witch: A Boo Hag Story", year_id: 30)
    Movie.create(title: "Geoff McFetridge: Drawing a Life", year_id: 30)
    Movie.create(title: "Get Away", year_id: 30)
    Movie.create(title: "Getting It Back: The Story of Cymande", year_id: 30)
    Movie.create(title: "Ghost Cat Anzu", year_id: 30)
    Movie.create(title: "Ghostbusters: Frozen Empire", year_id: 30)
    Movie.create(title: "Ghostlight", year_id: 30)
    Movie.create(title: "The Girl With the Needle", year_id: 30)
    Movie.create(title: "Girl, You Know It's True", year_id: 30)
    Movie.create(title: "Girls State", year_id: 30)
    Movie.create(title: "Girls Will Be Girls", year_id: 30)
    Movie.create(title: "GladIIator", year_id: 30)
    Movie.create(title: "Glitter & Doom", year_id: 30)
    Movie.create(title: "Go for Broke", year_id: 30)
    Movie.create(title: "The Goat Life", year_id: 30)
    Movie.create(title: "God & Country", year_id: 30)
    Movie.create(title: "God's Not Dead: In God We Trust", year_id: 30)
    Movie.create(title: "Godzilla x Kong: The New Empire", year_id: 30)
    Movie.create(title: "Golden Years", year_id: 30)
    Movie.create(title: "Goldilocks and the Two Bears", year_id: 30)
    Movie.create(title: "The Goldman Case", year_id: 30)
    Movie.create(title: "The Good Half", year_id: 30)
    Movie.create(title: "Good One", year_id: 30)
    Movie.create(title: "Goodrich", year_id: 30)
    Movie.create(title: "The Grab", year_id: 30)
    Movie.create(title: "Gracie and Pedro: Pets to the Rescue!", year_id: 30)
    Movie.create(title: "The Graduates", year_id: 30)
    Movie.create(title: "Great Absence", year_id: 30)
    Movie.create(title: "The Great Lillian Hall", year_id: 30)
    Movie.create(title: "The Great Warning", year_id: 30)
    Movie.create(title: "The Greatest Hits", year_id: 30)
    Movie.create(title: "The Greatest Night in Pop", year_id: 30)
    Movie.create(title: "The Greatest of All Time", year_id: 30)
    Movie.create(title: "The Greatest Surf Movie in the Universe", year_id: 30)
    Movie.create(title: "Greedy People", year_id: 30)
    Movie.create(title: "Green Border", year_id: 30)
    Movie.create(title: "Guadalupe: Mother of Humanity", year_id: 30)
    Movie.create(title: "Guest From the Future", year_id: 30)
    Movie.create(title: "Gunner", year_id: 30)
    Movie.create(title: "Guntur Kaaram", year_id: 30)
    Movie.create(title: "The Gutter Haikyuu!! The Dumpster Battle", year_id: 30)
    Movie.create(title: "Handling the Undead", year_id: 30)
    Movie.create(title: "Handsome Guys", year_id: 30)
    Movie.create(title: "Hanu Man", year_id: 30)
    Movie.create(title: "Happy Campers", year_id: 30)
    Movie.create(title: "Happy Clothes: A Film About Patricia Field", year_id: 30)
    Movie.create(title: "Hard Miles", year_id: 30)
    Movie.create(title: "Hard Truths", year_id: 30)
    Movie.create(title: "Harold and the Purple Crayon", year_id: 30)
    Movie.create(title: "He Went That Way", year_id: 30)
    Movie.create(title: "The Heart Stays", year_id: 30)
    Movie.create(title: "Heavier Trip", year_id: 30)
    Movie.create(title: "Hello, Love, Again", year_id: 30)
    Movie.create(title: "Her Story", year_id: 30)
    Movie.create(title: "Here (Bas Devos)", year_id: 30)
    Movie.create(title: "Here (Robert Zemeckis)", year_id: 30)
    Movie.create(title: "Here After", year_id: 30)
    Movie.create(title: "Heretic", year_id: 30)
    Movie.create(title: "Hidden Master: The Legacy of George Platt Lynes", year_id: 30)
    Movie.create(title: "High & Low: John Galliano", year_id: 30)
    Movie.create(title: "High Forces", year_id: 30)
    Movie.create(title: "High Tide", year_id: 30)
    Movie.create(title: "Hijack 1971", year_id: 30)
    Movie.create(title: "A Hip Hop Story", year_id: 30)
    Movie.create(title: "Hippo", year_id: 30)
    Movie.create(title: "His Three Daughters", year_id: 30)
    Movie.create(title: "Hit Man", year_id: 30)
    Movie.create(title: "Hitpig!", year_id: 30)
    Movie.create(title: "Hoard", year_id: 30)
    Movie.create(title: "Holding Back the Tide", year_id: 30)
    Movie.create(title: "Hollywoodgate", year_id: 30)
    Movie.create(title: "Home Education", year_id: 30)
    Movie.create(title: "Homegrown", year_id: 30)
    Movie.create(title: "Homestead", year_id: 30)
    Movie.create(title: "The Honest Candidate", year_id: 30)
    Movie.create(title: "Horizon: An American Saga—Chapter 1", year_id: 30)
    Movie.create(title: "Hot Frosty", year_id: 30)
    Movie.create(title: "Housekeeping for Beginners", year_id: 30)
    Movie.create(title: "Hovering Blade", year_id: 30)
    Movie.create(title: "How to Come Alive With Norman Mailer", year_id: 30)
    Movie.create(title: "How to Have Sex", year_id: 30)
    Movie.create(title: "How to Make Millions Before Grandma Dies", year_id: 30)
    Movie.create(title: "Hubba", year_id: 30)
    Movie.create(title: "The Human Surge 3", year_id: 30)
    Movie.create(title: "Humane", year_id: 30)
    Movie.create(title: "Humanist Vampire Seeking Consenting Suicidal Person", year_id: 30)
    Movie.create(title: "Hummingbirds", year_id: 30)
    Movie.create(title: "Hundreds of Beavers", year_id: 30)
    Movie.create(title: "The Hunted", year_id: 30)
    Movie.create(title: "I Am: Celine Dion", year_id: 30)
    Movie.create(title: "I Am Gitmo", year_id: 30)
    Movie.create(title: "I Did It My Way", year_id: 30)
    Movie.create(title: "I Don't Know Who You Are", year_id: 30)
    Movie.create(title: "I Like It Here", year_id: 30)
    Movie.create(title: "I Like Movies", year_id: 30)
    Movie.create(title: "I Love You, to the Moon, and Back", year_id: 30)
    Movie.create(title: "I Saw the TV Glow", year_id: 30)
    Movie.create(title: "I, the Executioner", year_id: 30)
    Movie.create(title: "I Used to Be Funny", year_id: 30)
    Movie.create(title: "Ice 3", year_id: 30)
    Movie.create(title: "The Idea of You", year_id: 30)
    Movie.create(title: "IF", year_id: 30)
    Movie.create(title: "If You Are the One III", year_id: 30)
    Movie.create(title: "I'll Be Right There", year_id: 30)
    Movie.create(title: "I'll Be Your Mirror", year_id: 30)
    Movie.create(title: "I'm Still Here", year_id: 30)
    Movie.create(title: "Imaginary", year_id: 30)
    Movie.create(title: "The Imaginary", year_id: 30)
    Movie.create(title: "Immaculate", year_id: 30)
    Movie.create(title: "In a Violent Nature", year_id: 30)
    Movie.create(title: "In Flames", year_id: 30)
    Movie.create(title: "In Our Day", year_id: 30)
    Movie.create(title: "In the Land of Saints and Sinners", year_id: 30)
    Movie.create(title: "In the Rearview", year_id: 30)
    Movie.create(title: "In the Summers", year_id: 30)
    Movie.create(title: "Incoming", year_id: 30)
    Movie.create(title: "Indian 2", year_id: 30)
    Movie.create(title: "Indigo Girls: It's Only Life After All", year_id: 30)
    Movie.create(title: "Infested", year_id: 30)
    Movie.create(title: "The Inheritance", year_id: 30)
    Movie.create(title: "Inshallah a Boy", year_id: 30)
    Movie.create(title: "Inside Out 2", year_id: 30)
    Movie.create(title: "Inside the Yellow Cocoon Shell", year_id: 30)
    Movie.create(title: "The Instigators", year_id: 30)
    Movie.create(title: "Intercepted", year_id: 30)
    Movie.create(title: "The Invisible Fight", year_id: 30)
    Movie.create(title: "Invisible Nation", year_id: 30)
    Movie.create(title: "Io capitano", year_id: 30)
    Movie.create(title: "IRaH", year_id: 30)
    Movie.create(title: "Irish Wish", year_id: 30)
    Movie.create(title: "I.S.S.", year_id: 30)
    Movie.create(title: "It Ends With Us", year_id: 30)
    Movie.create(title: "It's What's Inside", year_id: 30)
    Movie.create(title: "Jackpot!", year_id: 30)
    Movie.create(title: "Jamie Wyeth and the Unflinching Eye", year_id: 30)
    Movie.create(title: "Janet Planet", year_id: 30)
    Movie.create(title: "Jeanne du Barry", year_id: 30)
    Movie.create(title: "Jeonde Raho Bhoot Ji", year_id: 30)
    Movie.create(title: "Jigra", year_id: 30)
    Movie.create(title: "Jim Henson: Idea Man", year_id: 30)
    Movie.create(title: "Johnny Keep Walking!", year_id: 30)
    Movie.create(title: "Join or Die", year_id: 30)
    Movie.create(title: "Joker: Folie à Deux", year_id: 30)
    Movie.create(title: "Joy", year_id: 30)
    Movie.create(title: "June", year_id: 30)
    Movie.create(title: "June Zero", year_id: 30)
    Movie.create(title: "The Jungle Bunch: Operation Meltdown", year_id: 30)
    Movie.create(title: "Juror #2", year_id: 30)
    Movie.create(title: "Just the Two of Us", year_id: 30)
    Movie.create(title: "Kadaisi Ulaga Por", year_id: 30)
    Movie.create(title: "Kahan Shuru Kahan Khatam", year_id: 30)
    Movie.create(title: "Kalki 2898—A.D", year_id: 30)
    Movie.create(title: "Kanguva", year_id: 30)
    Movie.create(title: "Karaoke", year_id: 30)
    Movie.create(title: "Khel Khel Mein", year_id: 30)
    Movie.create(title: "Kidnapped", year_id: 30)
    Movie.create(title: "Kill", year_id: 30)
    Movie.create(title: "The Killer", year_id: 30)
    Movie.create(title: "Killer Heat", year_id: 30)
    Movie.create(title: "The Killer's Game", year_id: 30)
    Movie.create(title: "Kim's Video", year_id: 30)
    Movie.create(title: "Kinds of Kindness", year_id: 30)
    Movie.create(title: "The King Tide", year_id: 30)
    Movie.create(title: "Kingdom of the Planet of the Apes", year_id: 30)
    Movie.create(title: "Kiss the Future", year_id: 30)
    Movie.create(title: "The Kitchen", year_id: 30)
    Movie.create(title: "Kneecap", year_id: 30)
    Movie.create(title: "Knox Goes Away", year_id: 30)
    Movie.create(title: "Kraven the Hunter", year_id: 30)
    Movie.create(title: "Kudi Haryane Val Di", year_id: 30)
    Movie.create(title: "Kung Fu Panda 4", year_id: 30)
    Movie.create(title: "La cocina", year_id: 30)
    Movie.create(title: "Laggam", year_id: 30)
    Movie.create(title: "Lake George", year_id: 30)
    Movie.create(title: "Lal Salaam", year_id: 30)
    Movie.create(title: "Lambran Da Laana", year_id: 30)
    Movie.create(title: "Land of Bad", year_id: 30)
    Movie.create(title: "Land of Broken Hearts", year_id: 30)
    Movie.create(title: "Land of Happiness", year_id: 30)
    Movie.create(title: "Larger Than Life: Reign of the Boybands", year_id: 30)
    Movie.create(title: "The Last Breath", year_id: 30)
    Movie.create(title: "The Last Dance", year_id: 30)
    Movie.create(title: "The Last Frenzy", year_id: 30)
    Movie.create(title: "The Last Front", year_id: 30)
    Movie.create(title: "The Last of the Sea Women", year_id: 30)
    Movie.create(title: "The Last Redemption", year_id: 30)
    Movie.create(title: "The Last Rifleman", year_id: 30)
    Movie.create(title: "The Last Stop in Yuma County", year_id: 30)
    Movie.create(title: "Last Summer", year_id: 30)
    Movie.create(title: "Last Things", year_id: 30)
    Movie.create(title: "Late Bloomers", year_id: 30)
    Movie.create(title: "Late Night With the Devil", year_id: 30)
    Movie.create(title: "Latency", year_id: 30)
    Movie.create(title: "Lazareth", year_id: 30)
    Movie.create(title: "Leap of Faith", year_id: 30)
    Movie.create(title: "Lee", year_id: 30)
    Movie.create(title: "Leila's Brothers", year_id: 30)
    Movie.create(title: "Let Them Breathe: City on the Ocean", year_id: 30)
    Movie.create(title: "Let's Start a Cult", year_id: 30)
    Movie.create(title: "Life After Fighting", year_id: 30)
    Movie.create(title: "Life Hotel", year_id: 30)
    Movie.create(title: "Lift", year_id: 30)
    Movie.create(title: "Light", year_id: 30)
    Movie.create(title: "Lil Nas X: Long Live Montero", year_id: 30)
    Movie.create(title: "Limbo", year_id: 30)
    Movie.create(title: "The Line (Ethan Berger)", year_id: 30)
    Movie.create(title: "The Line (Ursula Meier)", year_id: 30)
    Movie.create(title: "Lisa Frankenstein", year_id: 30)
    Movie.create(title: "The Listener", year_id: 30)
    Movie.create(title: "Little Empty Boxes", year_id: 30)
    Movie.create(title: "The Lives of Infamous Men", year_id: 30)
    Movie.create(title: "Lola", year_id: 30)
    Movie.create(title: "Lonely Planet", year_id: 30)
    Movie.create(title: "The Long Game", year_id: 30)
    Movie.create(title: "Long Gone Heroes", year_id: 30)
    Movie.create(title: "Longing", year_id: 30)
    Movie.create(title: "Longlegs", year_id: 30)
    Movie.create(title: "Look Back", year_id: 30)
    Movie.create(title: "Look Into My Eyes", year_id: 30)
    Movie.create(title: "The Lord of the Rings: The War of the Rohirrim", year_id: 30)
    Movie.create(title: "Los Frikis", year_id: 30)
    Movie.create(title: "Losing Faith", year_id: 30)
    Movie.create(title: "Lost Angel: The Genius of Judee Sill", year_id: 30)
    Movie.create(title: "The Lost Boys", year_id: 30)
    Movie.create(title: "The Lost Holliday", year_id: 30)
    Movie.create(title: "Lost Ladies", year_id: 30)
    Movie.create(title: "Lost on a Mountain in Maine", year_id: 30)
    Movie.create(title: "Lousy Carter", year_id: 30)
    Movie.create(title: "Love Lies", year_id: 30)
    Movie.create(title: "Love Lies Bleeding", year_id: 30)
    Movie.create(title: "Love Me if You Dare!", year_id: 30)
    Movie.create(title: "Lover", year_id: 30)
    Movie.create(title: "Lover of Men. The Untold History of Abraham Lincoln", year_id: 30)
    Movie.create(title: "Lover, Stalker, Killer", year_id: 30)
    Movie.create(title: "Lucky Baskhar", year_id: 30)
    Movie.create(title: "Lullaby", year_id: 30)
    Movie.create(title: "Lumberjack the Monster", year_id: 30)
    Movie.create(title: "Lumina", year_id: 30)
    Movie.create(title: "Luther: Never Too Much", year_id: 30)
    Movie.create(title: "Mad About the Boy: The Noël Coward Story", year_id: 30)
    Movie.create(title: "Madame Web", year_id: 30)
    Movie.create(title: "Made in England: The Films of Powell and Pressburger", year_id: 30)
    Movie.create(title: "Madgaon Express", year_id: 30)
    Movie.create(title: "MadS", year_id: 30)
    Movie.create(title: "Maestra", year_id: 30)
    Movie.create(title: "Magpie", year_id: 30)
    Movie.create(title: "Mai", year_id: 30)
    Movie.create(title: "Maidaan", year_id: 30)
    Movie.create(title: "Majority Rules", year_id: 30)
    Movie.create(title: "Malaikottai Vaaliban", year_id: 30)
    Movie.create(title: "Mallari", year_id: 30)
    Movie.create(title: "Mambar Pierrette", year_id: 30)
    Movie.create(title: "The Man in the White Van", year_id: 30)
    Movie.create(title: "Mansarra", year_id: 30)
    Movie.create(title: "Maria", year_id: 30)
    Movie.create(title: "Marmalade", year_id: 30)
    Movie.create(title: "Mars Express", year_id: 30)
    Movie.create(title: "Martha", year_id: 30)
    Movie.create(title: "Maruthi Nagar Subramanyam", year_id: 30)
    Movie.create(title: "Mary", year_id: 30)
    Movie.create(title: "Mathu Vadalara 2", year_id: 30)
    Movie.create(title: "Matt and Mara", year_id: 30)
    Movie.create(title: "MaXXXine", year_id: 30)
    Movie.create(title: "Maya and the Wave", year_id: 30)
    Movie.create(title: "Mayhem!", year_id: 30)
    Movie.create(title: "Mea Culpa", year_id: 30)
    Movie.create(title: "Mean Girls", year_id: 30)
    Movie.create(title: "Meanwhile on Earth", year_id: 30)
    Movie.create(title: "Mediha", year_id: 30)
    Movie.create(title: "Mediterranean Fever", year_id: 30)
    Movie.create(title: "Meet Me Next Christmas", year_id: 30)
    Movie.create(title: "Megalopolis", year_id: 30)
    Movie.create(title: "Meiyazhagan", year_id: 30)
    Movie.create(title: "Memoir of a Snail", year_id: 30)
    Movie.create(title: "The Menendez Brothers", year_id: 30)
    Movie.create(title: "Merchant | Ivory", year_id: 30)
    Movie.create(title: "The Middle Ages", year_id: 30)
    Movie.create(title: "Miller’s Girl", year_id: 30)
    Movie.create(title: "Millers in Marriage", year_id: 30)
    Movie.create(title: "Mind Wave", year_id: 30)
    Movie.create(title: "The Ministry of Ungentlemanly Warfare", year_id: 30)
    Movie.create(title: "A Mistake", year_id: 30)
    Movie.create(title: "Mr. & Mrs. Mahi", year_id: 30)
    Movie.create(title: "Mr. Bachchan", year_id: 30)
    Movie.create(title: "Moana 2", year_id: 30)
    Movie.create(title: "Modernism, Inc.: The Eliot Noyes Design Story", year_id: 30)
    Movie.create(title: "Molli and Max in the Future", year_id: 30)
    Movie.create(title: "The Monk and the Gun", year_id: 30)
    Movie.create(title: "Monkey Man", year_id: 30)
    Movie.create(title: "Monolith", year_id: 30)
    Movie.create(title: "Mononoke the Movie: The Phantom in the Rain", year_id: 30)
    Movie.create(title: "Monster Summer", year_id: 30)
    Movie.create(title: "The Moon Thieves", year_id: 30)
    Movie.create(title: "Mother and Son", year_id: 30)
    Movie.create(title: "Mother, Couch", year_id: 30)
    Movie.create(title: "The Mother of All Lies", year_id: 30)
    Movie.create(title: "Mother of the Bride", year_id: 30)
    Movie.create(title: "Mothers' Instinct", year_id: 30)
    Movie.create(title: "Mountains", year_id: 30)
    Movie.create(title: "Mourning in Lod", year_id: 30)
    Movie.create(title: "The Movie Emperor", year_id: 30)
    Movie.create(title: "MoviePass, MovieCrash", year_id: 30)
    Movie.create(title: "Much Ado About Dying", year_id: 30)
    Movie.create(title: "Mufasa: The Lion King", year_id: 30)
    Movie.create(title: "Munjya", year_id: 30)
    Movie.create(title: "Music", year_id: 30)
    Movie.create(title: "Music by John Williams", year_id: 30)
    Movie.create(title: "Music for Mushrooms", year_id: 30)
    Movie.create(title: "Música", year_id: 30)
    Movie.create(title: "My First Film", year_id: 30)
    Movie.create(title: "My Hero Academia: You're Next", year_id: 30)
    Movie.create(title: "My Name Is Alfred Hitchcock", year_id: 30)
    Movie.create(title: "My Old Ass", year_id: 30)
    Movie.create(title: "My Penguin Friend", year_id: 30)
    Movie.create(title: "My Spy: The Eternal City", year_id: 30)
    Movie.create(title: "Nadikar", year_id: 30)
    Movie.create(title: "Nathan-ism", year_id: 30)
    Movie.create(title: "National Anthem", year_id: 30)
    Movie.create(title: "The Natural History of Destruction", year_id: 30)
    Movie.create(title: "The Nature of Love", year_id: 30)
    Movie.create(title: "Nature of the Crime", year_id: 30)
    Movie.create(title: "Nayab", year_id: 30)
    Movie.create(title: "Negative Path", year_id: 30)
    Movie.create(title: "Never Let Go", year_id: 30)
    Movie.create(title: "Never Look Away", year_id: 30)
    Movie.create(title: "A New Kind of Wilderness", year_id: 30)
    Movie.create(title: "New Wave", year_id: 30)
    Movie.create(title: "A New York Story", year_id: 30)
    Movie.create(title: "Nickel Boys", year_id: 30)
    Movie.create(title: "Night Is Not Eternal", year_id: 30)
    Movie.create(title: "Night Swim", year_id: 30)
    Movie.create(title: "Nightbitch", year_id: 30)
    Movie.create(title: "1992", year_id: 30)
    Movie.create(title: "No Other Land", year_id: 30)
    Movie.create(title: "No Way Up", year_id: 30)
    Movie.create(title: "Nocturnes", year_id: 30)
    Movie.create(title: "Noryang: Deadly Sea", year_id: 30)
    Movie.create(title: "Nosferatu", year_id: 30)
    Movie.create(title: "Not Another Church Movie", year_id: 30)
    Movie.create(title: "Nothing Can't Be Undone by a HotPot", year_id: 30)
    Movie.create(title: "Notice to Quit", year_id: 30)
    Movie.create(title: "Nurse Unseen", year_id: 30)
    Movie.create(title: "Nutcrackers", year_id: 30)
    Movie.create(title: "Obsessed With Light", year_id: 30)
    Movie.create(title: "Oddity", year_id: 30)
    Movie.create(title: "Oh, Canada", year_id: 30)
    Movie.create(title: "The Old Oak", year_id: 30)
    Movie.create(title: "Om Bheem Bush", year_id: 30)
    Movie.create(title: "Omar", year_id: 30)
    Movie.create(title: "Omen", year_id: 30)
    Movie.create(title: "Omni Loop", year_id: 30)
    Movie.create(title: "On the Adamant", year_id: 30)
    Movie.create(title: "Once Again (For the Very First Time)", year_id: 30)
    Movie.create(title: "One Life", year_id: 30)
    Movie.create(title: "1 Million Followers", year_id: 30)
    Movie.create(title: "One With the Whale", year_id: 30)
    Movie.create(title: "Onlookers", year_id: 30)
    Movie.create(title: "Only the River Flows", year_id: 30)
    Movie.create(title: "Ooru Peru Bhairavakona", year_id: 30)
    Movie.create(title: "Operation Valentine", year_id: 30)
    Movie.create(title: "The Order", year_id: 30)
    Movie.create(title: "Ordinary Angels", year_id: 30)
    Movie.create(title: "Oscar-Nominated Shorts 2024: Animation", year_id: 30)
    Movie.create(title: "Oscar-Nominated Shorts 2024: Documentary (Prog A)", year_id: 30)
    Movie.create(title: "Oscar-Nominated Shorts 2024: Documentary (Prog B)", year_id: 30)
    Movie.create(title: "Oscar-Nominated Shorts 2024: Live-Action", year_id: 30)
    Movie.create(title: "Out Come the Wolves", year_id: 30)
    Movie.create(title: "Out of Darkness", year_id: 30)
    Movie.create(title: "Out of My Mind", year_id: 30)
    Movie.create(title: "Outbreak", year_id: 30)
    Movie.create(title: "Outlaw Posse", year_id: 30)
    Movie.create(title: "The Outrun", year_id: 30)
    Movie.create(title: "Outstanding: A Comedy Revolution", year_id: 30)
    Movie.create(title: "Overlord: The Sacred Kingdom", year_id: 30)
    Movie.create(title: "The Painted", year_id: 30)
    Movie.create(title: "Panda Plan", year_id: 30)
    Movie.create(title: "Parachute", year_id: 30)
    Movie.create(title: "Paradise Is Burning", year_id: 30)
    Movie.create(title: "The Paragon", year_id: 30)
    Movie.create(title: "Parahuna 2", year_id: 30)
    Movie.create(title: "Parallel", year_id: 30)
    Movie.create(title: "Pasang: In the Shadow of Everest", year_id: 30)
    Movie.create(title: "Pastor's Kid", year_id: 30)
    Movie.create(title: "Patrice: The Movie", year_id: 30)
    Movie.create(title: "Peak Season", year_id: 30)
    Movie.create(title: "Pedro Páramo", year_id: 30)
    Movie.create(title: "Pegasus 2", year_id: 30)
    Movie.create(title: "The People's Joker", year_id: 30)
    Movie.create(title: "Peppa’s Cinema Party", year_id: 30)
    Movie.create(title: "Photographic Justice: The Corky Lee Story", year_id: 30)
    Movie.create(title: "A Photographic Memory", year_id: 30)
    Movie.create(title: "The Piano Lesson", year_id: 30)
    Movie.create(title: "Pictures of Ghosts", year_id: 30)
    Movie.create(title: "Piece by Piece", year_id: 30)
    Movie.create(title: "Pilot", year_id: 30)
    Movie.create(title: "A Place Called Silence", year_id: 30)
    Movie.create(title: "Plastic", year_id: 30)
    Movie.create(title: "Players", year_id: 30)
    Movie.create(title: "Political War", year_id: 30)
    Movie.create(title: "Poolman", year_id: 30)
    Movie.create(title: "Poppay Ki Wedding", year_id: 30)
    Movie.create(title: "Popular Theory", year_id: 30)
    Movie.create(title: "Porcelain War", year_id: 30)
    Movie.create(title: "Pottel", year_id: 30)
    Movie.create(title: "Power", year_id: 30)
    Movie.create(title: "Power Alley", year_id: 30)
    Movie.create(title: "The Prank", year_id: 30)
    Movie.create(title: "Premalu", year_id: 30)
    Movie.create(title: "Prey", year_id: 30)
    Movie.create(title: "A Prince", year_id: 30)
    Movie.create(title: "The Private Eye", year_id: 30)
    Movie.create(title: "Problemista", year_id: 30)
    Movie.create(title: "Project Silence", year_id: 30)
    Movie.create(title: "The Promised Land", year_id: 30)
    Movie.create(title: "Property", year_id: 30)
    Movie.create(title: "Protocol 7", year_id: 30)
    Movie.create(title: "The Punishment", year_id: 30)
    Movie.create(title: "Pushpa 2: The Rule", year_id: 30)
    Movie.create(title: "Queen of the Deuce", year_id: 30)
    Movie.create(title: "Queendom", year_id: 30)
    Movie.create(title: "Queens", year_id: 30)
    Movie.create(title: "Queer", year_id: 30)
    Movie.create(title: "A Quiet Place: Day One", year_id: 30)
    Movie.create(title: "Raadjahani Files", year_id: 30)
    Movie.create(title: "Raayan", year_id: 30)
    Movie.create(title: "Race for Glory: Audi vs. Lancia", year_id: 30)
    Movie.create(title: "The Radleys", year_id: 30)
    Movie.create(title: "Rajkumar", year_id: 30)
    Movie.create(title: "Rap World", year_id: 30)
    Movie.create(title: "Rathnam", year_id: 30)
    Movie.create(title: "Reagan", year_id: 30)
    Movie.create(title: "A Real Pain", year_id: 30)
    Movie.create(title: "Rebel Moon Part Two: The Scargiver", year_id: 30)
    Movie.create(title: "Rebel Ridge", year_id: 30)
    Movie.create(title: "Red Island", year_id: 30)
    Movie.create(title: "Red One", year_id: 30)
    Movie.create(title: "Red Rooms", year_id: 30)
    Movie.create(title: "Refuge", year_id: 30)
    Movie.create(title: "Regarding Us", year_id: 30)
    Movie.create(title: "The Relentless Patriot", year_id: 30)
    Movie.create(title: "The Remarkable Life of Ibelin", year_id: 30)
    Movie.create(title: "Remembering Gene Wilder", year_id: 30)
    Movie.create(title: "Resistance: They Fought Back", year_id: 30)
    Movie.create(title: "The Return", year_id: 30)
    Movie.create(title: "re:Uniting", year_id: 30)
    Movie.create(title: "Reverse the Curse", year_id: 30)
    Movie.create(title: "A Revolution on Canvas", year_id: 30)
    Movie.create(title: "Rewind", year_id: 30)
    Movie.create(title: "Rez Ball", year_id: 30)
    Movie.create(title: "Rhinegold", year_id: 30)
    Movie.create(title: "Ricky Stanicky", year_id: 30)
    Movie.create(title: "Ride", year_id: 30)
    Movie.create(title: "Riddle of Fire", year_id: 30)
    Movie.create(title: "RM: Right People, Wrong Place", year_id: 30)
    Movie.create(title: "Road Diary", year_id: 30)
    Movie.create(title: "Road House", year_id: 30)
    Movie.create(title: "A Road to a Village", year_id: 30)
    Movie.create(title: "Rob & Roll", year_id: 30)
    Movie.create(title: "Rob Peace", year_id: 30)
    Movie.create(title: "Robot Dreams", year_id: 30)
    Movie.create(title: "Role Play", year_id: 30)
    Movie.create(title: "The Room Next Door", year_id: 30)
    Movie.create(title: "Rose's War", year_id: 30)
    Movie.create(title: "The Roundup: Punishment", year_id: 30)
    Movie.create(title: "Rowdy Girl", year_id: 30)
    Movie.create(title: "Rule of Two Walls", year_id: 30)
    Movie.create(title: "Rumours", year_id: 30)
    Movie.create(title: "Ruslaan", year_id: 30)
    Movie.create(title: "Ryan's World the Movie: Titan Universe Adventure", year_id: 30)
    Movie.create(title: "Ryuichi Sakamoto | Opus", year_id: 30)
    Movie.create(title: "Sabbath Queen", year_id: 30)
    Movie.create(title: "A Sacrifice", year_id: 30)
    Movie.create(title: "Saindhav", year_id: 30)
    Movie.create(title: "Santosh", year_id: 30)
    Movie.create(title: "Sarangi: A Journey of Purna Bahadur", year_id: 30)
    Movie.create(title: "Sarfira", year_id: 30)
    Movie.create(title: "Saripodhaa Sanivaaram", year_id: 30)
    Movie.create(title: "Sasquatch Sunset", year_id: 30)
    Movie.create(title: "Saturday Night", year_id: 30)
    Movie.create(title: "Satyabhama", year_id: 30)
    Movie.create(title: "Say a Little Prayer", year_id: 30)
    Movie.create(title: "Scab Vendor: Confessions of a Tattoo Artist", year_id: 30)
    Movie.create(title: "Scoop", year_id: 30)
    Movie.create(title: "Scrambled", year_id: 30)
    Movie.create(title: "Seagrass", year_id: 30)
    Movie.create(title: "Sebastian", year_id: 30)
    Movie.create(title: "The Secret Art of Human Flight", year_id: 30)
    Movie.create(title: "The Seed of the Sacred Fig", year_id: 30)
    Movie.create(title: "Seeking Mavis Beacon", year_id: 30)
    Movie.create(title: "Self Reliance", year_id: 30)
    Movie.create(title: "Sentinel", year_id: 30)
    Movie.create(title: "Separated", year_id: 30)
    Movie.create(title: "September 5", year_id: 30)
    Movie.create(title: "The Settlers", year_id: 30)
    Movie.create(title: "The Shade", year_id: 30)
    Movie.create(title: "The Shadow Strays", year_id: 30)
    Movie.create(title: "The Shadowless Tower", year_id: 30)
    Movie.create(title: "Shaitann", year_id: 30)
    Movie.create(title: "She Is Conann", year_id: 30)
    Movie.create(title: "She Rises Up", year_id: 30)
    Movie.create(title: "She Taught Love", year_id: 30)
    Movie.create(title: "Shining for One Thing", year_id: 30)
    Movie.create(title: "Shirley", year_id: 30)
    Movie.create(title: "Sica", year_id: 30)
    Movie.create(title: "Sight", year_id: 30)
    Movie.create(title: "The Silent Hour", year_id: 30)
    Movie.create(title: "Sing Sing", year_id: 30)
    Movie.create(title: "Singham Again", year_id: 30)
    Movie.create(title: "Sirocco and the Kingdom of the Winds", year_id: 30)
    Movie.create(title: "Sisi & I", year_id: 30)
    Movie.create(title: "The Six Triple Eight", year_id: 30)
    Movie.create(title: "64 Days", year_id: 30)
    Movie.create(title: "Skin Deep", year_id: 30)
    Movie.create(title: "Skincare", year_id: 30)
    Movie.create(title: "Skywalkers: A Love Story", year_id: 30)
    Movie.create(title: "Sleep", year_id: 30)
    Movie.create(title: "Sleeping Dogs", year_id: 30)
    Movie.create(title: "Slingshot", year_id: 30)
    Movie.create(title: "Slow", year_id: 30)
    Movie.create(title: "Small Things Like These", year_id: 30)
    Movie.create(title: "Smile 2", year_id: 30)
    Movie.create(title: "Snack Shack", year_id: 30)
    Movie.create(title: "Soccer Soul", year_id: 30)
    Movie.create(title: "Solo", year_id: 30)
    Movie.create(title: "Solo Leveling: ReAwakening", year_id: 30)
    Movie.create(title: "Someone Like You", year_id: 30)
    Movie.create(title: "Sometimes I Think About Dying", year_id: 30)
    Movie.create(title: "Somewhere Quiet", year_id: 30)
    Movie.create(title: "Songs of Earth", year_id: 30)
    Movie.create(title: "Sonic the Hedgehog 3", year_id: 30)
    Movie.create(title: "Sons of Rizk 3", year_id: 30)
    Movie.create(title: "Sorry / Not Sorry", year_id: 30)
    Movie.create(title: "Sound of Hope: The Story of Possum Trot", year_id: 30)
    Movie.create(title: "Soundtrack to a Coup d'Etat", year_id: 30)
    Movie.create(title: "Space Cadet", year_id: 30)
    Movie.create(title: "The Space Race", year_id: 30)
    Movie.create(title: "Space: The Longest Goodbye", year_id: 30)
    Movie.create(title: "Spaceman", year_id: 30)
    Movie.create(title: "Sparta", year_id: 30)
    Movie.create(title: "Speak No Evil", year_id: 30)
    Movie.create(title: "The Speedway Murders", year_id: 30)
    Movie.create(title: "Spellbound", year_id: 30)
    Movie.create(title: "Spermworld", year_id: 30)
    Movie.create(title: "Spy x Family—Code: White", year_id: 30)
    Movie.create(title: "Srikanth", year_id: 30)
    Movie.create(title: "Standing on the Shoulders of Kitties: The Bubbles And The Shitrockers Story", year_id: 30)
    Movie.create(title: "Starring Jerry as Himself", year_id: 30)
    Movie.create(title: "State Organs", year_id: 30)
    Movie.create(title: "Stay With Us", year_id: 30)
    Movie.create(title: "Sting", year_id: 30)
    Movie.create(title: "The Stolen Valley", year_id: 30)
    Movie.create(title: "Stopmotion", year_id: 30)
    Movie.create(title: "The Storm", year_id: 30)
    Movie.create(title: "A Storm Foretold", year_id: 30)
    Movie.create(title: "Stormy", year_id: 30)
    Movie.create(title: "Strange Darling", year_id: 30)
    Movie.create(title: "The Strangers: Chapter 1", year_id: 30)
    Movie.create(title: "Stream", year_id: 30)
    Movie.create(title: "Stree 2", year_id: 30)
    Movie.create(title: "Stress Positions", year_id: 30)
    Movie.create(title: "Strictly Confidential", year_id: 30)
    Movie.create(title: "Stuntman", year_id: 30)
    Movie.create(title: "The Substance", year_id: 30)
    Movie.create(title: "Successor", year_id: 30)
    Movie.create(title: "SUGA | Agust D Tour: D-Day—The Movie", year_id: 30)
    Movie.create(title: "Sugarcane", year_id: 30)
    Movie.create(title: "Summer Camp", year_id: 30)
    Movie.create(title: "Summer Light and Then Comes the Night", year_id: 30)
    Movie.create(title: "Summer Solstice", year_id: 30)
    Movie.create(title: "Suncoast", year_id: 30)
    Movie.create(title: "Super/Man: The Christopher Reeve Story", year_id: 30)
    Movie.create(title: "The Supremes at Earl's All-You-Can-Eat", year_id: 30)
    Movie.create(title: "Swan Song", year_id: 30)
    Movie.create(title: "Swatantra Veer Savarkar", year_id: 30)
    Movie.create(title: "Sweet Dreams", year_id: 30)
    Movie.create(title: "Sweetheart Deal", year_id: 30)
    Movie.create(title: "Sweethearts", year_id: 30)
    Movie.create(title: "Table for Six 2", year_id: 30)
    Movie.create(title: "Taking Venice", year_id: 30)
    Movie.create(title: "Tarot", year_id: 30)
    Movie.create(title: "The Taste of Mango", year_id: 30)
    Movie.create(title: "Teri Baaton Main Aisa Uljha Jiya", year_id: 30)
    Movie.create(title: "Terrestrial Verses", year_id: 30)
    Movie.create(title: "Terrifier 3", year_id: 30)
    Movie.create(title: "Thank You, Dr. Fauci", year_id: 30)
    Movie.create(title: "That Christmas", year_id: 30)
    Movie.create(title: "That Kind of Summer", year_id: 30)
    Movie.create(title: "Theater of Thought", year_id: 30)
    Movie.create(title: "Thelma", year_id: 30)
    Movie.create(title: "Thelma the Unicorn", year_id: 30)
    Movie.create(title: "They Called Him Mostly Harmless", year_id: 30)
    Movie.create(title: "The Thicket", year_id: 30)
    Movie.create(title: "Things Will Be Different", year_id: 30)
    Movie.create(title: "This Closeness", year_id: 30)
    Movie.create(title: "This Search for Meaning", year_id: 30)
    Movie.create(title: "This World Is Not My Own", year_id: 30)
    Movie.create(title: "Three Oldboys", year_id: 30)
    Movie.create(title: "Three Promises", year_id: 30)
    Movie.create(title: "Tiger Stripes", year_id: 30)
    Movie.create(title: "Tiger Wolf Rabbit", year_id: 30)
    Movie.create(title: "(Tillu)²", year_id: 30)
    Movie.create(title: "Time Still Turns the Pages", year_id: 30)
    Movie.create(title: "To Gather Around", year_id: 30)
    Movie.create(title: "Tokyo Cowboy", year_id: 30)
    Movie.create(title: "Toofan", year_id: 30)
    Movie.create(title: "Touch", year_id: 30)
    Movie.create(title: "Transformers One", year_id: 30)
    Movie.create(title: "Trap", year_id: 30)
    Movie.create(title: "Trap City", year_id: 30)
    Movie.create(title: "A Traveler's Needs", year_id: 30)
    Movie.create(title: "Trim Season", year_id: 30)
    Movie.create(title: "Treasure", year_id: 30)
    Movie.create(title: "The Trophy Bride", year_id: 30)
    Movie.create(title: "The Truth vs. Alex Jones", year_id: 30)
    Movie.create(title: "The Tuba Thieves", year_id: 30)
    Movie.create(title: "Tuesday", year_id: 30)
    Movie.create(title: "Turtles All the Way Down", year_id: 30)
    Movie.create(title: "20,000 Species of Bees", year_id: 30)
    Movie.create(title: "Twice Colonized", year_id: 30)
    Movie.create(title: "Twilight of the Warriors: Walled In", year_id: 30)
    Movie.create(title: "Twisted Hearts", year_id: 30)
    Movie.create(title: "Twisters", year_id: 30)
    Movie.create(title: "Twittering Soul", year_id: 30)
    Movie.create(title: "200% Wolf", year_id: 30)
    Movie.create(title: "2024 Sundance Film Festival Shorts Tour", year_id: 30)
    Movie.create(title: "2073", year_id: 30)
    Movie.create(title: "Uglies", year_id: 30)
    Movie.create(title: "UKI", year_id: 30)
    Movie.create(title: "Ullozhukku", year_id: 30)
    Movie.create(title: "Ultraman: Rising", year_id: 30)
    Movie.create(title: "Umro Ayyar—A New Beginning", year_id: 30)
    Movie.create(title: "Uncropped", year_id: 30)
    Movie.create(title: "The Underdoggs", year_id: 30)
    Movie.create(title: "Unfightable", year_id: 30)
    Movie.create(title: "Unfrosted", year_id: 30)
    Movie.create(title: "Un/Happy for You", year_id: 30)
    Movie.create(title: "Union", year_id: 30)
    Movie.create(title: "The Union", year_id: 30)
    Movie.create(title: "Universal Language", year_id: 30)
    Movie.create(title: "The Universal Theory", year_id: 30)
    Movie.create(title: "The Unseen Sister", year_id: 30)
    Movie.create(title: "Unsinkable", year_id: 30)
    Movie.create(title: "Unstoppable", year_id: 30)
    Movie.create(title: "Unsung Hero", year_id: 30)
    Movie.create(title: "Untouchable", year_id: 30)
    Movie.create(title: "Upgraded", year_id: 30)
    Movie.create(title: "Upstream", year_id: 30)
    Movie.create(title: "Vanvaas", year_id: 30)
    Movie.create(title: "Vedaa", year_id: 30)
    Movie.create(title: "Venom: The Last Dance", year_id: 30)
    Movie.create(title: "Vermiglio", year_id: 30)
    Movie.create(title: "Veselka: The Rainbow on the Corner at the Center of the World", year_id: 30)
    Movie.create(title: "Vettaiyan", year_id: 30)
    Movie.create(title: "Vicky Vidya Ka Woh Wala Video", year_id: 30)
    Movie.create(title: "Villains Inc", year_id: 30)
    Movie.create(title: "Vindicating Trump", year_id: 30)
    Movie.create(title: "Vishniac", year_id: 30)
    Movie.create(title: "Viva La Vida", year_id: 30)
    Movie.create(title: "The Vourdalak", year_id: 30)
    Movie.create(title: "The Wall of the Dead", year_id: 30)
    Movie.create(title: "The Wall Street Boy", year_id: 30)
    Movie.create(title: "Wallace & Gromit: Vengeance Most Fowl", year_id: 30)
    Movie.create(title: "War Game", year_id: 30)
    Movie.create(title: "Warning 2", year_id: 30)
    Movie.create(title: "The Wasp", year_id: 30)
    Movie.create(title: "The Watchers", year_id: 30)
    Movie.create(title: "Water Brother", year_id: 30)
    Movie.create(title: "Wayward", year_id: 30)
    Movie.create(title: "We Grown Now", year_id: 30)
    Movie.create(title: "We Had the Day Bonsoir", year_id: 30)
    Movie.create(title: "We Live in Time We 12", year_id: 30)
    Movie.create(title: "We Will Dance Again", year_id: 30)
    Movie.create(title: "Weak Layers", year_id: 30)
    Movie.create(title: "Weekend in Taipei", year_id: 30)
    Movie.create(title: "The Well", year_id: 30)
    Movie.create(title: "Werewolves", year_id: 30)
    Movie.create(title: "Whale Restaurant", year_id: 30)
    Movie.create(title: "Where", year_id: 30)
    Movie.create(title: "Which Brings Me to You", year_id: 30)
    Movie.create(title: "White Bird", year_id: 30)
    Movie.create(title: "White With Fear", year_id: 30)
    Movie.create(title: "Who Is Stan Smith?", year_id: 30)
    Movie.create(title: "Who's Afraid of Nathan Law?", year_id: 30)
    Movie.create(title: "Wicked Little Letters", year_id: 30)
    Movie.create(title: "Wicked: Part I Widow Clicquot", year_id: 30)
    Movie.create(title: "The Wild Robot", year_id: 30)
    Movie.create(title: "Wildcat", year_id: 30)
    Movie.create(title: "Will & Harper", year_id: 30)
    Movie.create(title: "William Shatner: You Can Call Me Bill", year_id: 30)
    Movie.create(title: "Winner", year_id: 30)
    Movie.create(title: "Witches", year_id: 30)
    Movie.create(title: "With Love and a Major Organ", year_id: 30)
    Movie.create(title: "Wolfs", year_id: 30)
    Movie.create(title: "Woman of the Hour", year_id: 30)
    Movie.create(title: "The Wonderful Story of Henry Sugar and Three More", year_id: 30)
    Movie.create(title: "The World According to Allee Willis", year_id: 30)
    Movie.create(title: "Yannick", year_id: 30)
    Movie.create(title: "Yodha", year_id: 30)
    Movie.create(title: "YOLO", year_id: 30)
    Movie.create(title: "You Are Not Me", year_id: 30)
    Movie.create(title: "You Can't Run Forever", year_id: 30)
    Movie.create(title: "You Can’t Stay Here", year_id: 30)
    Movie.create(title: "You Gotta Believe", year_id: 30)
    Movie.create(title: "You Have to Come and See It", year_id: 30)
    Movie.create(title: "Young Werther", year_id: 30)
    Movie.create(title: "The Young Wife", year_id: 30)
    Movie.create(title: "Young Woman and the Sea", year_id: 30)
    Movie.create(title: "Your Monster", year_id: 30)
    Movie.create(title: "Youth (Hard Times)", year_id: 30)
    Movie.create(title: "Youth (Homecoming)", year_id: 30)
    Movie.create(title: "Y2K", year_id: 30)
    Movie.create(title: "Yudhra", year_id: 30)
    Movie.create(title: "Zurawski v Texas", year_id: 30)
  end
end
