class Year < ActiveRecord::Base
  has_many :movies
  has_many :ballots
  has_many :credits
  has_many :scenes

  validates :name, presence: true
  validates :open_voting, presence: true
  validates :close_voting, presence: true
  validates :display_results, presence: true


  def self.results_display
    where("display_results < ?", Time.zone.now).last
  end

  def self.active_voting
    where("open_voting < ? AND close_voting > ?", Time.zone.now, Time.zone.now).last
  end

  def self.all_but_results_display
    year_array = []
    where("display_results < ?", Time.zone.now).all.each do |y|
      if y != Year.results_display
        year_array << y
      end
    end
    year_array
  end

  def self.get_display_year(year)
    if year
      where("name = ? and display_results < ?", year, Time.zone.now ).last
    else
      Year.results_display
    end
  end

  def eligible_movies_by_average_rating
    movies.where("nbr_ratings > 4").order(average_rating: :desc, title_index: :asc)
  end

  def ranked_movies_hash
    ranked_movies_hash = {}
    hold_for_ties_array = []
    tie_start_index = 0
    tie_average_rating = 0.00
    movies_array = eligible_movies_by_average_rating
    movies_array.each_with_index do |m,index|
      if m.average_rating == tie_average_rating || index == 0 # this movie is tied with the previous movie on the list
        hold_for_ties_array << m
        if index + 1 == movies_array.length # end of the list--move last movie (plus any previous ties) to hash
          rank_array = (tie_start_index..index + 1).to_a
          rank_sum = rank_array.inject(:+)
          average_rank_of_tied_movies = rank_sum.to_f / hold_for_ties_array.length.to_f
          hold_for_ties_array.each do |m|
            ranked_movies_hash[m.id] = average_rank_of_tied_movies
          end
        end
      else
        if hold_for_ties_array.length > 1 # there are two or more tied movies in the hold array
          rank_array = (tie_start_index..index).to_a
          rank_sum = rank_array.inject(:+)
          average_rank_of_tied_movies = rank_sum.to_f / hold_for_ties_array.length.to_f
          hold_for_ties_array.each do |m|
            ranked_movies_hash[m.id] = average_rank_of_tied_movies
          end
        elsif hold_for_ties_array.length == 1 # there is a single movie in the hold array.  There were no ties.
          ranked_movies_hash[hold_for_ties_array[0].id] = index
        end
        if index + 1 == movies_array.length # end of the list--move last movie to the hash
          ranked_movies_hash[m.id] = index + 1
        else
          hold_for_ties_array = [m]
          tie_start_index = index + 1
          tie_average_rating = m.average_rating
        end
      end
    end
    ranked_movies_hash
  end

  def save_movie_vote_results
    picture_category = Category.where(name: "picture").first
    director_category = Category.where(name: "director").first
    screenplay_category = Category.where(name: "screenplay").first
    movies.each do |m|
      m.picture_points = m.compute_points(picture_category)
      m.picture_votes = m.compute_votes(picture_category)
      m.director_points = m.compute_points(director_category)
      m.director_votes = m.compute_votes(director_category)
      m.screenplay_points = m.compute_points(screenplay_category)
      m.screenplay_votes = m.compute_votes(screenplay_category)
      m.save
    end
  end

  def save_credit_vote_results
    actor_job = Job.where(name: "actor")
    credits.where(job: actor_job).each do |c|
      results_category = c.compute_results_category
      c.category = results_category
      c.points = c.compute_points_results(results_category)
      c.nbr_votes = c.compute_votes_results(results_category)
      c.save
    end
  end

  def save_scene_vote_results
    scenes.each do |s|
      s.nbr_votes = s.compute_votes
      s.points = s.compute_points
      s.save
    end
  end

  def save_ratings_results
    movies.each do |m|
      m.nbr_ratings = m.compute_total_nbr_ratings
      m.average_rating = m.compute_average_rating
      m.four_ratings = m.compute_nbr_ratings(4.0)
      m.three_pt_five_ratings = m.compute_nbr_ratings(3.5)
      m.three_ratings = m.compute_nbr_ratings(3.0)
      m.two_pt_five_ratings = m.compute_nbr_ratings(2.5)
      m.two_ratings = m.compute_nbr_ratings(2.0)
      m.one_pt_five_ratings = m.compute_nbr_ratings(1.5)
      m.one_ratings = m.compute_nbr_ratings(1.0)
      m.zero_ratings = m.compute_nbr_ratings(0.0)
      if m.compute_total_nbr_ratings > 1
        m.standard_dev = m.compute_standard_dev
      end
      m.save
    end
  end

  def save_user_profile_results
    ballots.each do |b|
      b.nbr_ratings = b.compute_total_nbr_ratings
      b.average_rating = b.compute_average_rating
      b.four_ratings = b.compute_nbr_ratings(4.0)
      b.three_pt_five_ratings = b.compute_nbr_ratings(3.5)
      b.three_ratings = b.compute_nbr_ratings(3.0)
      b.two_pt_five_ratings = b.compute_nbr_ratings(2.5)
      b.two_ratings = b.compute_nbr_ratings(2.0)
      b.one_pt_five_ratings = b.compute_nbr_ratings(1.5)
      b.one_ratings = b.compute_nbr_ratings(1.0)
      b.zero_ratings = b.compute_nbr_ratings(0.0)
      b.selectivity_index = b.compute_selectivity_index
      b.save
    end
  end

  def save_complete_results
    save_movie_vote_results
    save_credit_vote_results
    save_scene_vote_results
    save_ratings_results
    save_user_profile_results
  end

  def self.upload_2021_movies
    Movie.create(title: "About Endlessness", year_id: 27)
    Movie.create(title: "About Us", year_id: 27)
    Movie.create(title: "Above Suspicion", year_id: 27)
    Movie.create(title: "Acasa, My Home", year_id: 27)
    Movie.create(title: "Accidental Luxuriance of the Translucent Watery Rebus", year_id: 27)
    Movie.create(title: "Adam", year_id: 27)
    Movie.create(title: "The Addams Family 2", year_id: 27)
    Movie.create(title: "The Advent Calendar", year_id: 27)
    Movie.create(title: "After the Murder of Albert Lima", year_id: 27)
    Movie.create(title: "After We Fell", year_id: 27)
    Movie.create(title: "Against the Current", year_id: 27)
    Movie.create(title: "Agnes", year_id: 27)
    Movie.create(title: "Ahead of the Curve", year_id: 27)
    Movie.create(title: "Ailey", year_id: 27)
    Movie.create(title: "Akhanda", year_id: 27)
    Movie.create(title: "Akilla’s Escape", year_id: 27)
    Movie.create(title: "All About My Sisters", year_id: 27)
    Movie.create(title: "All Hands on Deck", year_id: 27)
    Movie.create(title: "All Light, Everywhere", year_id: 27)
    Movie.create(title: "All the Dead Ones", year_id: 27)
    Movie.create(title: "All the Streets Are Silent", year_id: 27)
    Movie.create(title: "Alpha Rift", year_id: 27)
    Movie.create(title: "The Alpinist", year_id: 27)
    Movie.create(title: "America: The Motion Picture", year_id: 27)
    Movie.create(title: "American Fighter", year_id: 27)
    Movie.create(title: "American Insurrection", year_id: 27)
    Movie.create(title: "American Night", year_id: 27)
    Movie.create(title: "American 965", year_id: 27)
    Movie.create(title: "American Sausage Standoff", year_id: 27)
    Movie.create(title: "The American Sector", year_id: 27)
    Movie.create(title: "American Sicario", year_id: 27)
    Movie.create(title: "American Skin", year_id: 27)
    Movie.create(title: "American Traitor: The Trial of Axis Sally", year_id: 27)
    Movie.create(title: "American Underdog", year_id: 27)
    Movie.create(title: "Amundsen", year_id: 27)
    Movie.create(title: "Anita", year_id: 27)
    Movie.create(title: "Annaatthe", year_id: 27)
    Movie.create(title: "Anne at 13,000 Feet.", year_id: 27)
    Movie.create(title: "Annette ", year_id: 27)
    Movie.create(title: "Antim: The Final Truth", year_id: 27)
    Movie.create(title: "Antlers", year_id: 27)
    Movie.create(title: "Apache Junction", year_id: 27)
    Movie.create(title: "Apocalypse ’45", year_id: 27)
    Movie.create(title: "Arlo the Alligator Boy", year_id: 27)
    Movie.create(title: "Army of the Dead", year_id: 27)
    Movie.create(title: "Army of Thieves", year_id: 27)
    Movie.create(title: "Artificial Gamer", year_id: 27)
    Movie.create(title: "Ascension", year_id: 27)
    Movie.create(title: "Asia", year_id: 27)
    Movie.create(title: "Atlantis", year_id: 27)
    Movie.create(title: "Attica", year_id: 27)
    Movie.create(title: "@Zola", year_id: 27)
    Movie.create(title: "The August Virgin", year_id: 27)
    Movie.create(title: "Aulcie", year_id: 27)
    Movie.create(title: "Awake", year_id: 27)
    Movie.create(title: "The Awakening of the Ants", year_id: 27)
    Movie.create(title: "Aware: Glimpses of Consciousness", year_id: 27)
    Movie.create(title: "Azor", year_id: 27)
    Movie.create(title: "Back of the Moon", year_id: 27)
    Movie.create(title: "Back to the Outback", year_id: 27)
    Movie.create(title: "Bad Luck Banging or Loony Porn", year_id: 27)
    Movie.create(title: "Bad Tales", year_id: 27)
    Movie.create(title: "Bad Trip", year_id: 27)
    Movie.create(title: "Baggio: The Divine Ponytail", year_id: 27)
    Movie.create(title: "Bait", year_id: 27)
    Movie.create(title: "The Banishing", year_id: 27)
    Movie.create(title: "Barb and Star Go to Vista Del Mar", year_id: 27)
    Movie.create(title: "The Battle at Lake Changjin", year_id: 27)
    Movie.create(title: "Be Somebody", year_id: 27)
    Movie.create(title: "Beans", year_id: 27)
    Movie.create(title: "Beautiful Something Left Behind", year_id: 27)
    Movie.create(title: "Beckett", year_id: 27)
    Movie.create(title: "Becoming Cousteau", year_id: 27)
    Movie.create(title: "Before the Dying of the Light", year_id: 27)
    Movie.create(title: "Beginning", year_id: 27)
    Movie.create(title: "Beijing Spring", year_id: 27)
    Movie.create(title: "Being a Human Person", year_id: 27)
    Movie.create(title: "Being the Ricardos", year_id: 27)
    Movie.create(title: "Belfast", year_id: 27)
    Movie.create(title: "Bell Bottom", year_id: 27)
    Movie.create(title: "Belonging", year_id: 27)
    Movie.create(title: "Benedetta", year_id: 27)
    Movie.create(title: "Bergman Island", year_id: 27)
    Movie.create(title: "Berlin Alexanderplatz", year_id: 27)
    Movie.create(title: "Best Sellers", year_id: 27)
    Movie.create(title: "Best Summer Ever", year_id: 27)
    Movie.create(title: "The Beta Test", year_id: 27)
    Movie.create(title: "Between Waves", year_id: 27)
    Movie.create(title: "The Big Scary ’S’ Word", year_id: 27)
    Movie.create(title: "Bill Traylor: Chasing Ghosts", year_id: 27)
    Movie.create(title: "Billie Eilish: The World’s a Little Blurry", year_id: 27)
    Movie.create(title: "Bingo Hell", year_id: 27)
    Movie.create(title: "Birds of Paradise", year_id: 27)
    Movie.create(title: "The Birthday Cake", year_id: 27)
    Movie.create(title: "Bitchin’: The Sound and Fury of Rick James", year_id: 27)
    Movie.create(title: "Black as Night", year_id: 27)
    Movie.create(title: "Black Friday", year_id: 27)
    Movie.create(title: "Black Widow", year_id: 27)
    Movie.create(title: "Blast Beat", year_id: 27)
    Movie.create(title: "The Blazing World", year_id: 27)
    Movie.create(title: "Bliss", year_id: 27)
    Movie.create(title: "Blithe Spirit", year_id: 27)
    Movie.create(title: "Bloody Hell", year_id: 27)
    Movie.create(title: "Blue Bayou", year_id: 27)
    Movie.create(title: "Blue Miracle", year_id: 27)
    Movie.create(title: "Bob Ross: Happy Accidents, Betrayal & Greed", year_id: 27)
    Movie.create(title: "Body Brokers", year_id: 27)
    Movie.create(title: "Boiling Point", year_id: 27)
    Movie.create(title: "Bombay Rose", year_id: 27)
    Movie.create(title: "Boogie", year_id: 27)
    Movie.create(title: "Boris Karloff: The Man Behind the Monster", year_id: 27)
    Movie.create(title: "The Boss Baby: Family Business", year_id: 27)
    Movie.create(title: "Boss Level", year_id: 27)
    Movie.create(title: "The Boy Behind the Door", year_id: 27)
    Movie.create(title: "A Boy Called Christmas", year_id: 27)
    Movie.create(title: "The Boy From Medellín", year_id: 27)
    Movie.create(title: "The Boys in Red Hats", year_id: 27)
    Movie.create(title: "Breaking Boundaries: The Science of Our Planet", year_id: 27)
    Movie.create(title: "Breaking News in Yuba County", year_id: 27)
    Movie.create(title: "Brian Wilson: Long Promised Road", year_id: 27)
    Movie.create(title: "Bring Down the Walls", year_id: 27)
    Movie.create(title: "Bring Your Own Brigade", year_id: 27)
    Movie.create(title: "Britney vs Spears", year_id: 27)
    Movie.create(title: "Broadcast Signal Intrusion", year_id: 27)
    Movie.create(title: "Broken Diamonds", year_id: 27)
    Movie.create(title: "Broken Harts", year_id: 27)
    Movie.create(title: "Bruised", year_id: 27)
    Movie.create(title: "Buckley’s Chance", year_id: 27)
    Movie.create(title: "Bulletproof", year_id: 27)
    Movie.create(title: "Bunty Aur Babli 2", year_id: 27)
    Movie.create(title: "Burning", year_id: 27)
    Movie.create(title: "Can You Bring It: Bill T. Jones and D-Man in the Waters", year_id: 27)
    Movie.create(title: "Candyman", year_id: 27)
    Movie.create(title: "The Capote Tapes", year_id: 27)
    Movie.create(title: "Captains of Zaatari", year_id: 27)
    Movie.create(title: "The Card Counter", year_id: 27)
    Movie.create(title: "The Carnivores", year_id: 27)
    Movie.create(title: "Casanova, Last Love", year_id: 27)
    Movie.create(title: "A Castle for Christmas", year_id: 27)
    Movie.create(title: "Catch the Bullet", year_id: 27)
    Movie.create(title: "Cenote", year_id: 27)
    Movie.create(title: "Censor", year_id: 27)
    Movie.create(title: "Chal Mera Putt 2", year_id: 27)
    Movie.create(title: "Chal Mera Putt 3", year_id: 27)
    Movie.create(title: "Chandigarh Kare Aashiqui", year_id: 27)
    Movie.create(title: "Changing the Game", year_id: 27)
    Movie.create(title: "Chaos Walking", year_id: 27)
    Movie.create(title: "Charlatan", year_id: 27)
    Movie.create(title: "Chasing Wonders", year_id: 27)
    Movie.create(title: "Chehre", year_id: 27)
    Movie.create(title: "Chernobyl 1986", year_id: 27)
    Movie.create(title: "Cherry", year_id: 27)
    Movie.create(title: "Chinese Doctors", year_id: 27)
    Movie.create(title: "A Choice of Weapons: Inspired by Gordon Parks", year_id: 27)
    Movie.create(title: "Christmas With the Chosen: \"The Messengers\"", year_id: 27)
    Movie.create(title: "Cicada", year_id: 27)
    Movie.create(title: "Cinderella", year_id: 27)
    Movie.create(title: "Circle of Bones", year_id: 27)
    Movie.create(title: "Citizen Ashe", year_id: 27)
    Movie.create(title: "Citizen Penn", year_id: 27)
    Movie.create(title: "City of Ali", year_id: 27)
    Movie.create(title: "Civil War (Or, Who Do We Think We Are)", year_id: 27)
    Movie.create(title: "A Classic Horror Story", year_id: 27)
    Movie.create(title: "Cliff Walkers", year_id: 27)
    Movie.create(title: "Clifford the Big Red Dog", year_id: 27)
    Movie.create(title: "Cloudy Mountain", year_id: 27)
    Movie.create(title: "C’mon C’mon", year_id: 27)
    Movie.create(title: "CODA", year_id: 27)
    Movie.create(title: "Collection", year_id: 27)
    Movie.create(title: "The Colony", year_id: 27)
    Movie.create(title: "The Columnist", year_id: 27)
    Movie.create(title: "Combat Wombat", year_id: 27)
    Movie.create(title: "Come From Away", year_id: 27)
    Movie.create(title: "Come True", year_id: 27)
    Movie.create(title: "Coming Home in the Dark", year_id: 27)
    Movie.create(title: "Coming 2 America", year_id: 27)
    Movie.create(title: "Concrete Cowboy", year_id: 27)
    Movie.create(title: "Confetti", year_id: 27)
    Movie.create(title: "The Conjuring: The Devil Made Me Do It", year_id: 27)
    Movie.create(title: "The Conservation Game", year_id: 27)
    Movie.create(title: "Convergence", year_id: 27)
    Movie.create(title: "A Cop Movie", year_id: 27)
    Movie.create(title: "Copshop", year_id: 27)
    Movie.create(title: "Corporate Responsibility", year_id: 27)
    Movie.create(title: "The County", year_id: 27)
    Movie.create(title: "The Courier", year_id: 27)
    Movie.create(title: "Cousins", year_id: 27)
    Movie.create(title: "Cowboys", year_id: 27)
    Movie.create(title: "Crack", year_id: 27)
    Movie.create(title: "A Crime on the Bayou", year_id: 27)
    Movie.create(title: "Crime Story", year_id: 27)
    Movie.create(title: "Crisis", year_id: 27)
    Movie.create(title: "Cruella", year_id: 27)
    Movie.create(title: "Cry Macho", year_id: 27)
    Movie.create(title: "Cryptozoo", year_id: 27)
    Movie.create(title: "Cursed Official", year_id: 27)
    Movie.create(title: "Cusp", year_id: 27)
    Movie.create(title: "Dad, I’m Sorry", year_id: 27)
    Movie.create(title: "Dangerous", year_id: 27)
    Movie.create(title: "Dara of Jasenovac", year_id: 27)
    Movie.create(title: "A Dark Foe", year_id: 27)
    Movie.create(title: "Dark State", year_id: 27)
    Movie.create(title: "Dating & New York", year_id: 27)
    Movie.create(title: "The Day After I’m Gone", year_id: 27)
    Movie.create(title: "Days", year_id: 27)
    Movie.create(title: "Days of the Bagnold Summer", year_id: 27)
    Movie.create(title: "Dead Man’s Switch: A Crypto Mystery", year_id: 27)
    Movie.create(title: "Deadlock", year_id: 27)
    Movie.create(title: "Dear Evan Hansen", year_id: 27)
    Movie.create(title: "Dear Rider, the Jake Burton Story", year_id: 27)
    Movie.create(title: "Death of a Telemarketer", year_id: 27)
    Movie.create(title: "Death Rider in the House of Vampires", year_id: 27)
    Movie.create(title: "The Deep House", year_id: 27)
    Movie.create(title: "Delphine’s Prayers", year_id: 27)
    Movie.create(title: "Demon Slayer: The Movie—Mugen Train", year_id: 27)
    Movie.create(title: "Demonic", year_id: 27)
    Movie.create(title: "Devil Between the Legs", year_id: 27)
    Movie.create(title: "Diary of a Wimpy Kid", year_id: 27)
    Movie.create(title: "Die in a Gunfight", year_id: 27)
    Movie.create(title: "The Dig", year_id: 27)
    Movie.create(title: "A Dim Valley", year_id: 27)
    Movie.create(title: "Dirty God", year_id: 27)
    Movie.create(title: "The Disciple", year_id: 27)
    Movie.create(title: "Distancing Socially", year_id: 27)
    Movie.create(title: "The Djinn", year_id: 27)
    Movie.create(title: "Dr. Bird’s Advice for Sad Poets", year_id: 27)
    Movie.create(title: "Dog Gone Trouble", year_id: 27)
    Movie.create(title: "Domino: Battle of the Bones", year_id: 27)
    Movie.create(title: "Donny’s Bar Mitzvah", year_id: 27)
    Movie.create(title: "Don’t Breathe 2", year_id: 27)
    Movie.create(title: "Don’t Look Up", year_id: 27)
    Movie.create(title: "Don’t Tell a Soul", year_id: 27)
    Movie.create(title: "The Dose", year_id: 27)
    Movie.create(title: "Downstream to Kinshasa", year_id: 27)
    Movie.create(title: "Dramarama", year_id: 27)
    Movie.create(title: "Dream Horse", year_id: 27)
    Movie.create(title: "Drive My Car", year_id: 27)
    Movie.create(title: "The Dry", year_id: 27)
    Movie.create(title: "Dune: Part One", year_id: 27)
    Movie.create(title: "Dutch", year_id: 27)
    Movie.create(title: "Duty Free", year_id: 27)
    Movie.create(title: "Earwig and the Witch", year_id: 27)
    Movie.create(title: "The East", year_id: 27)
    Movie.create(title: "East of the Mountains", year_id: 27)
    Movie.create(title: "Eat Wheaties!", year_id: 27)
    Movie.create(title: "Edge of the World", year_id: 27)
    Movie.create(title: "An Egg Rescue", year_id: 27)
    Movie.create(title: "8 Billion Angels", year_id: 27)
    Movie.create(title: "8-Bit Christmas", year_id: 27)
    Movie.create(title: "83", year_id: 27)
    Movie.create(title: "El Cuartito", year_id: 27)
    Movie.create(title: "El Planeta", year_id: 27)
    Movie.create(title: "The Electrical Life of Louis Wain", year_id: 27)
    Movie.create(title: "The Empty Man", year_id: 27)
    Movie.create(title: "Encanto", year_id: 27)
    Movie.create(title: "Encounter", year_id: 27)
    Movie.create(title: "The End of Us", year_id: 27)
    Movie.create(title: "Endgame", year_id: 27)
    Movie.create(title: "Endless Night", year_id: 27)
    Movie.create(title: "Endless Rain", year_id: 27)
    Movie.create(title: "Enemies of the State", year_id: 27)
    Movie.create(title: "Enfant Terrible", year_id: 27)
    Movie.create(title: "Enforcement", year_id: 27)
    Movie.create(title: "Ennio", year_id: 27)
    Movie.create(title: "Enormous: The Gorge Story", year_id: 27)
    Movie.create(title: "Equal Standard", year_id: 27)
    Movie.create(title: "Escape From Mogadishu", year_id: 27)
    Movie.create(title: "Escape Room: Tournament of Champions", year_id: 27)
    Movie.create(title: "The Estate", year_id: 27)
    Movie.create(title: "Eternals", year_id: 27)
    Movie.create(title: "The Evening Hour", year_id: 27)
    Movie.create(title: "Every Breath You Take", year_id: 27)
    Movie.create(title: "Every Last One of Them", year_id: 27)
    Movie.create(title: "Everybody’s Talking About Jamie", year_id: 27)
    Movie.create(title: "The Eyes of Tammy Faye", year_id: 27)
    Movie.create(title: "Eyimofe (This Is My Desire)", year_id: 27)
    Movie.create(title: "Falling", year_id: 27)
    Movie.create(title: "Falling for Figaro", year_id: 27)
    Movie.create(title: "False Positive", year_id: 27)
    Movie.create(title: "Fatal Distraction", year_id: 27)
    Movie.create(title: "Fatherhood", year_id: 27)
    Movie.create(title: "Fathom", year_id: 27)
    Movie.create(title: "Fauci", year_id: 27)
    Movie.create(title: "Fauna", year_id: 27)
    Movie.create(title: "Faya Dayi", year_id: 27)
    Movie.create(title: "Fear of Rain", year_id: 27)
    Movie.create(title: "Fear Street: Part One—1994", year_id: 27)
    Movie.create(title: "Fear Street: Part Two—1978", year_id: 27)
    Movie.create(title: "Fear Street: Part Three—1666", year_id: 27)
    Movie.create(title: "The Feast", year_id: 27)
    Movie.create(title: "Fever Dream", year_id: 27)
    Movie.create(title: "Film About a Father Who", year_id: 27)
    Movie.create(title: "Fin", year_id: 27)
    Movie.create(title: "Final Account", year_id: 27)
    Movie.create(title: "Final Set", year_id: 27)
    Movie.create(title: "Finch", year_id: 27)
    Movie.create(title: "Finding ‘Ohana", year_id: 27)
    Movie.create(title: "Finding You", year_id: 27)
    Movie.create(title: "First Date", year_id: 27)
    Movie.create(title: "The First Wave", year_id: 27)
    Movie.create(title: "Five Years North", year_id: 27)
    Movie.create(title: "Flag Day", year_id: 27)
    Movie.create(title: "Flee", year_id: 27)
    Movie.create(title: "Flora & Ulysses", year_id: 27)
    Movie.create(title: "Florian’s Knights", year_id: 27)
    Movie.create(title: "F9", year_id: 27)
    Movie.create(title: "For the Love of Money", year_id: 27)
    Movie.create(title: "Forever First Love", year_id: 27)
    Movie.create(title: "The Forever Purge", year_id: 27)
    Movie.create(title: "Fortress", year_id: 27)
    Movie.create(title: "Found", year_id: 27)
    Movie.create(title: "Four Good Days", year_id: 27)
    Movie.create(title: "499", year_id: 27)
    Movie.create(title: "14 Peaks", year_id: 27)
    Movie.create(title: "France", year_id: 27)
    Movie.create(title: "Francesco", year_id: 27)
    Movie.create(title: "Free Guy", year_id: 27)
    Movie.create(title: "Freeland", year_id: 27)
    Movie.create(title: "The French Dispatch of the Liberty, Kansas Evening Sun", year_id: 27)
    Movie.create(title: "Future People", year_id: 27)
    Movie.create(title: "G Storm", year_id: 27)
    Movie.create(title: "Gaia", year_id: 27)
    Movie.create(title: "The Gateway", year_id: 27)
    Movie.create(title: "Georgetown", year_id: 27)
    Movie.create(title: "Ghostbusters: Afterlife", year_id: 27)
    Movie.create(title: "Giants Being Lonely", year_id: 27)
    Movie.create(title: "A Gift From Bob", year_id: 27)
    Movie.create(title: "The Girl Who Believes in Miracles", year_id: 27)
    Movie.create(title: "A Glitch in the Matrix", year_id: 27)
    Movie.create(title: "The God Committee", year_id: 27)
    Movie.create(title: "God Exists, Her Name Is Petrunya", year_id: 27)
    Movie.create(title: "Godzilla vs. Kong", year_id: 27)
    Movie.create(title: "Golden Arm", year_id: 27)
    Movie.create(title: "Golden Voices", year_id: 27)
    Movie.create(title: "The Good Traitor", year_id: 27)
    Movie.create(title: "Gorbachev. Heaven", year_id: 27)
    Movie.create(title: "Grace and Grit", year_id: 27)
    Movie.create(title: "The Grand Duke of Corsica", year_id: 27)
    Movie.create(title: "The Green Knight", year_id: 27)
    Movie.create(title: "Gritt", year_id: 27)
    Movie.create(title: "Groomed", year_id: 27)
    Movie.create(title: "The Guilty", year_id: 27)
    Movie.create(title: "Gully", year_id: 27)
    Movie.create(title: "Gunpowder Milkshake", year_id: 27)
    Movie.create(title: "Gyopo", year_id: 27)
    Movie.create(title: "Haathi Mere Saathi", year_id: 27)
    Movie.create(title: "Habit", year_id: 27)
    Movie.create(title: "Halloween Kills", year_id: 27)
    Movie.create(title: "The Halt", year_id: 27)
    Movie.create(title: "The Hand of God", year_id: 27)
    Movie.create(title: "Happier Than Ever: A Love Letter to Los Angeles", year_id: 27)
    Movie.create(title: "Happily", year_id: 27)
    Movie.create(title: "Hard Luck Love Song", year_id: 27)
    Movie.create(title: "The Harder They Fall", year_id: 27)
    Movie.create(title: "The Hating Game", year_id: 27)
    Movie.create(title: "Heart of Champions", year_id: 27)
    Movie.create(title: "Held", year_id: 27)
    Movie.create(title: "Held for Ransom", year_id: 27)
    Movie.create(title: "Hell or High Seas", year_id: 27)
    Movie.create(title: "Her Socialist Smile", year_id: 27)
    Movie.create(title: "Here After", year_id: 27)
    Movie.create(title: "Here Are the Young Men", year_id: 27)
    Movie.create(title: "Here Today", year_id: 27)
    Movie.create(title: "A Hero", year_id: 27)
    Movie.create(title: "He’s All That", year_id: 27)
    Movie.create(title: "The Hidden Life of Trees", year_id: 27)
    Movie.create(title: "Hide and Seek", year_id: 27)
    Movie.create(title: "High Ground", year_id: 27)
    Movie.create(title: "Hitman’s Wife’s Bodyguard", year_id: 27)
    Movie.create(title: "Hive", year_id: 27)
    Movie.create(title: "A Holiday Chance", year_id: 27)
    Movie.create(title: "Holler", year_id: 27)
    Movie.create(title: "Holy Beasts", year_id: 27)
    Movie.create(title: "Home Sweet Home", year_id: 27)
    Movie.create(title: "Home Sweet Home Alone", year_id: 27)
    Movie.create(title: "Homeroom", year_id: 27)
    Movie.create(title: "Honeydew", year_id: 27)
    Movie.create(title: "Honsla Rakh", year_id: 27)
    Movie.create(title: "Hope", year_id: 27)
    Movie.create(title: "Horse Latitudes", year_id: 27)
    Movie.create(title: "The House Next Door: Meet the Blacks 2", year_id: 27)
    Movie.create(title: "House of Gucci", year_id: 27)
    Movie.create(title: "How It Ends", year_id: 27)
    Movie.create(title: "The Human Factor", year_id: 27)
    Movie.create(title: "The Humans", year_id: 27)
    Movie.create(title: "Hunted", year_id: 27)
    Movie.create(title: "Hypnotic", year_id: 27)
    Movie.create(title: "I Am Mother", year_id: 27)
    Movie.create(title: "I Am Not Alone", year_id: 27)
    Movie.create(title: "I Care a Lot", year_id: 27)
    Movie.create(title: "I Love Us", year_id: 27)
    Movie.create(title: "I Was a Simple Man", year_id: 27)
    Movie.create(title: "The Ice Road", year_id: 27)
    Movie.create(title: "Ida Red", year_id: 27)
    Movie.create(title: "Identifying Features", year_id: 27)
    Movie.create(title: "If Not Now, When?", year_id: 27)
    Movie.create(title: "I’m Your Man", year_id: 27)
    Movie.create(title: "In & of Itself", year_id: 27)
    Movie.create(title: "In Balachine’s Classroom", year_id: 27)
    Movie.create(title: "In Our Mothers’ Gardens", year_id: 27)
    Movie.create(title: "In the Earth", year_id: 27)
    Movie.create(title: "In the Heights", year_id: 27)
    Movie.create(title: "In the Same Breath", year_id: 27)
    Movie.create(title: "Incomplete Breath", year_id: 27)
    Movie.create(title: "India Sweets and Spices", year_id: 27)
    Movie.create(title: "Infinite", year_id: 27)
    Movie.create(title: "The Inheritance", year_id: 27)
    Movie.create(title: "Into the Darkness", year_id: 27)
    Movie.create(title: "Introducing, Selma Blair", year_id: 27)
    Movie.create(title: "Intrusion", year_id: 27)
    Movie.create(title: "Isabella", year_id: 27)
    Movie.create(title: "Isolation", year_id: 27)
    Movie.create(title: "It Must Be Heaven", year_id: 27)
    Movie.create(title: "Jacinta", year_id: 27)
    Movie.create(title: "Jagame Thandhiram", year_id: 27)
    Movie.create(title: "Jallikattu", year_id: 27)
    Movie.create(title: "Je Suis Karl", year_id: 27)
    Movie.create(title: "The Jesus Music", year_id: 27)
    Movie.create(title: "Jockey", year_id: 27)
    Movie.create(title: "Joe Bell", year_id: 27)
    Movie.create(title: "John and the Hole", year_id: 27)
    Movie.create(title: "Jolt", year_id: 27)
    Movie.create(title: "A Journal for Jordan", year_id: 27)
    Movie.create(title: "Joy Ride", year_id: 27)
    Movie.create(title: "Joy Womack: The White Swan", year_id: 27)
    Movie.create(title: "Judas and the Black Messiah", year_id: 27)
    Movie.create(title: "Juice WRLD: Into the Abyss", year_id: 27)
    Movie.create(title: "Julia", year_id: 27)
    Movie.create(title: "Jungle Cruise", year_id: 27)
    Movie.create(title: "Just Don’t Think I’ll Scream", year_id: 27)
    Movie.create(title: "Karen Dalton: In My Own Time", year_id: 27)
    Movie.create(title: "Kate", year_id: 27)
    Movie.create(title: "Kenny Scharf: When Worlds Collide", year_id: 27)
    Movie.create(title: "Khartoum Offside", year_id: 27)
    Movie.create(title: "Kid 90", year_id: 27)
    Movie.create(title: "Killian & the Comeback Kids", year_id: 27)
    Movie.create(title: "The Killing of Two Lovers", year_id: 27)
    Movie.create(title: "King Richard", year_id: 27)
    Movie.create(title: "The King’s Man", year_id: 27)
    Movie.create(title: "Kipchoge: The Last Milestone", year_id: 27)
    Movie.create(title: "The Kissing Booth 3", year_id: 27)
    Movie.create(title: "Knocking", year_id: 27)
    Movie.create(title: "Koati", year_id: 27)
    Movie.create(title: "Krabi, 2562", year_id: 27)
    Movie.create(title: "Kurt Vonnegut: Unstuck in Time", year_id: 27)
    Movie.create(title: "Kurup", year_id: 27)
    Movie.create(title: "Labyrinth of Cinema", year_id: 27)
    Movie.create(title: "Lady Boss: The Jackie Collins Story", year_id: 27)
    Movie.create(title: "The Lady of Heaven", year_id: 27)
    Movie.create(title: "Lady of the Manor", year_id: 27)
    Movie.create(title: "Lamb", year_id: 27)
    Movie.create(title: "Land", year_id: 27)
    Movie.create(title: "Language Lessons", year_id: 27)
    Movie.create(title: "Lansky", year_id: 27)
    Movie.create(title: "Lantern’s Lane", year_id: 27)
    Movie.create(title: "Lapsis", year_id: 27)
    Movie.create(title: "Last and First Men", year_id: 27)
    Movie.create(title: "Last Call", year_id: 27)
    Movie.create(title: "The Last Duel", year_id: 27)
    Movie.create(title: "The Last Letter From Your Lover", year_id: 27)
    Movie.create(title: "Last Man Standing: Suge Knight and the Murders of Biggie & Tupac", year_id: 27)
    Movie.create(title: "The Last Matinee", year_id: 27)
    Movie.create(title: "The Last Mercenary", year_id: 27)
    Movie.create(title: "Last Night in Soho", year_id: 27)
    Movie.create(title: "Last Shoot Out", year_id: 27)
    Movie.create(title: "The Last Son", year_id: 27)
    Movie.create(title: "Last Summer", year_id: 27)
    Movie.create(title: "Last Words", year_id: 27)
    Movie.create(title: "The Laws of the Universe—The Age of Elohim", year_id: 27)
    Movie.create(title: "Learning to Live Together: The Return of Mad Dogs & Englishmen", year_id: 27)
    Movie.create(title: "The Legend of the Five", year_id: 27)
    Movie.create(title: "The Legend of the Underground", year_id: 27)
    Movie.create(title: "Les Nôtres", year_id: 27)
    Movie.create(title: "Let Us In", year_id: 27)
    Movie.create(title: "Letter to the Editor", year_id: 27)
    Movie.create(title: "LFG", year_id: 27)
    Movie.create(title: "Licorice Pizza", year_id: 27)
    Movie.create(title: "Life in a Day 2020", year_id: 27)
    Movie.create(title: "Lily Topples the World", year_id: 27)
    Movie.create(title: "Limbo", year_id: 27)
    Movie.create(title: "Listening to Kenny G", year_id: 27)
    Movie.create(title: "Litigante", year_id: 27)
    Movie.create(title: "Little Big Women", year_id: 27)
    Movie.create(title: "Little Fish", year_id: 27)
    Movie.create(title: "Little Girl", year_id: 27)
    Movie.create(title: "The Little Things", year_id: 27)
    Movie.create(title: "Locked Down", year_id: 27)
    Movie.create(title: "The Loneliest Whale", year_id: 27)
    Movie.create(title: "Long Story Short", year_id: 27)
    Movie.create(title: "Long Weekend", year_id: 27)
    Movie.create(title: "Looking for a Lady With Fangs and a Moustache", year_id: 27)
    Movie.create(title: "Lorelei", year_id: 27)
    Movie.create(title: "Los Hermanos / The Brothers", year_id: 27)
    Movie.create(title: "Los Últimos Frikis", year_id: 27)
    Movie.create(title: "Lost Course", year_id: 27)
    Movie.create(title: "The Lost Daughter", year_id: 27)
    Movie.create(title: "The Lost Leonardo", year_id: 27)
    Movie.create(title: "Lourdes", year_id: 27)
    Movie.create(title: "Love Hard", year_id: 27)
    Movie.create(title: "Love Is Love Is Love", year_id: 27)
    Movie.create(title: "Love It Was Not", year_id: 27)
    Movie.create(title: "Luca", year_id: 27)
    Movie.create(title: "Lucy, the Human Chimp", year_id: 27)
    Movie.create(title: "Lvx Æterna", year_id: 27)
    Movie.create(title: "LUZ", year_id: 27)
    Movie.create(title: "Luzzu", year_id: 27)
    Movie.create(title: "Lydia Lunch—The War Is Never Over", year_id: 27)
    Movie.create(title: "Ma Belle, My Beauty", year_id: 27)
    Movie.create(title: "The Macaluso Sisters", year_id: 27)
    Movie.create(title: "The Mad Women’s Ball", year_id: 27)
    Movie.create(title: "Madame Claude", year_id: 27)
    Movie.create(title: "Madres", year_id: 27)
    Movie.create(title: "Mafia Inc", year_id: 27)
    Movie.create(title: "Magnificent Coloring World", year_id: 27)
    Movie.create(title: "Mainstream", year_id: 27)
    Movie.create(title: "Malcolm & Marie", year_id: 27)
    Movie.create(title: "The Mali-Cuba Connection", year_id: 27)
    Movie.create(title: "Malignant", year_id: 27)
    Movie.create(title: "Malmkrog", year_id: 27)
    Movie.create(title: "Małni—Towards the Ocean, Towards the Shore", year_id: 27)
    Movie.create(title: "Mama Weed", year_id: 27)
    Movie.create(title: "A Man Named Scott", year_id: 27)
    Movie.create(title: "The Man Who Sold His Skin", year_id: 27)
    Movie.create(title: "Mandibles", year_id: 27)
    Movie.create(title: "The Manor", year_id: 27)
    Movie.create(title: "The Many Saints of Newark", year_id: 27)
    Movie.create(title: "The Map of Tiny Perfect Things", year_id: 27)
    Movie.create(title: "Marakkar: Lion of the Arabian Sea", year_id: 27)
    Movie.create(title: "Marighella", year_id: 27)
    Movie.create(title: "The Marijuana Conspiracy", year_id: 27)
    Movie.create(title: "Mark, Mary & Some Other People", year_id: 27)
    Movie.create(title: "Markie in Milwaukee", year_id: 27)
    Movie.create(title: "The Marksman", year_id: 27)
    Movie.create(title: "Martha: A Picture Story", year_id: 27)
    Movie.create(title: "Mass", year_id: 27)
    Movie.create(title: "Materna", year_id: 27)
    Movie.create(title: "The Matrix Resurrections", year_id: 27)
    Movie.create(title: "The Mauritanian", year_id: 27)
    Movie.create(title: "Mayday", year_id: 27)
    Movie.create(title: "Mayor Pete", year_id: 27)
    Movie.create(title: "The Meaning of Hitler", year_id: 27)
    Movie.create(title: "Mektoub, My Love: Intermezzo", year_id: 27)
    Movie.create(title: "Memoria", year_id: 27)
    Movie.create(title: "Memory House", year_id: 27)
    Movie.create(title: "Midnight in the Switchgrass", year_id: 27)
    Movie.create(title: "Minyan", year_id: 27)
    Movie.create(title: "Miracle Fishing: Kidnapped Abroad", year_id: 27)
    Movie.create(title: "The Misfits", year_id: 27)
    Movie.create(title: "Misha and the Wolves", year_id: 27)
    Movie.create(title: "Mr. Saturday Night", year_id: 27)
    Movie.create(title: "The Mitchells vs the Machines", year_id: 27)
    Movie.create(title: "MLK/FBI", year_id: 27)
    Movie.create(title: "Moby Doc", year_id: 27)
    Movie.create(title: "Moffie", year_id: 27)
    Movie.create(title: "Mogul Mowgli", year_id: 27)
    Movie.create(title: "Moments Like This Never Last", year_id: 27)
    Movie.create(title: "Monday", year_id: 27)
    Movie.create(title: "The Moneychanger", year_id: 27)
    Movie.create(title: "Monster Family 2", year_id: 27)
    Movie.create(title: "Mortal Kombat", year_id: 27)
    Movie.create(title: "Mosley", year_id: 27)
    Movie.create(title: "Mosquito State", year_id: 27)
    Movie.create(title: "The Most Beautiful Boy in the World", year_id: 27)
    Movie.create(title: "The Most Reluctant Convert: The Untold Story of C.S. Lewis", year_id: 27)
    Movie.create(title: "Mother/Android", year_id: 27)
    Movie.create(title: "A Mouthful of Air", year_id: 27)
    Movie.create(title: "Moving On", year_id: 27)
    Movie.create(title: "Moxie", year_id: 27)
    Movie.create(title: "Multiverse", year_id: 27)
    Movie.create(title: "Munich: The Edge of War", year_id: 27)
    Movie.create(title: "Music", year_id: 27)
    Movie.create(title: "The Mustangs: America’s Wild Horses", year_id: 27)
    Movie.create(title: "My Beautiful Stutter", year_id: 27)
    Movie.create(title: "My Country, My Parents", year_id: 27)
    Movie.create(title: "My Darling Supermarket", year_id: 27)
    Movie.create(title: "My Heart Can’t Beat Unless You Tell It To", year_id: 27)
    Movie.create(title: "My Hero Academia: World Heroes’ Mission", year_id: 27)
    Movie.create(title: "My Little Pony: A New Generation", year_id: 27)
    Movie.create(title: "My Little Sister", year_id: 27)
    Movie.create(title: "My Love", year_id: 27)
    Movie.create(title: "My Mexican Bretzel", year_id: 27)
    Movie.create(title: "My Name Is Bulger", year_id: 27)
    Movie.create(title: "My Name Is Pauli Murray", year_id: 27)
    Movie.create(title: "My Octopus Teacher", year_id: 27)
    Movie.create(title: "My People, My Homeland", year_id: 27)
    Movie.create(title: "My Rembrandt", year_id: 27)
    Movie.create(title: "My Salinger Year", year_id: 27)
    Movie.create(title: "My Wonderful Wanda", year_id: 27)
    Movie.create(title: "My Zoe", year_id: 27)
    Movie.create(title: "A Naija Christmas", year_id: 27)
    Movie.create(title: "Naked Singularity", year_id: 27)
    Movie.create(title: "National Champions", year_id: 27)
    Movie.create(title: "Needle in a Timestack", year_id: 27)
    Movie.create(title: "Never Gonna Snow Again", year_id: 27)
    Movie.create(title: "Never Stop", year_id: 27)
    Movie.create(title: "The New Bauhaus", year_id: 27)
    Movie.create(title: "New Order", year_id: 27)
    Movie.create(title: "The Night", year_id: 27)
    Movie.create(title: "The Night House", year_id: 27)
    Movie.create(title: "Night in Paradise", year_id: 27)
    Movie.create(title: "Night Raiders", year_id: 27)
    Movie.create(title: "Night Teeth", year_id: 27)
    Movie.create(title: "Nightbooks", year_id: 27)
    Movie.create(title: "Nightmare Alley", year_id: 27)
    Movie.create(title: "Nina Wu", year_id: 27)
    Movie.create(title: "Nine Days", year_id: 27)
    Movie.create(title: "915: Hunting Hispanics", year_id: 27)
    Movie.create(title: "No Future", year_id: 27)
    Movie.create(title: "No Man of God", year_id: 27)
    Movie.create(title: "No Man’s Land", year_id: 27)
    Movie.create(title: "No One Gets Out Alive", year_id: 27)
    Movie.create(title: "No Ordinary Man", year_id: 27)
    Movie.create(title: "No Responders Left Behind", year_id: 27)
    Movie.create(title: "No Sudden Move", year_id: 27)
    Movie.create(title: "No Time to Die", year_id: 27)
    Movie.create(title: "Nobody", year_id: 27)
    Movie.create(title: "North by Current", year_id: 27)
    Movie.create(title: "Not Going Quietly", year_id: 27)
    Movie.create(title: "Not to Forget", year_id: 27)
    Movie.create(title: "Notorious Nick", year_id: 27)
    Movie.create(title: "Notturno", year_id: 27)
    Movie.create(title: "The Novice", year_id: 27)
    Movie.create(title: "The Nowhere Inn", year_id: 27)
    Movie.create(title: "No. 7 Cherry Lane", year_id: 27)
    Movie.create(title: "Off the Rails", year_id: 27)
    Movie.create(title: "Oh Mercy", year_id: 27)
    Movie.create(title: "Old", year_id: 27)
    Movie.create(title: "Old Henry", year_id: 27)
    Movie.create(title: "On Broadway", year_id: 27)
    Movie.create(title: "The One and Only Dick Gregory", year_id: 27)
    Movie.create(title: "On-Gaku: Our Sound", year_id: 27)
    Movie.create(title: "Only the Animals", year_id: 27)
    Movie.create(title: "Operation Varsity Blues", year_id: 27)
    Movie.create(title: "Oscar-Nominated Shorts 2021: Animation", year_id: 27)
    Movie.create(title: "Oscar-Nominated Shorts 2021: Documentary", year_id: 27)
    Movie.create(title: "Oscar-Nominated Shorts 2021: Live-Action", year_id: 27)
    Movie.create(title: "Our Friend", year_id: 27)
    Movie.create(title: "Our Ladies", year_id: 27)
    Movie.create(title: "Our Towns", year_id: 27)
    Movie.create(title: "The Outside Story", year_id: 27)
    Movie.create(title: "Outside the Wire", year_id: 27)
    Movie.create(title: "The Outsider", year_id: 27)
    Movie.create(title: "Own the Room", year_id: 27)
    Movie.create(title: "Oxygen", year_id: 27)
    Movie.create(title: "Paddleton", year_id: 27)
    Movie.create(title: "Palmer", year_id: 27)
    Movie.create(title: "Paper & Glue", year_id: 27)
    Movie.create(title: "Paper Spiders", year_id: 27)
    Movie.create(title: "The Paper Tigers", year_id: 27)
    Movie.create(title: "Parallel Mothers", year_id: 27)
    Movie.create(title: "Paranormal Activity: Next of Kin", year_id: 27)
    Movie.create(title: "Paris Calligrammes", year_id: 27)
    Movie.create(title: "Passing", year_id: 27)
    Movie.create(title: "PAW Patrol: The Movie", year_id: 27)
    Movie.create(title: "Peepal Tree", year_id: 27)
    Movie.create(title: "Pelé", year_id: 27)
    Movie.create(title: "Penguin Bloom", year_id: 27)
    Movie.create(title: "Percy vs Goliath", year_id: 27)
    Movie.create(title: "The Perfect Candidate", year_id: 27)
    Movie.create(title: "A Perfect Enemy", year_id: 27)
    Movie.create(title: "Peter Rabbit 2: The Runaway", year_id: 27)
    Movie.create(title: "Petite Maman", year_id: 27)
    Movie.create(title: "The Phantom", year_id: 27)
    Movie.create(title: "Pharma Bro", year_id: 27)
    Movie.create(title: "Pig", year_id: 27)
    Movie.create(title: "Pink Skies Ahead", year_id: 27)
    Movie.create(title: "Pixie", year_id: 27)
    Movie.create(title: "The Place That Makes Us", year_id: 27)
    Movie.create(title: "Plan B", year_id: 27)
    Movie.create(title: "The Plastic House", year_id: 27)
    Movie.create(title: "Playing God", year_id: 27)
    Movie.create(title: "Playing With Beethoven", year_id: 27)
    Movie.create(title: "Playing With Sharks", year_id: 27)
    Movie.create(title: "Port Authority", year_id: 27)
    Movie.create(title: "Poupelle of Chimney Town", year_id: 27)
    Movie.create(title: "The Power", year_id: 27)
    Movie.create(title: "The Power of the Dog", year_id: 27)
    Movie.create(title: "Pray Away", year_id: 27)
    Movie.create(title: "Prayers for the Stolen", year_id: 27)
    Movie.create(title: "Preparations to Be Together for an Unknown Period of Time", year_id: 27)
    Movie.create(title: "Present.Perfect", year_id: 27)
    Movie.create(title: "President", year_id: 27)
    Movie.create(title: "The Price of Freedom", year_id: 27)
    Movie.create(title: "The Princess Switch 3: Romancing the Star", year_id: 27)
    Movie.create(title: "Prism", year_id: 27)
    Movie.create(title: "Prisoners of the Ghostland", year_id: 27)
    Movie.create(title: "Procession", year_id: 27)
    Movie.create(title: "Profile", year_id: 27)
    Movie.create(title: "The Projectionist", year_id: 27)
    Movie.create(title: "The Protégé", year_id: 27)
    Movie.create(title: "Psycho Goreman", year_id: 27)
    Movie.create(title: "Puaada", year_id: 27)
    Movie.create(title: "Pups Alone", year_id: 27)
    Movie.create(title: "Purple Sea", year_id: 27)
    Movie.create(title: "Pushpa, the Rise: Part – 01", year_id: 27)
    Movie.create(title: "PVT Chat", year_id: 27)
    Movie.create(title: "Queen Bees", year_id: 27)
    Movie.create(title: "Queen Marie", year_id: 27)
    Movie.create(title: "Queenpins", year_id: 27)
    Movie.create(title: "A Quiet Place Part II", year_id: 27)
    Movie.create(title: "Quo Vadis, Aida?", year_id: 27)
    Movie.create(title: "Radhe: Your Most Wanted Bhai", year_id: 27)
    Movie.create(title: "Raging Fire", year_id: 27)
    Movie.create(title: "Railway Heroes", year_id: 27)
    Movie.create(title: "Rams", year_id: 27)
    Movie.create(title: "Raya and the Last Dragon", year_id: 27)
    Movie.create(title: "The Real Charlie Chaplin", year_id: 27)
    Movie.create(title: "The Reason I Jump", year_id: 27)
    Movie.create(title: "Rebel Hearts", year_id: 27)
    Movie.create(title: "The Reckoning", year_id: 27)
    Movie.create(title: "Red Moon Tide", year_id: 27)
    Movie.create(title: "Red Notice", year_id: 27)
    Movie.create(title: "Red Pill", year_id: 27)
    Movie.create(title: "Red Post on Escher Street", year_id: 27)
    Movie.create(title: "Red Rocket", year_id: 27)
    Movie.create(title: "Reminiscence", year_id: 27)
    Movie.create(title: "Reopening Night", year_id: 27)
    Movie.create(title: "The Rescue", year_id: 27)
    Movie.create(title: "Resident Evil: Welcome to Raccoon City", year_id: 27)
    Movie.create(title: "Resort to Love", year_id: 27)
    Movie.create(title: "Respect", year_id: 27)
    Movie.create(title: "The Reunited States", year_id: 27)
    Movie.create(title: "Revolution of Our Times", year_id: 27)
    Movie.create(title: "Revolution Rent", year_id: 27)
    Movie.create(title: "Ride or Die", year_id: 27)
    Movie.create(title: "Ride the Eagle", year_id: 27)
    Movie.create(title: "Riders of Justice", year_id: 27)
    Movie.create(title: "Ridge", year_id: 27)
    Movie.create(title: "The Rifleman", year_id: 27)
    Movie.create(title: "The Rise and Fall of LuLaRoe", year_id: 27)
    Movie.create(title: "Risen", year_id: 27)
    Movie.create(title: "Rita Moreno: Just a Girl Who Decided to Go for It", year_id: 27)
    Movie.create(title: "Roadrunner: A Film About Anthony Bourdain", year_id: 27)
    Movie.create(title: "Rock, Paper and Scissors", year_id: 27)
    Movie.create(title: "Rockfield: The Studio on the Farm", year_id: 27)
    Movie.create(title: "Roe v. Wade", year_id: 27)
    Movie.create(title: "Rogue Hostage", year_id: 27)
    Movie.create(title: "Roh", year_id: 27)
    Movie.create(title: "Ron’s Gone Wrong", year_id: 27)
    Movie.create(title: "Roohi", year_id: 27)
    Movie.create(title: "Rose Plays Julie", year_id: 27)
    Movie.create(title: "Rumba Love", year_id: 27)
    Movie.create(title: "Rumble", year_id: 27)
    Movie.create(title: "Run Hide Fight", year_id: 27)
    Movie.create(title: "Running Against the Wind", year_id: 27)
    Movie.create(title: "Runt", year_id: 27)
    Movie.create(title: "Rushed", year_id: 27)
    Movie.create(title: "Ruth", year_id: 27)
    Movie.create(title: "Sabaya", year_id: 27)
    Movie.create(title: "Ste. Anne", year_id: 27)
    Movie.create(title: "Saint Maud", year_id: 27)
    Movie.create(title: "Saint-Narcisse", year_id: 27)
    Movie.create(title: "The Salt of Tears", year_id: 27)
    Movie.create(title: "Sandeep Aur Pinky Faraar", year_id: 27)
    Movie.create(title: "SAS: Red Notice", year_id: 27)
    Movie.create(title: "Saturday Fiction", year_id: 27)
    Movie.create(title: "Satyameva Jayate 2", year_id: 27)
    Movie.create(title: "Savage State", year_id: 27)
    Movie.create(title: "Saving Paradise", year_id: 27)
    Movie.create(title: "Scales", year_id: 27)
    Movie.create(title: "The Scary of Sixty-First", year_id: 27)
    Movie.create(title: "Scenes From an Empty Church", year_id: 27)
    Movie.create(title: "Schemes in Antiques", year_id: 27)
    Movie.create(title: "School Life", year_id: 27)
    Movie.create(title: "Sea of Lost Time", year_id: 27)
    Movie.create(title: "Seance", year_id: 27)
    Movie.create(title: "Searching for Mr. Rugoff", year_id: 27)
    Movie.create(title: "Seaspiracy", year_id: 27)
    Movie.create(title: "The Secret of Sinchanee", year_id: 27)
    Movie.create(title: "Senior Moment", year_id: 27)
    Movie.create(title: "Sensation", year_id: 27)
    Movie.create(title: "Sentinelle", year_id: 27)
    Movie.create(title: "Separation", year_id: 27)
    Movie.create(title: "Settlers", year_id: 27)
    Movie.create(title: "7 Prisoners", year_id: 27)
    Movie.create(title: "The Seventh Day", year_id: 27)
    Movie.create(title: "Shadow in the Cloud", year_id: 27)
    Movie.create(title: "Shang-Chi and the Legend of the Ten Rings", year_id: 27)
    Movie.create(title: "A Shape of Things to Come", year_id: 27)
    Movie.create(title: "She Had a Dream", year_id: 27)
    Movie.create(title: "Sheena667", year_id: 27)
    Movie.create(title: "Shepherd: The Story of a Jewish Dog", year_id: 27)
    Movie.create(title: "Shiva Baby", year_id: 27)
    Movie.create(title: "Shook", year_id: 27)
    Movie.create(title: "Shoplifters of the World", year_id: 27)
    Movie.create(title: "Short Vacation", year_id: 27)
    Movie.create(title: "Show Me the Father", year_id: 27)
    Movie.create(title: "Siberia", year_id: 27)
    Movie.create(title: "Silent Night", year_id: 27)
    Movie.create(title: "Silk Road", year_id: 27)
    Movie.create(title: "Silo", year_id: 27)
    Movie.create(title: "Simple as Water", year_id: 27)
    Movie.create(title: "Sin", year_id: 27)
    Movie.create(title: "Sing 2", year_id: 27)
    Movie.create(title: "Single All the Way", year_id: 27)
    Movie.create(title: "Sisters on Track", year_id: 27)
    Movie.create(title: "Sisters With Transistors", year_id: 27)
    Movie.create(title: "6:45", year_id: 27)
    Movie.create(title: "Six Minutes to Midnight", year_id: 27)
    Movie.create(title: "Skylab", year_id: 27)
    Movie.create(title: "Slalom", year_id: 27)
    Movie.create(title: "The Sleeping Negro", year_id: 27)
    Movie.create(title: "Slow Machine", year_id: 27)
    Movie.create(title: "Small Engine Repair", year_id: 27)
    Movie.create(title: "Snake Eyes: G.I. Joe Origins", year_id: 27)
    Movie.create(title: "Snakehead", year_id: 27)
    Movie.create(title: "Softie", year_id: 27)
    Movie.create(title: "Solitary", year_id: 27)
    Movie.create(title: "Some Kind of Heaven", year_id: 27)
    Movie.create(title: "Some of Our Stallions", year_id: 27)
    Movie.create(title: "Son", year_id: 27)
    Movie.create(title: "A Son", year_id: 27)
    Movie.create(title: "Son of Monarchs", year_id: 27)
    Movie.create(title: "Son of the South", year_id: 27)
    Movie.create(title: "Sooryavanshi", year_id: 27)
    Movie.create(title: "Soulmates", year_id: 27)
    Movie.create(title: "Sound of Violence", year_id: 27)
    Movie.create(title: "South of Heaven", year_id: 27)
    Movie.create(title: "The Souvenir Part II", year_id: 27)
    Movie.create(title: "The Space Between", year_id: 27)
    Movie.create(title: "Space Jam: A New Legacy", year_id: 27)
    Movie.create(title: "The Sparks Brothers", year_id: 27)
    Movie.create(title: "Speer Goes to Hollywood", year_id: 27)
    Movie.create(title: "Spencer", year_id: 27)
    Movie.create(title: "Spider-Man: No Way Home", year_id: 27)
    Movie.create(title: "The Spine of Night", year_id: 27)
    Movie.create(title: "Spiral", year_id: 27)
    Movie.create(title: "Spirit Untamed", year_id: 27)
    Movie.create(title: "The SpongeBob Movie: Sponge on the Run", year_id: 27)
    Movie.create(title: "Spring Blossom", year_id: 27)
    Movie.create(title: "The Starling", year_id: 27)
    Movie.create(title: "State Funeral", year_id: 27)
    Movie.create(title: "Still Life in Lodz", year_id: 27)
    Movie.create(title: "Stillwater", year_id: 27)
    Movie.create(title: "Stop and Go", year_id: 27)
    Movie.create(title: "Stop Filming Us", year_id: 27)
    Movie.create(title: "Stowaway", year_id: 27)
    Movie.create(title: "Stray", year_id: 27)
    Movie.create(title: "Street Gang: How We Got to Sesame Street", year_id: 27)
    Movie.create(title: "Strip Down, Rise Up", year_id: 27)
    Movie.create(title: "The Subject", year_id: 27)
    Movie.create(title: "Sublet", year_id: 27)
    Movie.create(title: "The Suicide Squad", year_id: 27)
    Movie.create(title: "Summer of 85", year_id: 27)
    Movie.create(title: "Summer of Soul (…or, When the Revolution Could Not Be Televised)", year_id: 27)
    Movie.create(title: "Summertime", year_id: 27)
    Movie.create(title: "The Summit of the Gods", year_id: 27)
    Movie.create(title: "Sun Children", year_id: 27)
    Movie.create(title: "Sunken Roads: Three Generations After D-Day", year_id: 27)
    Movie.create(title: "Sunrise/Sunset", year_id: 27)
    Movie.create(title: "Super Frenchie", year_id: 27)
    Movie.create(title: "Supernova", year_id: 27)
    Movie.create(title: "Surge", year_id: 27)
    Movie.create(title: "Survive the Game", year_id: 27)
    Movie.create(title: "Suzanna Andler", year_id: 27)
    Movie.create(title: "Swan Song (Benjamin Cleary)", year_id: 27)
    Movie.create(title: "Swan Song (Todd Stephens)", year_id: 27)
    Movie.create(title: "Sweat", year_id: 27)
    Movie.create(title: "Sweet Girl", year_id: 27)
    Movie.create(title: "Sweet Thing", year_id: 27)
    Movie.create(title: "Swimming Out Till the Sea Turns Blue", year_id: 27)
    Movie.create(title: "Sword Art Online: The Movie—Progressive—Aria of a Starless Night", year_id: 27)
    Movie.create(title: "Tadap", year_id: 27)
    Movie.create(title: "Tailgate", year_id: 27)
    Movie.create(title: "A Tale of Three Sisters", year_id: 27)
    Movie.create(title: "Tango Shalom", year_id: 27)
    Movie.create(title: "The Tender Bar", year_id: 27)
    Movie.create(title: "Test Pattern", year_id: 27)
    Movie.create(title: "Thalaivi", year_id: 27)
    Movie.create(title: "There Is No Evil", year_id: 27)
    Movie.create(title: "There Is No I in Threesome", year_id: 27)
    Movie.create(title: "There’s Someone Inside Your House", year_id: 27)
    Movie.create(title: "They Say Nothing Stays the Same", year_id: 27)
    Movie.create(title: "Things Heard & Seen", year_id: 27)
    Movie.create(title: "13 Minutes", year_id: 27)
    Movie.create(title: "3212 Un-redacted", year_id: 27)
    Movie.create(title: "This Game’s Called Murder", year_id: 27)
    Movie.create(title: "This Is Not a Burial, It’s a Resurrection", year_id: 27)
    Movie.create(title: "This Is Not a War Story", year_id: 27)
    Movie.create(title: "This Is the Night", year_id: 27)
    Movie.create(title: "This Is the Year", year_id: 27)
    Movie.create(title: "This Town", year_id: 27)
    Movie.create(title: "Those Who Wish Me Dead", year_id: 27)
    Movie.create(title: "Three Corners of Deception", year_id: 27)
    Movie.create(title: "Three Summers", year_id: 27)
    Movie.create(title: "Thunder Force", year_id: 27)
    Movie.create(title: "Tick, Tick… Boom!", year_id: 27)
    Movie.create(title: "Tigre Gente", year_id: 27)
    Movie.create(title: "’Til Kingdom Come", year_id: 27)
    Movie.create(title: "Till Death", year_id: 27)
    Movie.create(title: "Tina", year_id: 27)
    Movie.create(title: "Tiny Tim: King for a Day", year_id: 27)
    Movie.create(title: "Titane", year_id: 27)
    Movie.create(title: "Tlamess", year_id: 27)
    Movie.create(title: "To All the Boys: Always and Forever", year_id: 27)
    Movie.create(title: "Together", year_id: 27)
    Movie.create(title: "Together Together", year_id: 27)
    Movie.create(title: "Tom and Jerry", year_id: 27)
    Movie.create(title: "Tom Clancy’s Without Remorse", year_id: 27)
    Movie.create(title: "The Tomorrow War", year_id: 27)
    Movie.create(title: "Toofaan", year_id: 27)
    Movie.create(title: "Torn", year_id: 27)
    Movie.create(title: "Tove", year_id: 27)
    Movie.create(title: "The Tragedy of Macbeth", year_id: 27)
    Movie.create(title: "Tragic Jungle", year_id: 27)
    Movie.create(title: "The Trip", year_id: 27)
    Movie.create(title: "Triumph", year_id: 27)
    Movie.create(title: "Troop Zero", year_id: 27)
    Movie.create(title: "True Mothers", year_id: 27)
    Movie.create(title: "True to the Game 3", year_id: 27)
    Movie.create(title: "Truman & Tennessee: An Intimate Conversation", year_id: 27)
    Movie.create(title: "Truth or Consequences", year_id: 27)
    Movie.create(title: "Try Harder!", year_id: 27)
    Movie.create(title: "Tu me manques", year_id: 27)
    Movie.create(title: "The Tunnel", year_id: 27)
    Movie.create(title: "Twas the Night", year_id: 27)
    Movie.create(title: "12 Mighty Orphans", year_id: 27)
    Movie.create(title: "Twelve Thousand", year_id: 27)
    Movie.create(title: "23 Walks", year_id: 27)
    Movie.create(title: "2021 Sundance Film Festival Short Film Tour", year_id: 27)
    Movie.create(title: "Twilight’s Kiss", year_id: 27)
    Movie.create(title: "Twist", year_id: 27)
    Movie.create(title: "Two Gods", year_id: 27)
    Movie.create(title: "Two of Us", year_id: 27)
    Movie.create(title: "The Two Sights", year_id: 27)
    Movie.create(title: "Un film dramatique", year_id: 27)
    Movie.create(title: "Unapologetic", year_id: 27)
    Movie.create(title: "Under the Stadium Lights", year_id: 27)
    Movie.create(title: "Under the Volcano", year_id: 27)
    Movie.create(title: "Undine", year_id: 27)
    Movie.create(title: "The Unforgivable", year_id: 27)
    Movie.create(title: "The Unholy", year_id: 27)
    Movie.create(title: "The United States of Insanity", year_id: 27)
    Movie.create(title: "The United States vs. Billie Holiday", year_id: 27)
    Movie.create(title: "The Unspeakable", year_id: 27)
    Movie.create(title: "Untold: Caitlyn Jenner", year_id: 27)
    Movie.create(title: "Uppercase Print", year_id: 27)
    Movie.create(title: "Vacation Friends", year_id: 27)
    Movie.create(title: "Vakeel Saab", year_id: 27)
    Movie.create(title: "Val", year_id: 27)
    Movie.create(title: "Valley of Souls", year_id: 27)
    Movie.create(title: "The Vault", year_id: 27)
    Movie.create(title: "The Velvet Queen", year_id: 27)
    Movie.create(title: "The Velvet Underground", year_id: 27)
    Movie.create(title: "Vengeance Is Mine", year_id: 27)
    Movie.create(title: "Venom: Let There Be Carnage", year_id: 27)
    Movie.create(title: "V/H/S 94", year_id: 27)
    Movie.create(title: "The Viewing Booth", year_id: 27)
    Movie.create(title: "The Vigil", year_id: 27)
    Movie.create(title: "The Village Detective: A Song Cycle", year_id: 27)
    Movie.create(title: "Violation", year_id: 27)
    Movie.create(title: "The Violent Heart", year_id: 27)
    Movie.create(title: "Violet", year_id: 27)
    Movie.create(title: "The Virtuoso", year_id: 27)
    Movie.create(title: "Vital Behaviors", year_id: 27)
    Movie.create(title: "Vivo", year_id: 27)
    Movie.create(title: "A Voluntary Year", year_id: 27)
    Movie.create(title: "Voyagers", year_id: 27)
    Movie.create(title: "The Voyeurs", year_id: 27)
    Movie.create(title: "Waiting for the Carnival", year_id: 27)
    Movie.create(title: "Walking With Herb", year_id: 27)
    Movie.create(title: "The Walrus and the Whistleblower", year_id: 27)
    Movie.create(title: "Warning", year_id: 27)
    Movie.create(title: "The Water Man", year_id: 27)
    Movie.create(title: "We Broke Up", year_id: 27)
    Movie.create(title: "We Need to Do Something", year_id: 27)
    Movie.create(title: "A Week Away", year_id: 27)
    Movie.create(title: "Werewolves Within", year_id: 27)
    Movie.create(title: "West Side Story", year_id: 27)
    Movie.create(title: "Wet Season", year_id: 27)
    Movie.create(title: "WeWork, or The Making and Breaking of a $47 Billion Unicorn", year_id: 27)
    Movie.create(title: "What Do We See When We Look at the Sky?", year_id: 27)
    Movie.create(title: "What We Left Unfinished", year_id: 27)
    Movie.create(title: "Wheel of Fortune and Fantasy", year_id: 27)
    Movie.create(title: "When Hitler Stole Pink Rabbit", year_id: 27)
    Movie.create(title: "Whirlybird", year_id: 27)
    Movie.create(title: "White as Snow", year_id: 27)
    Movie.create(title: "White Lie", year_id: 27)
    Movie.create(title: "White on White", year_id: 27)
    Movie.create(title: "White People Money", year_id: 27)
    Movie.create(title: "The White Tiger", year_id: 27)
    Movie.create(title: "Who You Think I Am", year_id: 27)
    Movie.create(title: "Why Did You Kill Me?", year_id: 27)
    Movie.create(title: "Wife of a Spy", year_id: 27)
    Movie.create(title: "Wild Indian", year_id: 27)
    Movie.create(title: "Wildland", year_id: 27)
    Movie.create(title: "Wish Dragon", year_id: 27)
    Movie.create(title: "The Wishmas Tree", year_id: 27)
    Movie.create(title: "WITCH: We Intend to Cause Havoc", year_id: 27)
    Movie.create(title: "The Witches of the Orient", year_id: 27)
    Movie.create(title: "Without Getting Killed or Caught", year_id: 27)
    Movie.create(title: "Wojnarowicz: Fuck You Faggot Fucker", year_id: 27)
    Movie.create(title: "Wolf", year_id: 27)
    Movie.create(title: "Wolfgang", year_id: 27)
    Movie.create(title: "The Woman in the Window", year_id: 27)
    Movie.create(title: "The Woman Who Ran", year_id: 27)
    Movie.create(title: "Women Is Losers", year_id: 27)
    Movie.create(title: "Woodlands Dark and Days Bewitched: A History of Folk Horror", year_id: 27)
    Movie.create(title: "Woodstock 99: Peace, Love, and Rage", year_id: 27)
    Movie.create(title: "The Works and Days (of Tayoko Shiojiri in the Shiotani Basin)", year_id: 27)
    Movie.create(title: "The World to Come", year_id: 27)
    Movie.create(title: "The Worst Person in the World", year_id: 27)
    Movie.create(title: "Worth", year_id: 27)
    Movie.create(title: "Wrath of Man", year_id: 27)
    Movie.create(title: "A Writer’s Odyssey", year_id: 27)
    Movie.create(title: "Writing With Fire", year_id: 27)
    Movie.create(title: "Yaar Annmulle Returns", year_id: 27)
    Movie.create(title: "Yakuza Princess", year_id: 27)
    Movie.create(title: "The Year of the Discovery", year_id: 27)
    Movie.create(title: "The Year of the Everlasting Storm", year_id: 27)
    Movie.create(title: "Years of Construction", year_id: 27)
    Movie.create(title: "Yes Day", year_id: 27)
    Movie.create(title: "Yes I Am Student", year_id: 27)
    Movie.create(title: "You Mean Everything to Me", year_id: 27)
    Movie.create(title: "You Will Die at Twenty", year_id: 27)
    Movie.create(title: "Young Hearts", year_id: 27)
    Movie.create(title: "The Youngest Evangelist", year_id: 27)
    Movie.create(title: "Zeros and Ones", year_id: 27)
    Movie.create(title: "Zone 414", year_id: 27)
    Movie.create(title: "Zumiriki", year_id: 27)
  end
end
